package utilities;

import frame.About_Frame;
import frame.Menu;
import java.awt.Image;
import javax.swing.ImageIcon;

public class Diagram_View extends javax.swing.JFrame {

    private DiagramViewer previousDiagramViewer = null;
    String[] options1 = new String[]{
        "ProgLanguages",
        "C_Datatypes",
        "C++_Datatypes",
        "Java_Datatypes",
        "Java_Access_modifiers",
        "DataStructures",
        "Python_Datatypes",
        "JavaScript_Datatypes",
        "CodingPractices",
        "Classification",
        "TypesOfLanguages",
        "UsesOfLanguages"
    };
    String[] options2 = new String[]{
        "RestApi",
         "ApiGateWay",
        "ApiPerformance",
        "WebsitePerformanceMetrics",
        "ProgramVsProcessVsThread"
    };
    String[] options3 = new String[]{
        "SQL",
        "Javaswing",
        "JVM",
        "12Factors",
        "BestMicroServices",
        "DevSecOps"
    };
    String[] options4 = new String[]{
        "htmltags",
        "HttpRequests",
        "MicroServicesArchitecture"
    };
    String[] options5 = new String[]{
        "Graphs",
        "TreeTravsersal",
        "AI",
        "NeuralNetworks",
        "MachineLearning"
    };
    String[] options6 = new String[]{
        "RoadMap",
        "LinuxFileSystem",
        "LinuxBootProcess",
        "AWSArchitecture",
        "ForwardVsReverseProxy"
    };

    /**
     * Creates new form Diagram_View
     */
    public Diagram_View() {
        setLocationRelativeTo(null);
        setLocationByPlatform(true);
        setResizable(false);
        setTitle("Diagram-Viewer");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>(options1);
        jComboBox2 = new javax.swing.JComboBox<String>(options2);
        ;
        jComboBox3 = new javax.swing.JComboBox<String>(options3);
        ;
        jComboBox4 = new javax.swing.JComboBox<String>(options4);
        ;
        jComboBox5 = new javax.swing.JComboBox<String>(options5);
        ;
        jComboBox6 = new javax.swing.JComboBox<String>(options6);
        ;
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox1.setToolTipText("programming languages related");
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox2.setToolTipText("<html>choose any option below if you want to choose 1st <br> open any other frame first<br> then you can choose it<html>");
        jComboBox2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox3.setToolTipText("<html>choose any option below if you want to choose 1st <br> open any other frame first<br> then you can choose it<html>");
        jComboBox3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox4.setToolTipText("<html>choose any option below if you want to choose 1st <br> open any other frame first<br> then you can choose it<html>");
        jComboBox4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox5.setToolTipText("<html>choose any option below if you want to choose 1st <br> open any other frame first<br> then you can choose it<html>");
        jComboBox5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(255, 204, 102));
        jComboBox6.setToolTipText("<html>choose any option below if you want to choose 1st <br> open any other frame first<br> then you can choose it<html>");
        jComboBox6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Choose Any Topic Below");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Welcome ");

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Diagrams Section");

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backbutton.png"))); // NOI18N
        jButton1.setText("TO MENU");
        jButton1.setToolTipText("press to mobve back main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("About");
        jButton2.setToolTipText("press to open about frame");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit_btn.png"))); // NOI18N
        jButton3.setToolTipText("press to exit from application");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("To");

        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/diagram.jpeg"));
        Image image = icon.getImage().getScaledInstance(180,125,Image.SCALE_SMOOTH);
        ImageIcon icon2 = new ImageIcon(image);
        jLabel1.setIcon(icon2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(26, 26, 26))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu.getInstance().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged

        int selectedIndex = jComboBox4.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedItem = jComboBox4.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "htmltags" ->
                    diagramViewer = new DiagramViewer("Html-Tag-list", "htmltags");
                case "HttpRequests" ->
                    diagramViewer = new DiagramViewer("HTTP-Requests-Modes", "httprequestmodes");
                case "MicroServicesArchitecture" ->
                    diagramViewer = new DiagramViewer("Typical-MicroServices-Architecture", "mvc");

            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged

        int selectedIndex = jComboBox3.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedItem = jComboBox3.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "SQL" ->
                    diagramViewer = new DiagramViewer("SQL-Introduction", "sql");
                case "Javaswing" ->
                    diagramViewer = new DiagramViewer("Java-swing-tree", "swingdiagram");
                case "JVM" ->
                    diagramViewer = new DiagramViewer("Java-Code", "javacode");
                case "12Factors" ->
                    diagramViewer = new DiagramViewer("12-Factors", "12factor");
                case "BestMicroServices" ->
                    diagramViewer = new DiagramViewer("Best-Microservices-Practices", "bestmicroservices");
                case "DevSecOps" ->
                    diagramViewer = new DiagramViewer("DevSecOPs", "devsceops");

            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        int selectedIndex = jComboBox2.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedItem = jComboBox2.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "RestApi" ->
                    diagramViewer = new DiagramViewer("Rest-API-Authentication", "restapi");
                case "ApiGateWay" ->
                    diagramViewer = new DiagramViewer("Api-GateWay", "apigateway");
                case "ApiPerformance" ->
                    diagramViewer = new DiagramViewer("Api-Performance", "apiperformance");
                case "WebsitePerformanceMetrics" ->
                    diagramViewer = new DiagramViewer("Website-Performance-Metrics", "websiteperformancemetrics");
                case "ProgramVsProcessVsThread" ->
                    diagramViewer = new DiagramViewer("Program-Process-Thread", "pVsPVsTh");

            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        int selectedIndex = jComboBox1.getSelectedIndex();
        if (selectedIndex != -1 && selectedIndex!=0) {
            String selectedItem = jComboBox1.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "C_Datatypes" ->
                    diagramViewer = new DiagramViewer("C_DataTypes", "cdatatypes");
                case "C++_Datatypes" ->
                    diagramViewer = new DiagramViewer("C++_DataTypes", "c++datatypes");
                case "Java_Datatypes" ->
                    diagramViewer = new DiagramViewer("Java_DataTypes", "javadatatypes");
                case "Java_Access_modifiers" ->
                    diagramViewer = new DiagramViewer("Java_Access_Modifiers", "accessmodifiers");
                case "DataStructures" ->
                    diagramViewer = new DiagramViewer("Primitive_Vs_Reference_Data_Types", "DSC");
                case "Python_Datatypes" ->
                    diagramViewer = new DiagramViewer("Python_DataTypes", "pythondatatypes");
                case "JavaScript_Datatypes" ->
                    diagramViewer = new DiagramViewer("JavaScript_DataTypes", "jsdatatypes");
                case "CodingPractices" ->
                    diagramViewer = new DiagramViewer("BestCodingPractices", "codingpractices");
                case "Classification" ->
                    diagramViewer = new DiagramViewer("ProgrammingLanguages-Classification", "planguages");
                case "TypesOfLanguages" ->
                    diagramViewer = new DiagramViewer("Types-Of-Languages", "typesplanguages");
                case "UsesOfLanguages" ->
                    diagramViewer = new DiagramViewer("Programming-Languages-Usecases", "planguagesuse");
            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed


    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed


    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged

        int selectedIndex = jComboBox5.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedItem = jComboBox5.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "Graphs" ->
                    diagramViewer = new DiagramViewer("Types_Graphs", "graphs");
                case "TreeTravsersal" ->
                    diagramViewer = new DiagramViewer("Tree_Traversal_Techinques", "tree");
                case "AI" ->
                    diagramViewer = new DiagramViewer("AI-Branches", "ai");
                case "NeuralNetworks" ->
                    diagramViewer = new DiagramViewer("Neural-Networks", "neuralnetwork");
                case "MachineLearning" ->
                    diagramViewer = new DiagramViewer("Machine-Learning", "mlearning");

            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged

        int selectedIndex = jComboBox6.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedItem = jComboBox6.getItemAt(selectedIndex);
            DiagramViewer diagramViewer = null;
            switch (selectedItem) {
                case "RoadMap" ->
                    diagramViewer = new DiagramViewer("Road-Map-TO-SeniorDeveloper", "roadmap");
                case "LinuxFileSystem" ->
                    diagramViewer = new DiagramViewer("Linux-File-System", "linuxfilesystem");
                case "LinuxBootProcess" ->
                    diagramViewer = new DiagramViewer("Linux-Boot-Process", "linuxbootprocess");
                case "AWSArchitecture" ->
                    diagramViewer = new DiagramViewer("AWS-Network-Architecture", "websiteperformancemetrics");
                case "ForwardVsReverseProxy" ->
                    diagramViewer = new DiagramViewer("Forward-Reverse-Proxy", "proxy");

            }
            if (diagramViewer != null) {
                diagramViewer.setVisible(true);
                // Dispose the  previous instance
                if (previousDiagramViewer != null) {
                    previousDiagramViewer.dispose();
                }
                previousDiagramViewer = diagramViewer;
            }
        }
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        About_Frame.getInstance().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagram_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Diagram_View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
