package ninthListFrames;

import frame.Quiz;


/**
 * @author MuhammadHasnatRasool
 */
public class Google_Ads_Quiz extends Quiz {

    public Google_Ads_Quiz(String name) {
        super(name);
        loadQuestions();
        setupQuiz();
    }

    private void setupQuiz() {
        shuffleIndices();
        selectTotalQuestions();
        setCurrentQuestion();
        setQuestionTextAndOptions();
    }
    @Override
    public void setQuestionTextAndOptions() {
        qno.setText("Question #: " + currentQno);
        question.setText(questions.get(currentQuestionIndex));
        opt1.setText(options.get(currentQuestionIndex).split(", ")[0]);
        opt2.setText(options.get(currentQuestionIndex).split(", ")[1]);
        opt3.setText(options.get(currentQuestionIndex).split(", ")[2]);
        opt4.setText(options.get(currentQuestionIndex).split(", ")[3]);
    }

    // questions:53
    @Override
    public final void loadQuestions() {

        questions.add(" Which ad component has three fields that allow 30 characters each?");
        options.add("A)the headline, B)the description, C)the website URL, D)the call-to-action");
        answers.add("A)the headline");

        questions.add(" When reviewing the **Recommendations** page, you identify a suggestion that you want to use. What is the most practical way to implement the suggestion?");
        options.add("A)Copy the optimization visit the ad group and past the optimization., B)Follow the step-by-step instructions., C)Visit the ad group click the **Optimization** drop-down and select **Apply All**., D)Click **Apply** on the recommendation.");
        answers.add("D)Click **Apply** on the recommendation.");

        questions.add(" Griff has noticed that his best-performing keywords have started to see an increased CPC, despite no changes on his part. What is the most likely reason for this?");
        options.add("A)ad Quality Score increase, B)reduction of landing page inbound links, C)reduction in daily budget, D)increased competition");
        answers.add("D)increased competition");

        questions.add(" You are running a campaign that will consist of 15 ads. What is the minimum number of ad groups that you can have as part of the campaign?");
        options.add("A)1, B)5, C)3, D)15");
        answers.add("A)1");

        questions.add(" Braxton has his maximum bid set to $5. His competitor bids $3.95. How much will Braxton pay upon winning the auction?");
        options.add("A)$3.96, B)$3.95, C)$4, D)$5");
        answers.add("A)$3.96");

        questions.add(" Maurice creates an ad headline that reads \"Buy **{Keyword:hats}** Today\". Which headline could `not` be displayed to a user for this ad?");
        options.add("A)Buy Caps Today, B)Buy Helmets Today, C)Buy Fedoras Today, D)Buy Hats");
        answers.add("B)Buy Helmets Today");

        questions.add(" Which choice is `not` an option when configuring `ad` extensions?");
        options.add("A)product extensions, B)sitelink extensions, C)message extensions, D)callout extensions");
        answers.add("A)product extensions");

        questions.add(" Which choice is the best practice when designing a landing page for an ad campaign?");
        options.add("A)having lots of inbound links, B)using JavaScript, C)relevant content matching the ad, D)enrolling in Ad Central");
        answers.add("C)relevant content matching the ad");

        questions.add(" Which choice has no impact on Quality Score?");
        options.add("A)ad relevance, B)expected clickthrough rate, C)landing page experience, D)max CPC bid");
        answers.add("D)max CPC bid");

        questions.add(" Marcelina wants to know how many sales her Google Ads brought in. What should she set up?");
        options.add("A)target CPA bidding, B)conversion tracking, C)custom deep links, D)custom display URLs");
        answers.add("B)conversion tracking");

        questions.add(" Kellan creates an ad headline that reads \"Buy **{Keyword:Shoes}** Today\". What is this an example of?");
        options.add("A)automatic headline replacement, B)keyword insertion, C)dynamic bidding, D)auto replacement");
        answers.add("B)keyword insertion");

        questions.add(" What factors does Google Ads take into account when determining whether a remarketing list qualifies for inclusion in a similar audiences list?");
        options.add("A)the number of visitors on the list, B)the amount of revenue generated by the list, C)the average bid targeting the list, D)the average monthly spend targeting the list");
        answers.add("A)the number of visitors on the list");

        questions.add(" An auction has a normal bid of $.50 but there is an active bid adjustment of -20%. What is the final bid amount?");
        options.add("A)$0.40, B)$0.60, C)$0.04, D)$0.06");
        answers.add("A)$0.40");

        questions.add(" Raisa starting running a new ad campaign a month ago. Without making any changes, she noticed that her CPC has gone down significantly in the last week. What could have caused this?");
        options.add("A)a decrease in ad Quality Score, B)an increase in daily budget, C)changes in competitor campaigns, D)an increase of landing page inbound links");
        answers.add("C)changes in competitor campaigns");

        questions.add(" Which ad rotation setting uses machine learning to prioritize ads based upon expected performance?");
        options.add("A)Rotate evenly, B)Optimize, C)Manual rotation, D)Rotate indefinitely");
        answers.add("B)Optimize");

        questions.add(" Clara is running retargeted display ads, but does not want her audience to experience ad fatique. What should be configure?");
        options.add("A)ad scheduling, B)a frequency cap, C)an impression cap, D)auto ad rotation");
        answers.add("D)auto ad rotation");

        questions.add(" If someone performs a search for \"most comfortable chair\", which ad description text would likely perform the best?");
        options.add("A)Don't be uncomfortable. Get a new chair. Try the LumbarPro today., B)Experience the most comfortable chair with more than 1000 five-star reviews., C)Try the LumbarPro a chair that has been reviewed as comfortable by more than 1000 people., D)Need a new chair? The LumbarPro is the highest rated chair. Try this chair today.");
        answers.add("B)Experience the most comfortable chair, with more than 1,000 five-star reviews.");

        questions.add(" Why would you use callout extensions?");
        options.add("A)to share pricing on various business offerings, B)to highlight key features and unique offers, C)to show reviews of your product or service, D)to add phone numbers to the ad");
        answers.add("B)to highlight key features and unique offers");

        questions.add(" You have a maximum CPC bid of $4 for the keyword **Coffee Mugs**. What tool could you use to determine the projected result of raising the bid to $4.50?");
        options.add("A)CPC Optimizer, B)Bid Simulator, C)Google Analytics, D)Lighthouse");
        answers.add("A)CPC Optimizer");

        questions.add(" Which keyword status is not valid?");
        options.add("A)Geographically restricted, B)Under review, C)Paused, D)Eligible");
        answers.add("A)Geographically restricted");

        questions.add(" When reviewing a campaign, you notice that your cost per conversion on desktop is much lower than on mobile. How should you optimize the bidding strategy is you wanted to increase the overall number of campaign conversions?");
        options.add("A)Increase the desktop bid adjustment for this campaign, B)Increase the ad frequency for the campaign, C)Decrease the desktop bid adjustment for the campaign, D)Increase both the desktop and mobile ad adjustments");
        answers.add("A)Increase the desktop bid adjustment for this campaign");

        questions.add(" With Google's Active View technology, when is an impression of a display ad considered viewable?");
        options.add("A)when the user leaves the page the ad appears on, B)when any part of the ad is on-screen for 5 seconds, C)when the entire ad first appears on the screen, D)when at least 50% of the ad is on-screen for at least 1 second");
        answers.add("D)when at least 50% of the ad is on-screen for at least 1 second");

        questions.add(" Rhama wants to increase her bids for any customers that are within a selected radius of her storefront. What would you recommend she do?");
        options.add("A)Create a location bid adjustment, B)Use automated bidding, C)Create an ad group with higher bids targeted to that geographical region, D)Restrict the campaign to only the radius");
        answers.add("C)Create an ad group with higher bids, targeted to that geographical region");

        questions.add(" The standard approach to submitting product data to Google Ads is through the use of a product **____**.");
        options.add("A)link, B)ad, C)feed, D)extension");
        answers.add("C)feed");

        questions.add(" In order to create a similat audience, you must provide Google Ads with **_________**.");
        options.add("A)a budget, B)a tracking pixel, C)all of these answers, D)a seed list of users");
        answers.add("D)a seed list of users");

        questions.add(" How do responsive search ads increase your likelihood of reaching more customers?");
        options.add("A)They provide multiple headline and description options so ads automatically evolve based on performance., B)Responsive search ads are mobile optimized, C)All of these answers, D)Responsive reach ads receive preferential treatment in the google ads auction");
        answers.add("C)All of these answers");

        questions.add(" Sion is having a sale that will last three days. He wants his ad text to show how much time is remaining in the sale. Would would you recoment for Sion?");
        options.add("A)Use the sale extension and set the sale duration for each time zone., B)Do not include the sale in the ad text as this likley violated Google Ads editorial policies., C)Add a countdown customizer to the ad text., D)Manually adjust the ad text as frequently as possible to reflect the time remaining");
        answers.add("C)Add a countdown customizer to the ad text.");

        questions.add(" Tabitha has a mobile application that is complementary to her website. She wants to make it known to potential customers, but driving app downloads is not her main goal. What would you recommend she configure on her Google Ads?");
        options.add("A)app extension, B)Universal App campaign, C)Mobile App campaign, D)download extension");
        answers.add("A)app extension");

        questions.add(" Which solution allows you to show ads in Google search results, only if the user has previously visited your website?");
        options.add("A)MDC, B)ECPC, C)RLSA, D)Target ROAS");
        answers.add("C)RLSA");

        questions.add(" Why are aad extensions beneficial?");
        options.add("A)They increase the character count for descriptions and headlines, B)They expand the ad and tend to increase the clickthrough rate, C)They allow you to integrate your data with third-party platforms such as Google Analytics, D)They reduce the overall cost of your campaigns");
        answers.add("B)They expand the ad and tend to increase the clickthrough rate");

        questions.add(" In a text ad, the display URL is made up of the domain from your final URL and up to two **_____**.");
        options.add("A)descriptions, B)paths, C)keywords, D)tracking tags");
        answers.add("B)paths");

        questions.add(" Within the Display Network, locations where your ad can appear are referred to as _______.");
        options.add("A)ad slots, B)placements, C)landing pages, D)displays");
        answers.add("B)placements");

        questions.add(" Which setting lets you monitor how certain criteria perform with your ads without limiting reach?");
        options.add("A)remarketing, B)conversion value, C)targeting, D)observation");
        answers.add("D)observation");

        questions.add(" Tory manages marketing for a hotel franchise with a thousand locations worldwide. Each hotel location has its own landing page. If Tory wanted to quickly generate search ads for every location, which ad type would be most beneficial?");
        options.add("A)Dynamic Search Ads, B)Responsive Search Ads, C)Universal Search Ads, D)Programmatic Search Ads");
        answers.add("C)Universal Search Ads");

        questions.add(" Janice operates a brand-new dry cleaning business, with five locations throughout Ireland. What would be a good way to organize a campaign announcing the grand opening?");
        options.add("A)one campaign with an ad group for each location, B)one ad group containing all locations, C)one ad group for each service, D)one campaign for each location");
        answers.add("A)one campaign with an ad group for each location");

        questions.add(" What is ad frequency?");
        options.add("A)the total number of impressions your advertisement receives, B)the total number of users who clicked on your advertisement, C)the number of times a single user will see your advertisement, D)the number of visitors who completed the checkout process");
        answers.add("C)the number of times a single user will see your advertisement");

        questions.add(" Which metric does not help in understanding your ROI?");
        options.add("A)production costs, B)frequency, C)revenue, D)cost per conversion");
        answers.add("B)frequency");

        questions.add(" Which choice represents the hierarchy of search campaigns in Google Ads?");
        options.add("A)ads > keywords > campaign, B)campaign > ad group > ads, C)keywords > campaign > ads, D)ad group > campaign > ads");
        answers.add("B)campaign > ad group > ads");

        questions.add(" If you continuously search for your own advertisement using Google, just to confirm that it appears, it is very likely that you will inflate your  ____ and decrease your ____  .");
        options.add("A)impressions; clickthrough rate, B)conversions; ROI, C)clickthrough rate; impressions, D)ROI; conversions");
        answers.add("A)impressions; clickthrough rate");

        questions.add(" Which report would most accurately show how far away users are when clicking your ads in relation to the location of your business?");
        options.add("A)dimension report, B)geographic report, C)distance report, D)user location report");
        answers.add("C)distance report");

        questions.add(" If your average daily budge is $20, what is the maximum amount Google Ads may charge you on a single day?");
        options.add("A)$22, B)$20, C)$40, D)$36");
        answers.add("C)$40");

        questions.add(" Ursula owns a yoga studio in New York City (NYC). A customer performs several searches in the following order: \"yoga studio near me\", \"best yoga NYC\", \"yoga free trial NYC\". What attribution model would assign 100% of the credit for the conversion to _____ yoga free trial NYC ____?");
        options.add("A)last position, B)last search, C)linear, D)last click");
        answers.add("D)last click");

        questions.add(" Farhann is running advertisements that are targetting only Italy, but he sees that his ads are receiving clicks from people in Greece. What is the most likely reason?");
        options.add("A)Italian people visiting Greece are searching for \"best restaurant in Greece\", B)People in Greece are conducting searches such as \"best restaurant in Italy\", C)Greek people visiting Italy are searching for \"best restaurants in Italy\", D)People in Italy are conducting searches such as \"best restaurants in Greece\"");
        answers.add("B)People in Greece are conducting searches such as \"best restaurant in Italy\"");

        questions.add(" Which average daily budget will maximize the number of impressions you receive, but ensure that you will never spend more than $45 in a single day?");
        options.add("A)$22, B)$44, C)$30, D)$15");
        answers.add("A)$22");

        questions.add(" Linzi wants to her ads to show up at the very top of the search result page, regardless of what it costs. What would you suggest she do in order to show in the top result a specified percentage of the time?");
        options.add("A)Inform Linzi this is not possible, B)Use the Target Impression Share bid strategy, C)Use the maximum bid amount as suggested by Keyword Planner, D)Create an ad group with top of page as the only location target");
        answers.add("A)Inform Linzi this is not possible");

        questions.add(" What destination URL would you need to configure to send traffic directly to a page within a mobile app?");
        options.add("A)universal link, B)path link, C)app link, D)deep link");
        answers.add("B)path link");

        questions.add(" Why is it important to know your cost per conversion?");
        options.add("A)You can compare your cost per conversion to your competitors, B)All of these answers, C)Your cost per conversion helps you understand your ROI, D)A lower cost per conversion will improve your ad rank");
        answers.add("C)Your cost per conversion helps you understand your ROI");

        questions.add(" Mark has configured ad extensions for every campaign, but his ads never show them. What is the most likely explanation?");
        options.add("A)The Ad Rank is too low, B)The bidding strategy is not set to ECPC, C)The search query has misspellings, D)The bid is too low");
        answers.add("A)The Ad Rank is too low");

        questions.add(" What tool should you use to determine where your ad will appear for a particular search query?");
        options.add("A)Placement Optimization and Preview, B)Bid Optimizer, C)Ad Preview and Diagnosis, D)Keyword Planner");
        answers.add("C)Ad Preview and Diagnosis");

        questions.add(" You sell piano keyboards, but your ads also appear when people search for \"computer keyboards\". What should you do?");
        options.add("A)Add an exact match keyword as piano., B)Add an exact match keyword as computer., C)Add a negative keyword for computer., D)Add a negative keyword for keyboards.");
        answers.add("C)Add a negative keyword for **computer**.");

        questions.add(".52. You want to determine exactly what search terms triggered your ads to display. What do you do?");
        options.add("A)Review the attribution report., B)Review the bidding report., C)Review the search terms report., D)Review the keyword frequency report.");
        answers.add("D)Review the keyword frequency report.");

        questions.add(".53. Which statement is true when structuring ad groups?");
        options.add("A)Adding more ads to an ad group will improve the likelihood of multiple ads appearing for a search query., B)Adding more ads to an ad group provides more chances for success in an auction., C)Adding fewer ads to an ad group will improve the likelihood of an ad receiving a high-quality score., D)Adding fewer ads to an ad group means higher bounce rates.");
        answers.add("B)Adding more ads to an ad group provides more chances for success in an auction.");

        questions.add(".54. Patrick sells hats, and has added [womens hats] to his keyword list. Which search term will not trigger Patrick's ad to display?");
        options.add("A)the women's hats, B)hat for women, C)women's hats, D)sewing womens hats");
        answers.add("A)the women's hats");

    }

    public static void main(String[] args) {
        new Google_Ads_Quiz(name).setVisible(true);
    }

}
