package secondListFrames;

import frame.Quiz;

public class Computer_Quiz extends Quiz {
   
    public Computer_Quiz(String name) {
        super(name);
        loadQuestions();
        System.out.println(questions.size());
        setupQuiz();
    }

    private void setupQuiz() {
        shuffleIndices();
        selectTotalQuestions();
        setCurrentQuestion();
        setQuestionTextAndOptions();
    }

   
    @Override
    public void setQuestionTextAndOptions() {
        qno.setText("Question #: " + currentQno);
        question.setText(questions.get(currentQuestionIndex));
        opt1.setText(options.get(currentQuestionIndex).split(", ")[0]);
        opt2.setText(options.get(currentQuestionIndex).split(", ")[1]);
        opt3.setText(options.get(currentQuestionIndex).split(", ")[2]);
        opt4.setText(options.get(currentQuestionIndex).split(", ")[3]);
    }

    // 200 questions
    @Override
    public final void loadQuestions() {
        questions.add("The digital computer was developed primarily in");
	options.add("A) USSR, B) Japan, C) USA, D) UK");
	answers.add("C) USA");
	questions.add("The memory which is programmed at the time it is manufactured");
	options.add("A) POM, B) RAM, C) PROM, D) EPROM");
	answers.add("A) POM");
	questions.add("The first firm to mass-market a microcomputer as a personal computer was");
	options.add("A) IBM, B) super UNIVAC, C) Radio Shaks, D) Data General Corporation");
	answers.add("C) Radio Shaks");
	questions.add("ASCII stands for");
	options.add("A) American Stable Code for International Interchange, B) American Standard Case for Institutional Interchange, C) American Standard Code for Information Interchange, D) American Standard Code for Interchange Information");
	answers.add("C) American Standard Code for Information Interchange");
	questions.add("When did arch rivals IBM and Apple Computers In C. decide to join hands?");
	options.add("A) 1991, B) 1978, C) 1984, D) 1990");
	answers.add("A) 1991");
	questions.add("The subject of cybernetics deals with the science of");
	options.add("A) genetics, B) control and communications, C) molecular biology, D) biochemistry");
	answers.add("B) control and communications");
	questions.add("Which of the following memory medium is not used as main memory system?");
	options.add("A) magnetic core, B) semiconductor, C) magnetic tape, D) both a and b");
	answers.add("C) magnetic tape");
	questions.add("A digital computer did not score over, an analog computer in terms of");
	options.add("A) speed, B) accuracy, C) reliability, D) cost");
	answers.add("B) accuracy");
	questions.add("Which of the following is first generation of computer?");
	options.add("A) EDSAC, B) IBM-1401, C) CDC-1604, D) ICL-2900");
	answers.add("A) EDSAC");
	questions.add("Human beings are referred to as Homosapinens, which device is called Silicon Sapiens?");
	options.add("A) monitor, B) hardware, C) robot, D) computer");
	answers.add("D) computer");
	questions.add("Who is credited with the idea of using punch cards to control patterns of a weaving machine?");
	options.add("A) Pascal, B) Hollerith, C) Jacquard, D) Babbage");
	answers.add("C) Jacquard");
	questions.add("Registers, which are partially visible to users and used to hold conditional, are known as");
	options.add("A) PC, B) memory address register, C) general purpose register, D) flags");
	answers.add("C) general purpose register");
	questions.add("In 1830, Charles Babbage designed a machine called analytical engine, which he showed at the parts exhibition. In which year was it exhibited?");
	options.add("A) 1860, B) 1820, C) 1855, D) 1970");
	answers.add("C) 1855");
	questions.add("Chief component of first generation computer was");
	options.add("A) transistors, B) vacuum tubes and valves, C) integrated circuits, D) none of them");
	answers.add("B) vacuum tubes and valves");
	questions.add("An error in software or hardware is called a bug. What is the alternative computer jargon for it?");
	options.add("A) leech, B) sued, C) slug, D) glitch");
	answers.add("D) glitch");
	questions.add("FoxPro is");
	options.add("A) a medicine, B) a disease, C) a computer language, D) an animal");
	answers.add("C) a computer language");
	questions.add("Most of the inexpensive personal computer does not have any disk or diskette drive. What is the name");
	options.add("A) home computers, B) diskless computers, C) dedicated computers, D) general computers");
	answers.add("A) home computers");
	questions.add("One of the main feature that distinguish microprocessors from micro-computers is");
	options.add("A) words are usually larger in microprocessors, B) words are shorter in microprocessors, C) microprocessors does not contain I/O devices, D) exactly the same as the machine cycle time");
	answers.add("C) microprocessors does not contain I/O devices");
	questions.add("Which was the world's first minicomputer and when was it introduced?");
	options.add("A) PDP-I, 1958, B) IBM System/36, 1960, C) PDP-II, 1961, D) VAX 11/780, 1962");
	answers.add("A) PDP-I, 1958");
	questions.add("FORTRAN is");
	options.add("A) File Translation, B) Format Translation, C) Formula Translation, D) Floppy Translation");
	answers.add("C) Formula Translation");
	questions.add("Modern Computer are very reliable but they are not");
	options.add("A) fast, B) powerful, C) infallible, D) cheap");
	answers.add("C) infallible");
	questions.add("Which of the following required large computer memory?");
	options.add("A) imaging, B) graphics, C) voice, D) all of them");
	answers.add("D) all of them");
	questions.add("The least significant bit of the binary number, which is equivalent to any odd decimal number, is");
	options.add("A) 0, B) 1, C) 1 or 0, D) 3");
	answers.add("A) 0");
	questions.add("UNIVAC is");
	options.add("A) Universal Automatic Computer, B) Universal Array Computer, C) Unique Automatic Computer, D) Unvalued Automatic Computer");
	answers.add("A) Universal Automatic Computer");
	questions.add("EEPROM stands for");
	options.add("A) Electrically Erasable Programmable Read Only Memory, B) Easily Erasable Programmable Real Only Memory, C) Electronic Erasable Programmable Read Only Memory, D) none of them");
	answers.add("A) Electrically Erasable Programmable Read Only Memory");
	questions.add("What is the name of the display feature that highlights are of the screen. Which requires imperator");
	options.add("A) pixel, B) reverse video, C) touch screen, D) cursor");
	answers.add("B) reverse video");
	questions.add("Super Computer was invented by");
	options.add("A) J.H. Van Tassel, B) J.C Perrier, C) W.L. Judson, D) A.J. Garnering");
	answers.add("A) J.H. Van Tassel");
	questions.add("A term associated with the comparison of processing speeds of different computer system is");
	options.add("A) EFTS, B) MPG, C) MIPS, D) CFPS");
	answers.add("C) MIPS");
	questions.add("What type of control pins are needed in a microprocessor to regulate traffic on the bus, in order to");
	options.add("A) bus control, B) interrupts, C) bus arbitration, D) status");
	answers.add("C) bus arbitration");
	questions.add("CD-ROM stands for");
	options.add("A) Compactable Read Only Memory, B) Compact Data Read Only Memory, C) Compactable Disk Read Only Memory, D) Compact Disk Read Only Memory");
	answers.add("D) Compact Disk Read Only Memory");
	questions.add("Second Generations computers were developed during");
	options.add("A) 1949 to 1955, B) 1956 to 1965, C) 1965 to 1970, D) 1970 to 1990");
	answers.add("B) 1956 to 1965");
	questions.add("IBM launched its first personal computer called IBM-PC in 1981. It has chips from Intel, disk drives from");
	options.add("A) India, B) China, C) Germany, D) Taiwan");
	answers.add("D) Taiwan");
	questions.add("Which of the following terms is not associated with computers?");
	options.add("A) Frank land reaction, B) data base, C) binary, D) windows");
	answers.add("A) Frank land reaction");
	questions.add("Which of the following code used in present day computing was developed by IBM Corporation?");
	options.add("A) ASCII, B) Hollerith Code, C) Baudot Code, D) EBCDIC Code");
	answers.add("D) EBCDIC Code");
	questions.add("The processes of starting or restarting a computer system by loading instructions from a secondary");
	options.add("A) duping, B) booting, C) padding, D) all of them");
	answers.add("B) booting");
	questions.add("When was the world's first laptop computer introduced in the market and by whom?");
	options.add("A) Hewlett-Packard, B) Epson, 1981, C) Tandy model - 2002, 1985, D) Laplink traveling software in 1982");
	answers.add("B) Epson, 1981");
	questions.add("ALU is");
	options.add("A) Arithmetic Logic Unit, B) Array Logic Unit, C) Application Logic Unit, D) none of them");
	answers.add("A) Arithmetic Logic Unit");
	questions.add("The computer size was very large in");
	options.add("A) First Generation, B) Second Generation, C) Third Generation, D) Fourth Generation");
	answers.add("A) First Generation");
	questions.add("Personal computers use a number of chips mounted on a main circuit boarD. What is the common name");
	options.add("A) breadboard, B) daughter board, C) motherboard, D) father board");
	answers.add("C) motherboard");
	questions.add("The special files of DOS are");
	options.add("A) COM, B) EXE, C) BATCH, D) all of them");
	answers.add("D) all of them");
	questions.add("Who invented the microprocessor?");
	options.add("A) Marcian E Huff, B) Herman H Goldstein, C) Joseph Jacquard, D) all of them");
	answers.add("A) Marcian E Huff");
	questions.add("The first microprocessor built by the Intel Corporation was called");
	options.add("A) 8008, B) 8080, C) 4004, D) 8800");
	answers.add("C) 4004");
	questions.add("VGA is");
	options.add("A) Video Graphics Array, B) Visual Graphics Array, C) Volatile Graphics Array, D) Video Graphics Adapter");
	answers.add("A) Video Graphics Array");
	questions.add("Microprocessors as switching devices are for which generation computers");
	options.add("A) First Generation, B) Second Generation, C) Third Generation, D) Fourth Generation");
	answers.add("D) Fourth Generation");
	questions.add("In most IBM PCs, the CPU, the device drives, memory expansion slots and active components are");
	options.add("A) breadboard, B) daughter board, C) motherboard, D) father board");
	answers.add("C) motherboard");
	questions.add("(Binary Codes) as used in computer sciences are codes made up of which of the following two numbers?");
	options.add("A) 0 and 9, B) 1 and 3, C) 0 and 1, D) 9 and 1");
	answers.add("C) 0 and 1");
	questions.add("What is the latest write-once optical storage media?");
	options.add("A) digital paper, B) magneto-optical disk, C) WORM disk, D) CD-ROM disk");
	answers.add("D) CD-ROM disk");
	questions.add("One computer that is not considered a portable computer is");
	options.add("A) minicomputer, B) a laptop computer, C) both a and b, D) none of them");
	answers.add("A) minicomputer");
	questions.add("Who built the world's first electronic calculator using telephone relays, light bulbs and batteries");
	options.add("A) Claude Shannon, B) Konrard Zeus, C) George Stibits, D) Howard H. Aiken");
	answers.add("C) George Stibits");
	questions.add("IBM 1401 is");
	options.add("A) First Generation computer, B) Second Generation computer, C) Third Generation computer, D) Fourth Generation computer");
	answers.add("B) Second Generation computer");
	questions.add("Which of the devices can be used to directly image printed text?");
	options.add("A) OCR, B) OMR, C) MICR, D) all of them");
	answers.add("A) OCR");
	questions.add("What is meant by a dedicated computer?");
	options.add("A) which is used by one person only, B) which is assigned one and only task, C) which uses one kind of software, D) which is meant for application software");
	answers.add("B) which is assigned one and only task");
	questions.add("Bill Gates is more well-known as");
	options.add("A) the CEO of apple Macintosh, B) the CEO of IBM, C) the owner of Microsoft Corporation, D) the inventor of the personal computer");
	answers.add("C) the owner of Microsoft Corporation");
	questions.add("The most important advantage of a video disk is");
	options.add("A) compactness, B) potential capacity, C) durability, D) cost effectiveness");
	answers.add("B) potential capacity");
	questions.add("The accuracy of the floating-point number representable in two 16-bit words of a computer is");
	options.add("A) 16 digits, B) 6 digits, C) 9 digits, D) all of them");
	answers.add("B) 6 digits");
	questions.add("Who developed a mechanical device in the 17th century that could add, subtract, multiple, divide and");
	options.add("A) Napier, B) Babbage, C) Pascal, D) Leibniz");
	answers.add("D) Leibniz");
	questions.add("MSI stands for");
	options.add("A) Medium Scale Integrated Circuits, B) Medium System Integrated Circuits, C) Medium Scale Intelligent Circuit, D) Medium System Intelligent Circuit");
	answers.add("A) Medium Scale Integrated Circuits");
	questions.add("The output quality of a printer is measured my");
	options.add("A) dot per inch, B) dot per s. inch, C) dots printed per unit time, D) all of them");
	answers.add("B) dot per s. inch");
	questions.add("The system unit of a personal computer typically contains all of the following except");
	options.add("A) microprocessor, B) disk controller, C) serial interface, D) modem");
	answers.add("D) modem");
	questions.add("Which of the following is the unit to express the memory of a computer?");
	options.add("A) complier, B) bus, C) byte, D) clone");
	answers.add("C) byte");
	questions.add("What is the number of read-write heads in the drive for a 9-trac magnetic tape?");
	options.add("A) 9, B) 16, C) 18, D) 27");
	answers.add("A) 9");
	questions.add("A dumb terminal has");
	options.add("A) an embedded microcomputer, B) extensive memory, C) independent processing, D) a keyboard and screen");
	answers.add("D) a keyboard and screen");
	questions.add("IBM 7000 digital computer");
	options.add("A) belongs to second generation, B) uses VLSI, C) employs semi conductor memory, D) has modular constructions");
	answers.add("D) has modular constructions");
	questions.add("The capacity of 3.5 inch floppy disk is");
	options.add("A) 1.40 MB, B) 1.44 GB, C) 1.40 GB, D) 1.44 MB");
	answers.add("D) 1.44 MB");
	questions.add("In analog computer");
	options.add("A) input is first converted to digital form, B) input is never converted to digital form, C) output is displayed in digital form, D) all of them");
	answers.add("B) input is never converted to digital form");
	questions.add("A computer program that converts an entire program into machine language is called a/an");
	options.add("A) interpreter, B) simulator, C) compiler, D) commander");
	answers.add("C) compiler");
	questions.add("Which one of the following characteristics is absent in a computer, however sophisticated it may be?");
	options.add("A) high speed, B) intelligence, C) accuracy, D) perfect memory");
	answers.add("B) intelligence");
	questions.add("Before a disk drive can access any sector record, a computer program has to provide the record's disk address. What information does this address specify?");
	options.add("A) track number, B) sector number, C) surface number, D) all of them");
	answers.add("D) all of them");
	questions.add("Plotter accuracy is measured in terms of repeatable and");
	options.add("A) buffer size, B) resolution, C) vertical dimensions, D) intelligence");
	answers.add("B) resolution");
	questions.add("As integrated circuit is");
	options.add("A) a complicated circuit, B) an integrating device, C) much costlier than a single transistor, D) fabricated on a tiny silicon chip");
	answers.add("D) fabricated on a tiny silicon chip");
	questions.add("The first computer introduced in Nepal was");
	options.add("A) IBM 1400, B) IBM 1401, C) IBM 1402, D) IBM 1403");
	answers.add("B) IBM 1401");
	questions.add("In latest generation computers the instructions are executed");
	options.add("A) parallel only, B) sequentially only, C) both sequentially and parallel, D) all of them");
	answers.add("C) both sequentially and parallel");
	questions.add("A computer program that translates one program instructions at a time into machine language is called a/an");
	options.add("A) interpreter, B) CPU, C) compiler, D) simulator");
	answers.add("A) interpreter");
	questions.add("The ALU of a computer responds to the commands coming from");
	options.add("A) primary memory, B) control section, C) external memory, D) cache memory");
	answers.add("B) control section");
	questions.add("As compared to diskettes, the hard disks are");
	options.add("A) more expensive, B) more portable, C) less rigid, D) slowly accessed");
	answers.add("A) more expensive");
	questions.add("Dot-matric is a type of");
	options.add("A) tape, B) printer, C) disk, D) bus");
	answers.add("B) printer");
	questions.add("Daisy wheel printer is a type of");
	options.add("A) matrix printer, B) impact printer, C) laser printer, D) manual printer");
	answers.add("B) impact printer");
	questions.add("Most important advantages of an IC is its");
	options.add("A) easy replacement in case of circuit failure, B) extremely high reliability, C) reduced cost, D) low powers consumption");
	answers.add("B) extremely high reliability");
	questions.add("WAN stands for");
	options.add("A) Wap Area Network, B) Wide Area Network, C) Wide Array Net, D) Wireless Area Network");
	answers.add("B) Wide Area Network");
	questions.add("Who designed the first electronics computer - ENIAC?");
	options.add("A) Van-Neumann, B) Joseph M. Jacquard, C) J. Presper Eckert and John W Mauchly, D) all of them");
	answers.add("C) J. Presper Eckert and John W Mauchly");
	questions.add("A small or intelligent device is so called because it contains within it a");
	options.add("A) computer, B) microcomputer, C) programmable, D) sensor");
	answers.add("D) sensor");
	questions.add("The act of retrieving existing data from memory is called");
	options.add("A) read-out, B) read from, C) read, D) all of them");
	answers.add("D) all of them");
	questions.add("Floppy disks which are made from feasible plastic material are also called");
	options.add("A) hark disks, B) high-density disks, C) diskettes, D) templates");
	answers.add("C) diskettes");
	questions.add("The number of records contained within a block of data on magnetic tape is defined by the");
	options.add("A) block definition, B) record contain clause, C) blocking factor, D) record per block factor");
	answers.add("C) blocking factor");
	questions.add("The first machine to successfully perform a long series of arithmetic and logical operations was");
	options.add("A) ENIAC, B) Mark-I, C) Analytic Engine, D) UNIVAC-1");
	answers.add("B) Mark-I");
	questions.add("MICR stands for");
	options.add("A) Magnetic Ink Character Reader, B) Magnetic Ink Code Reader, C) Magnetic Ink Cases Reader, D) none of them");
	answers.add("D) none of them");
	questions.add("Who invented the high level language c?");
	options.add("A) Dennis M. Ritchie, B) Nicklaus Writh, C) Seymour Papert, D) Donald Kunth");
	answers.add("A) Dennis M. Ritchie");
	questions.add("Which of the following is not a programming language?");
	options.add("A) basic, B) FORTRAN, C) LASER, D) PASCAL");
	answers.add("C) LASER");
	questions.add("All modern computer operate on");
	options.add("A) information, B) floppies, C) data, D) word");
	answers.add("C) data");
	questions.add("Regarding a VDU, which statement is more correct?");
	options.add("A) it is an output device, B) it is an input device, C) it is a peripheral device, D) it is hardware item");
	answers.add("C) it is a peripheral device");
	questions.add("Serial access memories are useful in applications where");
	options.add("A) data consists of numbers, B) each stored word is processed differently, C) short access time is required, D) data naturally needs to flow in and out in a serial form");
	answers.add("D) data naturally needs to flow in and out in a serial form");
	questions.add("In the third Generation of computers");
	options.add("A) distributed data processing first became popular, B) an operating system was first developed, C) high level procedural language were first used, D) online real time systems first become popular");
	answers.add("D) online real time systems first become popular");
	questions.add("EBCDIC stands for");
	options.add("A) Extended Binary Coded Decimal Interchange Code, B) Extended Bit Code Decimal Interchange Code, C) Extended Bit Case Decimal Interchange Code, D) Extended Binary Case Decimal Interchange Code");
	answers.add("A) Extended Binary Coded Decimal Interchange Code");
	questions.add("Personnel who design, program, operate and maintain computer equipment refers to");
	options.add("A) console-operator, B) programmer, C) peopleware, D) system analyst");
	answers.add("C) peopleware");
	questions.add("The technical term not related to computer systems");
	options.add("A) virus, B) Winchester disk, C) mouse, D) FIFO system");
	answers.add("D) FIFO system");
	questions.add("Instructions and memory address are represented by");
	options.add("A) character code, B) binary codes, C) binary word, D) parity bit");
	answers.add("B) binary codes");
	questions.add("What is the name of the computer terminal which gives paper printout?");
	options.add("A) display screen, B) soft copy terminal, C) hard copy terminal, D) plotter");
	answers.add("C) hard copy terminal");
	questions.add("BCD is");
	options.add("A) Binary Coded Decimal, B) Bit Coded Decimal, C) Binary Coded Digit, D) Bit Coded Digit");
	answers.add("A) Binary Coded Decimal");
	questions.add("An IBM system/38 represents the computer class of");
	options.add("A) small scale computer, B) medium scale computer, C) large scale computer, D) super computer");
	answers.add("A) small scale computer");
	questions.add("Which of the following memories must be refreshed many times per second?");
	options.add("A) static RAM, B) dynamic RAM, C) EPROM, D) ROM");
	answers.add("B) dynamic RAM");
	questions.add("Two kinds of main memory are");
	options.add("A) primary and secondary, B) random and sequential, C) ROM and RAM, D) all of them");
	answers.add("C) ROM and RAM");
	questions.add("Latency time is");
	options.add("A) time to spin the needed data under head, B) time to spin the needed data under track, C) time to spin data under sector, D) all of them");
	answers.add("A) time to spin the needed data under head");
	questions.add("Easily relocatable language is");
	options.add("A) machine language, B) assembly language, C) high level language, D) medium level language");
	answers.add("B) assembly language");
	questions.add("A floppy disk contains");
	options.add("A) circular tracks only, B) sectors only, C) both circular tracks and sectors, D) all of them");
	answers.add("C) both circular tracks and sectors");
	questions.add("The first electronic general purpose digital computer built by Mauchly and Eckert called ENIA did not work on the stored program principle. How many numbers could it store in its internal memory?");
	options.add("A) 100, B) 20, C) 40, D) 80");
	answers.add("B) 20");
	questions.add("An integrated circuit is");
	options.add("A) a complicated circuit, B) an integrating device, C) much costlier than a single transistor, D) fabricated on a tiny silicon chip");
	answers.add("D) fabricated on a tiny silicon chip");
	questions.add("A kind of serial dot-matrix printer than forms characters with magnetically-charged ink sprayed dost is called");
	options.add("A) laser printer, B) ink-jet printer, C) drum printer, D) chart printer");
	answers.add("B) ink-jet printer");
	questions.add("Floppy disks are available in");
	options.add("A) single side single density, B) single side double density, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is called low level languages?");
	options.add("A) machine language, B) assembly language, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("The octal equivalent of 111010 is");
	options.add("A) 81, B) 72, C) 71, D) none of them");
	answers.add("B) 72");
	questions.add("The digital computer was developed primarily in");
	options.add("A) USSR, B) Japan, C) USA, D) UK");
	answers.add("C) USA");
	questions.add("Most important advantages of an IC is its");
	options.add("A) easy replacement in case of circuit failure, B) extremely high reliability, C) reduced cost, D) lower power consumption");
	answers.add("B) extremely high reliability");
	questions.add("Which of the following is true?");
	options.add("A) fields are composed of bytes, B) records are composed of fields, C) fields are composed of characters, D) all of them");
	answers.add("D) all of them");
	questions.add("The latest PC keyboards use a circuit that senses the movement by the change in its capacitance");
	options.add("A) capacitance keyboard, B) mechanical keyboard, C) qwerty keyboard, D) dvorak keyboard");
	answers.add("A) capacitance keyboard");
	questions.add("Which printer is very commonly used for desktop publishing?");
	options.add("A) laser printer, B) inkjet printer, C) daisywheel printer, D) dot-matrix printer");
	answers.add("A) laser printer");
	questions.add("Floppy disks typically in diameter");
	options.add("A) 3, B) 5.25, C) 8, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is problem oriented language?");
	options.add("A) high level language, B) machine language, C) assembly language, D) low level language");
	answers.add("A) high level language");
	questions.add("The first electronic computer in the world was");
	options.add("A) UNIVAC, B) EDVAC, C) ENIAC, D) all of them");
	answers.add("C) ENIAC");
	questions.add("The subject of cybernetics deals with the science of");
	options.add("A) genetics, B) control and communications, C) molecular biology, D) biochemistry");
	answers.add("B) control and communications");
	questions.add("In a punched card system, data is processed by a");
	options.add("A) keypunch machine, sorter and posting machine, B) accounting machine, posting machine and billing machine, C) sorter, posting machine, and billing machine, D) accounting machine, keypunch machine and sorter");
	answers.add("D) accounting machine, keypunch machine and sorter");
	questions.add("Which of the following file organization is most efficient for a file with a high degree of file activity?");
	options.add("A) sequential, B) ISAM, C) VSAM, D) B-Tree Index");
	answers.add("A) sequential");
	questions.add("An output device that uses words or messages recorded on a magnetic medium to produce audio response is");
	options.add("A) magnetic tape, B) voice response unit, C) voice recognition unit, D) voice band");
	answers.add("B) voice response unit");
	questions.add("Hard disk is coated in both side above");
	options.add("A) magnetic metallic oxide, B) optical metallic oxide, C) carbon layer, D) all of them");
	answers.add("A) magnetic metallic oxide");
	questions.add("A complier is a translating program which");
	options.add("A) translates instruction of a high language into machine language, B) translates entire source program into machine language program, C) it is not involved in program's execution, D) all of them");
	answers.add("D) all of them");
	questions.add("The most commonly used standard data code to represent alphabetical, numerical and punctuation characters used in electronic data processing system is called");
	options.add("A) ASCII, B) EBCDIC, C) BCD, D) all of them");
	answers.add("A) ASCII");
	questions.add("Who is credited with the idea of using punch cards to control patterns of a weaving machine?");
	options.add("A) Pascal, B) Hollerith, C) Babbage, D) Jacquard");
	answers.add("D) Jacquard");
	questions.add("The first machine to successfully perform a long series of arithmetic and logical operations was");
	options.add("A) ENIAC, B) Mark-I, C) Analytic Engine, D) UNIVAC-1");
	answers.add("B) Mark-I");
	questions.add("The two basic types of record-access methods are");
	options.add("A) sequential and random, B) sequential and indexed, C) direct and immediate, D) on-line and real time");
	answers.add("A) sequential and random");
	questions.add("Different components on the motherboard of a PC processor unit are linked together by sets or parallel electrical conducting lines. What are these lines called?");
	options.add("A) conductors, B) buses, C) connectors, D) connectivity");
	answers.add("B) buses");
	questions.add("Which of the following will happen when data is entered into memory location?");
	options.add("A) it will add to the content of the location, B) it will change the address of the memory location, C) it will erase the previous content, D) it will not be fruitful if there is already some data at the location");
	answers.add("C) it will erase the previous content");
	questions.add("Binary circuit elements have");
	options.add("A) one stable state, B) two stable state, C) three stable state, D) none of them");
	answers.add("B) two stable state");
	questions.add("Which of the following is machine independence program?");
	options.add("A) high level language, B) low level language, C) assembly language, D) machine language");
	answers.add("A) high level language");
	questions.add("Which was the computer conceived by Babbage?");
	options.add("A) analytical engine, B) arithmetic machine, C) Donald Kunth, D) all of them");
	answers.add("A) analytical engine");
	questions.add("Most of the inexpensive personal computer does not have any disk or diskette drive. What is the name of such computers/");
	options.add("A) home computers, B) diskless computers, C) dedicated computers, D) general purpose computers");
	answers.add("A) home computers");
	questions.add("In the third Generation of computers");
	options.add("A) distributed data processing first became popular, B) an operating system was first developed, C) high-level procedural languages were first used, D) online real time systems first become popular");
	answers.add("D) online real time systems first become popular");
	questions.add("The advantage of COM are its _______ and ______");
	options.add("A) compact size; speed readability, B) compact size; speed, C) readability; speed, D) low cost; readability");
	answers.add("B) compact size; speed");
	questions.add("A storage area used to store data to compensate for the difference in speed at which the different units can handle data is");
	options.add("A) memory, B) buffer, C) accumulator, D) address");
	answers.add("B) buffer");
	questions.add("Which statement is valid?");
	options.add("A) 1 KB = 1024 bytes, B) 1 MB = 2048 bytes, C) 1 MB = 1000 kilobytes, D) 1 KB = 1000 bytes");
	answers.add("A) 1 KB = 1024 bytes");
	questions.add("Which statement is valid about interpreter?");
	options.add("A) it translates one instruction at a time, B) object code is saved for future use, C) repeated interpretation is not necessary, D) all of them");
	answers.add("A) it translates one instruction at a time");
	questions.add("Offline device is");
	options.add("A) a device which is not connected to CPU, B) a device which is connected to CPU, C) a direct access storage device, D) an I/O device");
	answers.add("A) a device which is not connected to CPU");
	questions.add("Which of the following required large computer memory?");
	options.add("A) imaging, B) graphics, C) voice, D) all of them");
	answers.add("D) all of them");
	questions.add("A characteristic of card systems is");
	options.add("A) slowness in processing data, B) using cards as records of transactions, C) needing a larger DP staff, D) all of them");
	answers.add("D) all of them");
	questions.add("A disadvantage of the laser printer is");
	options.add("A) it is quieter than an impact printer, B) it is very slow, C) the output is of a lower quality, D) none of them");
	answers.add("D) none of them");
	questions.add("Which statement is valid about magnetic tape?");
	options.add("A) it is a plastic ribbon, B) it is coated on both sides with iron oxide, C) it can be erased and reused, D) all of them");
	answers.add("A) it is a plastic ribbon");
	questions.add("Which statement is valid about computer program?");
	options.add("A) it is understood by a computer, B) it is understood by programmer, C) it is understood user, D) all of them");
	answers.add("D) all of them");
	questions.add("Which is the limitation of high level language?");
	options.add("A) lower efficiency, B) machine dependence, C) machine level coding, D) none of them");
	answers.add("A) lower efficiency");
	questions.add("Which of the following registers is loaded with the contents of the memory location pointed by the PC?");
	options.add("A) memory address registers, B) memory data registers, C) instruction register, D) program counter");
	answers.add("C) instruction register");
	questions.add("A term associated with the comparison of processing speeds of different computer system is");
	options.add("A) EFTS, B) MPG, C) MIPS, D) CPS");
	answers.add("C) MIPS");
	questions.add("An IBM system/38 represents the computer class of");
	options.add("A) small scale computer, B) medium scale computer, C) large scale computer, D) super computer");
	answers.add("A) small scale computer");
	questions.add("Which of the following is not true for a magnetic disk?");
	options.add("A) it is expensive relative to magnetic tape, B) it provides only sequential access to stored data, C) users can easily update records by writing over the old data, D) all of them");
	answers.add("B) it provides only sequential access to stored data");
	questions.add("Which of the following magazines covers only the IBM PC and its compatibles");
	options.add("A) byte, B) PC magazine, C) personal computing, D) interface age");
	answers.add("B) PC magazine");
	questions.add("The data recording format in most of the modern magnetic tape is");
	options.add("A) 7-bit ASCII, B) 7-bit EBCDIC, C) 8-bit ASCII, D) 8-bit EBCDIC");
	answers.add("D) 8-bit EBCDIC");
	questions.add("Software in computer");
	options.add("A) enhances the capabilities of hardware machine, B) increase the speed of central processing unit, C) both a and b, D) none of them");
	answers.add("A) enhances the capabilities of hardware machine");
	questions.add("High level language is also called");
	options.add("A) problem oriented language, B) business oriented language, C) mathematically oriented language, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following registers is used to keep track of address of the memory location where the next instruction is located?");
	options.add("A) memory address registers, B) memory data register, C) instruction register, D) program counter");
	answers.add("D) program counter");
	questions.add("The processes of starting or restarting a computer system by loading instructions from a secondary storage device into the completer memory is called");
	options.add("A) duping, B) booting, C) padding, D) CPS");
	answers.add("B) booting");
	questions.add("The first firm to mass-market a microcomputer as a personal computer was");
	options.add("A) IBM, B) Sperry Univac, C) Data General Corporation, D) Radio Shack");
	answers.add("C) Data General Corporation");
	questions.add("The primary advantage of key-to-tape data entry system is");
	options.add("A) a large percentage of editing can be performed at the time of data entry, B) key verification is easily performed, C) the tape is reusable, D) keying errors can be detected as they occur");
	answers.add("C) the tape is reusable");
	questions.add("Which of the following professions has not been affected by personal computers?");
	options.add("A) medical, B) clerical and law, C) accounting, D) none of them");
	answers.add("D) none of them");
	questions.add("Which of the following is associated with error detector?");
	options.add("A) odd parity bit, B) even parity bit, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is not computer language?");
	options.add("A) high level language, B) medium level language, C) low level language, D) all of them");
	answers.add("B) medium level language");
	questions.add("A computer programmer");
	options.add("A) does all the thinking for a computer, B) can enter input data quickly, C) can operate all types of computer equipment, D) can draw only flowchart");
	answers.add("A) does all the thinking for a computer");
	questions.add("Microprocessors can be used to make");
	options.add("A) computers, B) digital systems, C) calculators, D) all of them");
	answers.add("D) all of them");
	questions.add("Who invented the microprocessor?");
	options.add("A) Marcian E Huff, B) Herman H Goldstein, C) Joseph Jacquard, D) all of them");
	answers.add("A) Marcian E Huff");
	questions.add("A digital computer did not score over, an analog computer in terms of");
	options.add("A) speed, B) accuracy, C) cost, D) memory");
	answers.add("B) accuracy");
	questions.add("The terminal device that functions as a cash register, computer terminal and OCR reader is the");
	options.add("A) Data collection terminal, B) OCR register terminal, C) Video Display terminal, D) POS terminal");
	answers.add("D) POS terminal");
	questions.add("Tape speed is measured in");
	options.add("A) feet per second, B) inch per second, C) meter per second, D) centimeter per second");
	answers.add("B) inch per second");
	questions.add("Which language is directly understood by the computer without translation program?");
	options.add("A) machine language, B) assembly language, C) high level language, D) none of them");
	answers.add("A) machine language");
	questions.add("CD-ROM is a");
	options.add("A) semiconductor memory, B) memory register, C) magnetic memory, D) none of them");
	answers.add("D) none of them");
	questions.add("How many address lines are needed to address each machine location in a 2048*4 memory chip?");
	options.add("A) 10, B) 11, C) 8, D) 12");
	answers.add("B) 11");
	questions.add("One computer that is not considered a portable computer is");
	options.add("A) minicomputer, B) laptop computer, C) notebook computer, D) all of them");
	answers.add("A) minicomputer");
	questions.add("In 1830, Charles Babbage designed a machine called analytical engine, which he showed at the parts exhibition. In which year was it exhibited?");
	options.add("A) 1820, B) 1860, C) 1855, D) 1870");
	answers.add("C) 1855");
	questions.add("Which of the following does not affect the resolution of a video display image?");
	options.add("A) Bandwidth, B) raster scan rage, C) vertical and horizontal lines of resolution, D) screen size");
	answers.add("D) screen size");
	questions.add("The arranging of data in a logical sequence is called");
	options.add("A) sorting, B) classifying, C) reproducing, D) summarizing");
	answers.add("A) sorting");
	questions.add("Magnetic disks are the most popular medium for");
	options.add("A) direct access, B) sequential access, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Instruction in computer languages consists of");
	options.add("A) OPCODE, B) OPERAND, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is not a primary storage device?");
	options.add("A) magnetic tape, B) magnetic disk, C) optical disk, D) none of them");
	answers.add("D) none of them");
	questions.add("Which American computer company is called Big Blue?");
	options.add("A) Microsoft, B) Compa Corp, C) IBM, D) Tandy Svenson");
	answers.add("C) IBM");
	questions.add("IBM 7000 digital computer");
	options.add("A) belongs to second generation, B) uses VLSI, C) employs semi conductor memory, D) has modular constructions");
	answers.add("C) employs semi conductor memory");
	questions.add("Which was the world's first minicomputer and when was it introduced?");
	options.add("A) PDP-I, 1958, B) IBM System/36, 1960, C) PDP-II, 1961, D) VAX 11/780, 1962");
	answers.add("A) PDP-I, 1958");
	questions.add("While inserting a diskette into the diskette drive of a PC, the diskette's label side should face");
	options.add("A) east, B) north, C) south, D) up");
	answers.add("D) up");
	questions.add("When was Apple Macintosh II microcomputer introduced in the market?");
	options.add("A) 1964, B) 1970, C) 1983, D) 1986");
	answers.add("C) 1983");
	questions.add("Storage capacity of magnetic disk depends on");
	options.add("A) tracks per inch of surface, B) bits per inch of tracks, C) disk pack in disk surface, D) all of them");
	answers.add("D) all of them");
	questions.add("Machine language is");
	options.add("A) machine dependent, B) difficult to program, C) error prone, D) all of them");
	answers.add("D) all of them");
	questions.add("A name or number used to identify a storage location devices?");
	options.add("A) a byte, B) a record, C) an address, D) all of them");
	answers.add("C) an address");
	questions.add("When did IBM introduce the 20286 based PC/AT?");
	options.add("A) 1982, B) 1984, C) 1985, D) 1989");
	answers.add("B) 1984");
	questions.add("The proper definition of a modern digital computer is");
	options.add("A) an electronic automated machine that can solve problems involving words and numbers, B) a more sophistic and modified electronic pocket calculator, C) any machine that can perform mathematical operations, D) a machine that works on binary code");
	answers.add("D) a machine that works on binary code");
	questions.add("Where was India's first computer installed and when?");
	options.add("A) Indian Institute of Technology, Delhi, 1977, B) Indian Institute of Science, Bangalore, 1971, C) India Iron & Steel Co. Ltd., 1968, D) Indian Statistical Institute, Calcutta, 1955");
	answers.add("D) Indian Statistical Institute, Calcutta, 1955");
	questions.add("In which year was UK's premier computing event called The which computer started?");
	options.add("A) 1980, B) 1985, C) 1986, D) 1987");
	answers.add("A) 1980");
	questions.add("Reading data is performed in magnetic disk by");
	options.add("A) read/write leads, B) sectors, C) track, D) lower surface");
	answers.add("A) read/write leads");
	questions.add("Mnemonic a memory trick is used in which of the following language?");
	options.add("A) machine language, B) assembly language, C) high level language, D) none of them");
	answers.add("B) assembly language");
	questions.add("Which of the following is a secondary memory device?");
	options.add("A) keyboard, B) disk, C) ALU, D) all of them");
	answers.add("B) disk");
	questions.add("When was the X window system born?");
	options.add("A) 1984, B) 1989, C) 1988, D) 1990");
	answers.add("A) 1984");
	questions.add("A modern electronic computer is a machine that is meant for");
	options.add("A) doing quick mathematical calculations, B) input, storage, manipulation and outputting of data, C) electronic data processing, D) performing repetitive tasks accurately");
	answers.add("B) input, storage, manipulation and outputting of data");
	questions.add("Which of the following are the two main components of the CPU?");
	options.add("A) Control units and registers, B) Registers and main memory, C) Control unit and ALU, D) ALU and bus");
	answers.add("C) Control unit and ALU");
	questions.add("Access time is");
	options.add("A) seek time + latency time, B) seek time, C) seek time - latency time, D) latency time");
	answers.add("A) seek time + latency time");
	questions.add("The translator program used in assembly language is called");
	options.add("A) complier, B) interpreter, C) assembler, D) translator");
	answers.add("C) assembler");
	questions.add("The difference between memory and storage is that memory is _______ and storage is ______");
	options.add("A) temporary, permanent, B) permanent, temporary, C) slow, fast, D) all of them");
	answers.add("A) temporary, permanent");
	questions.add("Today's computer giant IBM was earlier known by different name which was changes in 1924. What was that name?");
	options.add("A) Tabulator Machine Co., B) Computer Tabulating Recording Co., C) The Tabulator Ltd., D) International Computer Ltd.");
	answers.add("A) Tabulator Machine Co.");
	questions.add("Seek time is");
	options.add("A) time to position the head over proper track, B) time to position the head over proper sector, C) time to position the head over proper cylinder, D) none of them");
	answers.add("A) time to position the head over proper track");
        questions.add("What is the name of the new color laptop computer which is powered by a 386 processor at 33 MHz and is built by Epson?");
	options.add("A) AX3/33, B) NEC-20, C) Magnum 2000, D) HCL-3000");
	answers.add("A) AX3/33");
	questions.add("In the third Generation of computers");
	options.add("A) distributed data processing first became popular, B) an operating system was first developed, C) high-level procedural languages were first used, D) online real time systems first become popular");
	answers.add("D) online real time systems first become popular");
	questions.add("To locate a data item for storage is");
	options.add("A) field, B) feed, C) database, D) fetch");
	answers.add("D) fetch");
	questions.add("The central processing unit (CPU) consists of");
	options.add("A) input, output and processing, B) control unit, primary storage and secondary storage, C) control unit, arithmetic-logic unit and primary storage, D) control unit, processing and primary storage");
	answers.add("C) control unit, arithmetic-logic unit and primary storage");
	questions.add("A factor which would strongly influence a business person to adopt a computer is its");
	options.add("A) accuracy, B) reliability, C) speed, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is used only for data entry and storage and never for processing?");
	options.add("A) mouse, B) dumb terminal, C) micro computer, D) dedicated data entry system");
	answers.add("B) dumb terminal");
	questions.add("What is the responsibility of the logical unit in the CPU of a computer?");
	options.add("A) to produce result, B) to compare numbers, C) to control flow of information, D) to do math's works");
	answers.add("B) to compare numbers");
	questions.add("What does the disk drive of a computer do?");
	options.add("A) rotate the disk, B) read the disk, C) load a program from the disk into the memory, D) both b and c");
	answers.add("D) both b and c");
	questions.add("A characteristic of card systems is");
	options.add("A) slowness in processing data, B) using cards as records of transactions, C) needing a larger DP staff, D) all of them");
	answers.add("D) all of them");
	questions.add("Programs designed to perform specific tasks is known as");
	options.add("A) system software, B) application software, C) utility software, D) operating system");
	answers.add("B) application software");
	questions.add("EBCDIC can code up to how many different characters?");
	options.add("A) 256, B) 16, C) 32, D) 64");
	answers.add("A) 256");
	questions.add("The magnetic storage chip used to provide non-volatile direct access storage of data and that have no moving parts are known as");
	options.add("A) magnetic core memory, B) magnetic tape memory, C) magnetic disk memory, D) magnetic bubble memory");
	answers.add("D) magnetic bubble memory");
	questions.add("To produce high quality graphics (hardcopy) in color, you would want to use a/an");
	options.add("A) RGB monitor, B) plotter, C) ink-jet printer, D) laser printer");
	answers.add("B) plotter");
	questions.add("The secondary storage devices can only store data but they cannot perform");
	options.add("A) arithmetic operation, B) logic operation, C) fetch operation, D) either of the above");
	answers.add("D) either of the above");
	questions.add("The language that the computer can understand and execute is called");
	options.add("A) machine language, B) application software, C) system program, D) all of them");
	answers.add("A) machine language");
	questions.add("An IBM system/38 represents the computer class of");
	options.add("A) small scale computer, B) medium scale computer, C) large scale computer, D) super computer");
	answers.add("A) small scale computer");
	questions.add("Perforated paper used as input of output media is known as");
	options.add("A) paper tapes, B) magnetic tape, C) punched papers tape, D) card punch");
	answers.add("A) paper tapes");
	questions.add("Which is considered a direct entry input device?");
	options.add("A) optical scanner, B) mouse and digitizer, C) light pen, D) all of them");
	answers.add("D) all of them");
	questions.add("CAD stands for");
	options.add("A) computer aided design, B) computer algorithm for design, C) computer application in design, D) all of them");
	answers.add("A) computer aided design");
	questions.add("Which of the following printers are you sure will not to use if your objective is to print on multi carbon forms?");
	options.add("A) daisy wheel, B) dot matrix, C) laser, D) thimble");
	answers.add("C) laser");
	questions.add("Which of the printers used in conjunction with computers uses dry ink power?");
	options.add("A) daisy wheel printer, B) line printer, C) laser printer, D) thermal printer");
	answers.add("C) laser printer");
	questions.add("Which of the following is form of semi conductor memory in which it is possible to change the contents of selected memory locations by applying suitable electrical signals?");
	options.add("A) CAM, B) ROM, C) EPROM, D) Abacus");
	answers.add("C) EPROM");
	questions.add("An application suitable for sequential processing is");
	options.add("A) processing of grades, B) payroll processing, C) both a and b, D) all of them");
	answers.add("C) both a and b");
	questions.add("The first firm to mass-market a microcomputer as a personal computer was");
	options.add("A) IBM, B) Sperry Univac, C) Data General Corporation, D) Radio Shack");
	answers.add("C) Data General Corporation");
	questions.add("Time during which a job is processed by the computer is");
	options.add("A) delay times, B) real time, C) execution time, D) down time");
	answers.add("C) execution time");
	questions.add("Which is used for manufacturing chips?");
	options.add("A) bus, B) control unit, C) semiconductors, D) both a and b");
	answers.add("C) semiconductors");
	questions.add("RATS stand for");
	options.add("A) Regression Analysis Time Series, B) Regression Analysis Time Sharing, C) Real Analysis Series, D) all of them");
	answers.add("A) Regression Analysis Time Series");
	questions.add("Which of the following printing devices an output composed of a series of data?");
	options.add("A) wire matrix printer, B) band printer, C) Wang image printer, D) both a and c");
	answers.add("D) both a and c");
	questions.add("Which of the following produces the best quality graphics reproduction?");
	options.add("A) laser printer, B) ink jet printer, C) plotter, D) dot matrix printer");
	answers.add("C) plotter");
	questions.add("A disk storage medium in the form of an assembly containing a single rigid magnetic disk permanently is");
	options.add("A) fixed disk, B) disk cartridge, C) card punch, D) card reader");
	answers.add("B) disk cartridge");
	questions.add("The word processing task associated with changing the appearance of a document is");
	options.add("A) editing, B) writing, C) formatting, D) all of them");
	answers.add("C) formatting");
	questions.add("A digital computer did not score over, an analog computer in terms of");
	options.add("A) speed, B) accuracy, C) cost, D) memory");
	answers.add("B) accuracy");
	questions.add("A computer which CPU speed around 100 million instruction per second and with the word length of around 64 bits is known as");
	options.add("A) super computer, B) mini computer, C) micro computer, D) macro computer");
	answers.add("A) super computer");
	questions.add("The computer code for the interchange of information between terminals is");
	options.add("A) ASCII, B) BCD, C) EBCDIC, D) all of them");
	answers.add("A) ASCII");
	questions.add("In which year was chip used inside the computer for the first time?");
	options.add("A) 1964, B) 1975, C) 1999, D) 1944");
	answers.add("B) 1975");
	questions.add("The personal computer industry was started by");
	options.add("A) IBM, B) Apple, C) Compa, D) HCL");
	answers.add("A) IBM");
	questions.add("Which of the following memories allows simultaneous read and write operations?");
	options.add("A) ROM, B) RAM, C) EPROM, D) none of them");
	answers.add("B) RAM");
	questions.add("A memory that is capable of determining whether a given datum is contained in one of its address is");
	options.add("A) ROM, B) PROM, C) CAM, D) RAM");
	answers.add("C) CAM");
	questions.add("The special files of DOS are");
	options.add("A) COM, B) EXE, C) BATCH, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is used as a primary storage device?");
	options.add("A) magnetic drum, B) prom, C) floppy, D) all of them");
	answers.add("B) prom");
	questions.add("In 1830, Charles Babbage designed a machine called analytical engine, which he showed at the parts exhibition. In which year was it exhibited?");
	options.add("A) 1820, B) 1860, C) 1855, D) 1870");
	answers.add("C) 1855");
	questions.add("An approach that permits the computer to work on several programs instead of one is");
	options.add("A) on-line thesaurus, B) multiprogramming, C) over lapped processing, D) outline processor");
	answers.add("C) over lapped processing");
	questions.add("A byte consists of");
	options.add("A) one bit, B) four bits, C) eight bits, D) sixteen bits");
	answers.add("C) eight bits");
	questions.add("What was the name of the first commercially available microprocessor chip?");
	options.add("A) Intel 308, B) Intel 33, C) Intel 4004, D) Motorola 539");
	answers.add("C) Intel 4004");
	questions.add("In the IBM PC-At, what to the words AT stand for");
	options.add("A) additional terminals, B) advance technology, C) applied technology, D) advanced terminology");
	answers.add("B) advance technology");
	questions.add("Which of the following memories has the shortest access time?");
	options.add("A) cache memory, B) magnetic bubble memory, C) magnetic core memory, D) RAM");
	answers.add("A) cache memory");
	questions.add("A method of implementing a memory management system is");
	options.add("A) buddy system, B) bridge ware, C) broadband coaxial system, D) all of them");
	answers.add("A) buddy system");
	questions.add("Which of the following memories needs refreshing?");
	options.add("A) SRAM, B) DRAM, C) ROM, D) all of them");
	answers.add("B) DRAM");
	questions.add("Which was the world's first minicomputer and when was it introduced?");
	options.add("A) PDP-I, 1958, B) IBM System/36, 1960, C) PDP-II, 1961, D) VAX 11/780, 1962");
	answers.add("A) PDP-I, 1958");
	questions.add("A directly accessible appointment calendar is feature of a ______ resident package");
	options.add("A) CPU, B) memory, C) buffer, D) ALU");
	answers.add("B) memory");
	questions.add("A hybrid computer");
	options.add("A) resembles digital computer, B) resembles analog computer, C) resembles both a digital and analog computer, D) none of them");
	answers.add("C) resembles both a digital and analog computer");
	questions.add("When were the first minicomputer built?");
	options.add("A) 1965, B) 1962, C) 1971, D) 1966");
	answers.add("A) 1965");
	questions.add("Magnetic tape can serve as");
	options.add("A) secondary storage media, B) output media, C) input media, D) all of them");
	answers.add("D) all of them");
	questions.add("A 32 bit microprocessor has the word length equal to");
	options.add("A) 2 byte, B) 32 byte, C) 4 byte, D) 8 byte");
	answers.add("C) 4 byte");
	questions.add("A plastic card similar to a credit card but having some memory and microprocessor embedded within it is");
	options.add("A) punched paper tape, B) chip card, C) card punch, D) magnetic tape");
	answers.add("A) punched paper tape");
	questions.add("IBM 7000 digital computer");
	options.add("A) belongs to second generation, B) uses VLSI, C) employs semiconductor memory, D) has modular constructions");
	answers.add("C) employs semiconductor memory");
	questions.add("Where was India's first computer installed and when?");
	options.add("A) Indian Institute of Technology, Delhi, 1977, B) Indian Institute of Science, Bangalore, 1971, C) India Iron & Steel Co. Ltd., 1968, D) Indian Statistical Institute, Calcutta, 1955");
	answers.add("D) Indian Statistical Institute, Calcutta, 1955");
	questions.add("The term gigabyte refers to");
	options.add("A) 1024 bytes, B) 1024 kilobytes, C) 1024 megabytes, D) 1024 gigabytes");
	answers.add("C) 1024 megabytes");
	questions.add("The silicon chips used for data processing are called");
	options.add("A) RAM chips, B) ROM chips, C) micro processors, D) PROM chips");
	answers.add("D) PROM chips");
	questions.add("The first digital computer built with IC chips was known as");
	options.add("A) IBM 7090, B) Apple - 1, C) IBM System/360, D) VAX - 10");
	answers.add("C) IBM System/360");
	questions.add("If in a computer, 16 bits are used to specify address in a RAM, the number of addresses will be");
	options.add("A) 216, B) 65,536, C) 64K, D) none of them");
	answers.add("B) 65,536");
	questions.add("An error in computer data is called");
	options.add("A) chip, B) bug, C) CPU, D) storage");
	answers.add("B) bug");
	questions.add("A device that operates under control of another device is called");
	options.add("A) stem, B) slave, C) simulator, D) emulator");
	answers.add("B) slave");
	questions.add("The proper definition of a modern digital computer is");
	options.add("A) an electronic automated machine that can solve problems involving words and numbers, B) a more sophistic and modified electronic pocket calculator, C) any machine that can perform mathematical operations, D) a machine that works on binary code");
	answers.add("D) a machine that works on binary code");
	questions.add("Which of the following are the two main components of the CPU?");
	options.add("A) Control units and registers, B) Registers and main memory, C) Control unit and ALU, D) ALU and bus");
	answers.add("C) Control unit and ALU");
	questions.add("Which of the following processors use RISC technology?");
	options.add("A) 486dx, B) Power PC, C) 486sx, D) 6340");
	answers.add("B) Power PC");
	questions.add("The metal disks, which are permanently housed in, sealed and contamination free containers are called");
	options.add("A) hard disks, B) floppy disk, C) Winchester disk, D) flexible disk");
	answers.add("C) Winchester disk");
	questions.add("In which language is source program written?");
	options.add("A) English, B) Symbolic, C) High level, D) Temporary");
	answers.add("C) High level");
	questions.add("The two major types of computer chips are");
	options.add("A) external memory chip, B) primary memory chip, C) microprocessor chip, D) both b and c");
	answers.add("D) both b and c");
	questions.add("A set of information that defines the status of resources allocated to a process is");
	options.add("A) process control, B) ALU, C) register unit, D) process description");
	answers.add("D) process description");
	questions.add("Actual data processing operations are performed in the arithmetic logic section, but not in the Storage section of a processor unit");
	options.add("A) primary, B) accumulator, C) buffer, D) secondary");
	answers.add("A) primary");
	questions.add("User programmable terminals that combine VDT hardware with built-in microprocessor is");
	options.add("A) kips, B) PC, C) mainframe, D) intelligent terminals");
	answers.add("D) intelligent terminals");
	questions.add("A modern electronic computer is a machine that is meant for");
	options.add("A) doing quick mathematical calculations, B) input, storage, manipulation and outputting of data, C) electronic data processing, D) performing repetitive tasks accurately");
	answers.add("B) input, storage, manipulation and outputting of data");
	questions.add("Which of the following is true?");
	options.add("A) fields are composed of bytes, B) records are composed of fields, C) fields are composed of characters, D) all of them");
	answers.add("D) all of them");
	questions.add("A/an _______ device is any information, which is sent to the CPU");
	options.add("A) input, B) output, C) CPU, D) memory");
	answers.add("A) input");
	questions.add("A computer consists of");
	options.add("A) a central processing unit, B) a memory, C) input and output unit, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following terms is the most closely related to main memory?");
	options.add("A) not volatile, B) permanent, C) control unit, D) Temporary");
	answers.add("D) Temporary");
	questions.add("As compared to the secondary memory, the primary memory of a computer is");
	options.add("A) large, B) cheap, C) fast, D) slow");
	answers.add("C) fast");
	questions.add("Any method for controlling access to or use of memory is known");
	options.add("A) memory map, B) memory protection, C) memory management, D) memory instruction");
	answers.add("B) memory protection");
	questions.add("The use of spooler programs and/or ________ hardware allows personal computer operates to do the processing work at the same time a printing operation is in progress");
	options.add("A) registered mails, B) memory, C) CPU, D) buffer");
	answers.add("D) buffer");
	questions.add("An integrated circuit is");
	options.add("A) a complicated circuit, B) an integrating device, C) much costlier than a single transistor, D) fabricated on a tiny silicon chip");
	answers.add("D) fabricated on a tiny silicon chip");
	questions.add("Which of the following file organization is most efficient for a file with a high degree of file activity?");
	options.add("A) Sequential, B) ISAM, C) VSAM, D) B-Tree Index");
	answers.add("A) Sequential");
	questions.add("Current SIMMs have either _____ or _____ connectors (pins)");
	options.add("A) 9 or 32, B) 30 or 70, C) 28 or 72, D) 30 or 72");
	answers.add("D) 30 or 72");
	questions.add("An application program that helps the user to change any number and immediately see the result of that change is");
	options.add("A) desktop publishing program, B) database, C) spreadsheet, D) all of them");
	answers.add("C) spreadsheet");
	questions.add("Which of the following is used for manufacturing chips?");
	options.add("A) control bus, B) control unit, C) parity unit, D) semiconductor");
	answers.add("D) semiconductor");
	questions.add("Which of the following is a way to access secondary memory?");
	options.add("A) random access memory, B) action method, C) transfer method, D) density method");
	answers.add("A) random access memory");
	questions.add("A type of core store that has a lower access time than the devices used for working store in the same processor is known as");
	options.add("A) core memory, B) buffer, C) fast core, D) address register");
	answers.add("D) address register");
	questions.add("Which most popular input device is used today for interactive processing and for the one line entry of data for batch processing?");
	options.add("A) mouse, B) magnetic disk, C) visual display terminal, D) card punch");
	answers.add("A) mouse");
	questions.add("Most important advantage of an IC is its");
	options.add("A) easy replacement in case of circuit failure, B) extremely high reliability, C) reduced cost, D) lower power consumption");
	answers.add("B) extremely high reliability");
	questions.add("The two basic types of record-access methods are");
	options.add("A) sequential and random, B) sequential and indexed, C) direct and immediate, D) on-line and real time");
	answers.add("A) sequential and random");
	questions.add("The storage subsystem in a microcomputer consists mainly of ______ or ______ media with varying capacities");
	options.add("A) memory or video, B) magnetic or optical, C) optical or memory, D) video or magnetic");
	answers.add("B) magnetic or optical");
	questions.add("The instructions for starting the computer are house on");
	options.add("A) random access memory, B) CD-ROM, C) read only memory chip, D) all of them");
	answers.add("C) read only memory chip");
	questions.add("Which of the following is required when more than one person uses a central computer at the same time?");
	options.add("A) terminal, B) light pen, C) digitizer, D) mouse");
	answers.add("A) terminal");
	questions.add("Which was the most popular first generation computer?");
	options.add("A) IBM 1650, B) IBM 360, C) IBM 1130, D) IBM 2700");
	answers.add("A) IBM 1650");
	questions.add("Which of the following is an acronym for electronic delay storage automatic calculator?");
	options.add("A) UNIVAC, B) EDSAC, C) EDVAC, D) Abacus");
	answers.add("B) EDSAC");
	questions.add("In a punched card system, data is processed by a");
	options.add("A) Keypunch machine, sorter and posting machine, B) accounting machine, posting machine and billing machine, C) sorter, posting machine, and billing machine, D) accounting machine, keypunch machine and sorter");
	answers.add("D) accounting machine, keypunch machine and sorter");
	questions.add("The advantage of COM are its _______ and ______");
	options.add("A) compact size; speed readability, B) compact size; speed, C) readability; speed, D) low cost; readability");
	answers.add("B) compact size; speed");
	questions.add("Which of the following is not an input device?");
	options.add("A) OCR, B) optical scanners, C) voice recognition device, D) COM (Computer Output to Microfilm)");
	answers.add("D) COM (Computer Output to Microfilm)");
	questions.add("The ALU of a computer normally contains a number of high speed storage element called");
	options.add("A) semiconductor memory, B) registers, C) hark disks, D) magnetic disk");
	answers.add("B) registers");
	questions.add("The first machine to successfully perform a long series of arithmetic and logical operations was");
	options.add("A) ENIAC, B) Mark I, C) Analytic engine, D) UNIVAC-I");
	answers.add("B) Mark I");
	questions.add("The number of characters that can be stored in given physical space is");
	options.add("A) word length, B) byte, C) data density, D) field");
	answers.add("C) data density");
	questions.add("Another word for a daisy wheel printer");
	options.add("A) petal printer, B) golf ball printer, C) laser printer, D) line printer");
	answers.add("B) golf ball printer");
	questions.add("Which term is used to describe RAM?");
	options.add("A) Dynamic RAM (DRAM), B) Static RAM (SRAM), C) Video RAM (VRAM), D) all of them");
	answers.add("D) all of them");
	questions.add("What is required when more than one person uses a central computer at the same time?");
	options.add("A) mouse, B) light pen, C) digitizer, D) terminal");
	answers.add("D) terminal");
	questions.add("Which type of computer uses the 8-bit code called EBCDIC?");
	options.add("A) minicomputers, B) microcomputers, C) mainframe computers, D) super computer");
	answers.add("C) mainframe computers");
	questions.add("The difference between memory and storage is that memory is _______ and storage is ______");
	options.add("A) temporary, permanent, B) permanent, temporary, C) slow, fast, D) all of them");
	answers.add("A) temporary, permanent");
	questions.add("Which American computer company is called Big Blue?");
	options.add("A) Microsoft, B) Compa Corp, C) IBM, D) Tandy Svenson");
	answers.add("C) IBM");
	questions.add("Digital computer is a computer");
	options.add("A) that works with discrete quantities, B) that works with analog quantities, C) both a and b, D) none of them");
	answers.add("A) that works with discrete quantities");
	questions.add("The storage capacity of a disk system depends on the bits or inch of track and the tracks per inch of");
	options.add("A) cylinder, B) hum, C) cluster, D) surface");
	answers.add("D) surface");
	questions.add("A term used to describe interconnected computer configuration is");
	options.add("A) multiprogramming, B) modulation, C) multiprocessing, D) micro program sequence");
	answers.add("A) multiprogramming");
	questions.add("Which of the following are (is) considered to be video component?");
	options.add("A) resolution, B) color depth, C) refresh rate, D) all of them");
	answers.add("D) all of them");
	questions.add("A hard copy would be prepared on a");
	options.add("A) line printer, B) dot matrix printer, C) typewriter terminal, D) all of them");
	answers.add("D) all of them");
	questions.add("Where as a computer mouse moves over the table surface, the trackball is");
	options.add("A) stationary, B) difficult to move, C) dragged, D) moved in small stems");
	answers.add("A) stationary");
	questions.add("A floppy disk contains");
	options.add("A) circular tracks only, B) sectors only, C) both circular tracks and sectors, D) all of them");
	answers.add("C) both circular tracks and sectors");
	questions.add("When did IBM introduce the 20286 based PC/AT?");
	options.add("A) 1982, B) 1984, C) 1985, D) 1989");
	answers.add("B) 1984");
	questions.add("The subdivision of fields");
	options.add("A) always done to give the programmer greater flexibility, B) dependent on programming language used, C) never accomplished on fields containing numeric data, D) all of them");
	answers.add("B) dependent on programming language used");
	questions.add("A data transmission medium made of tiny threads of glass or plastic that can transmit huge amount of information at the speed of light is");
	options.add("A) fiber optic cable, B) copper cable, C) twisted wire cable, D) none of them");
	answers.add("A) fiber optic cable");
	questions.add("The disk drive component used to position read/write heads over a specific track is known as");
	options.add("A) acoustic couples, B) access arm, C) cluster, D) all of them");
	answers.add("B) access arm");
	questions.add("An input/output device at which data enters or leaves a computer system is");
	options.add("A) keyboard, B) terminal, C) printer, D) plotter");
	answers.add("B) terminal");
	questions.add("On a PC, how much memory is available to application software?");
	options.add("A) 1024 KB, B) 760 KB, C) 640 KB, D) 560 KB");
	answers.add("C) 640 KB");
	questions.add("A typical personal computer used for business purposes would have ______ of ROM.");
	options.add("A) 4 KB, B) 16 K, C) 64 K, D) 256 K");
	answers.add("D) 256 K");
	questions.add("Which one of the following input device is user-programmable?");
	options.add("A) dumb terminal, B) smart terminal, C) VDT, D) intelligent terminal");
	answers.add("D) intelligent terminal");
	questions.add("The octal equivalence of 111010 is");
	options.add("A) 81, B) 72, C) 71, D) none of them");
	answers.add("B) 72");
	questions.add("The first electronic general purpose digital computer built by Mauchly and Eckert called ENIA did not work on the stored program principle. How many numbers could it store in its internal memory?");
	options.add("A) 100, B) 20, C) 40, D) 80");
	answers.add("B) 20");
	questions.add("The primary memory of a personal computer consists");
	options.add("A) ROM only, B) RAM only, C) Both ROM and RAM, D) memory module");
	answers.add("C) Both ROM and RAM");
	questions.add("Considering output data to exhibit specific information is");
	options.add("A) calculating, B) recording, C) merging, D) summarizing");
	answers.add("D) summarizing");
	questions.add("A physical connection between the microprocessor memory and other parts of the microcomputer is known as");
	options.add("A) path, B) address bus, C) route, D) all of them");
	answers.add("B) address bus");
	questions.add("Which of the following items are examples of storage devices?");
	options.add("A) floppy/hard disks, B) CD-ROMs, C) tape devices, D) all of them");
	answers.add("D) all of them");
	questions.add("A high quality CD system uses the following for printing drawing and graphs");
	options.add("A) dot matrix printer, B) digital plotter, C) line printer, D) all of them");
	answers.add("B) digital plotter");
	questions.add("Which computer memory is used for strong programs and data currently being processed by the CPU?");
	options.add("A) mass memory, B) internal memory, C) non-volatile memory, D) PROM");
	answers.add("B) internal memory");
	questions.add("The first electronic computer in the world was");
	options.add("A) UNIVAC, B) EDSAC, C) ENIAC, D) all of them");
	answers.add("C) ENIAC");
	questions.add("Process of finding/correcting program errors is");
	options.add("A) bus, B) debugging, C) hacking, D) cracking");
	answers.add("B) debugging");
	questions.add("Microsoft Excel is");
	options.add("A) financial planning package, B) electronic spreadsheet, C) data-base management package, D) graphics package");
	answers.add("B) electronic spreadsheet");
	questions.add("Which chips using special external equipment can reprogram");
	options.add("A) ROM, B) PROM, C) SAM, D) RAM");
	answers.add("B) PROM");
	questions.add("A group of magnetic tapes, videos or terminals usually under the control of one master is");
	options.add("A) cylinder, B) surface, C) track, D) cluster");
	answers.add("D) cluster");
	questions.add("The Width of a processor's data path is measured in bits. Which of the following are common data paths?");
	options.add("A) 8 bits, B) 12 bits, C) 16 bits, D) 32 bits");
	answers.add("A) 8 bits");
	questions.add("Symbolic logic was discovered by");
	options.add("A) George Boole, B) Herman Hollerith, C) Van Neumann, D) Basic Pascal");
	answers.add("A) George Boole");
	questions.add("Computer instructions written with the use of English words instead of binary machine code is called");
	options.add("A) mnemonics, B) symbolic code, C) gray codes, D) opcode");
	answers.add("B) symbolic code");
	questions.add("The most commonly used standard data code to represent alphabetical, numerical and punctuation characters used in electronic data processing system is called");
	options.add("A) ASCII, B) EBCDIC, C) BCD, D) all of them");
	answers.add("A) ASCII");
	questions.add("Diagnostic routine is a");
	options.add("A) programs used to print error messages, B) indicates system problems and improper program instructions, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("All the keys on the IBM PC keyboard repeat as long as one holds them down. These keys are known as");
	options.add("A) typematic keys, B) functional keys, C) automatic keys, D) alphabetic keys");
	answers.add("A) typematic keys");
	questions.add("A storage device where the access time is depended upon the location of the data is");
	options.add("A) random access, B) serial access, C) transaction access, D) sequential access");
	answers.add("B) serial access");
	questions.add("Number crunchier is the informal name for");
	options.add("A) mini computer, B) super computer, C) microcomputer, D) mainframe computer");
	answers.add("B) super computer");
	questions.add("Which is the type of memory for information that does not change on your computer?");
	options.add("A) RAM, B) ROM, C) ERAM, D) RW/RAM");
	answers.add("B) ROM");
	questions.add("What was the nick name of the computer used by the Americans in 1952 for their H-bomb project?");
	options.add("A) ENIAC, B) EDSAC, C) MANIAC, D) UNIVAC");
	answers.add("C) MANIAC");
	questions.add("Computer operators");
	options.add("A) writes computer programs for specific problems, B) operate the device which input and output data from the computer, C) normally require a college degree in computer science, D) all of them");
	answers.add("B) operate the device which input and output data from the computer");
	questions.add("Which was the computer conceived by Babbage?");
	options.add("A) analytical engine, B) arithmetic machine, C) Donald Kunth, D) all of them");
	answers.add("A) analytical engine");
	questions.add("The term DBMS is referred to");
	options.add("A) Data Base Management System, B) the software used for the management, maintenance and retrieval of data stored in a data base, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Distributed data processing configuration where all activities passes through a centrally located computer is");
	options.add("A) ring network, B) spider network, C) hierarchical network, D) data control network");
	answers.add("B) spider network");
	questions.add("Which number system is commonly used a shortcut notation for groups of four binary digits?");
	options.add("A) binary, B) decimal, C) octal, D) hexadecimal");
	answers.add("D) hexadecimal");
	questions.add("A technique used by codes to convert an analog signal into a digital bit stream is known as");
	options.add("A) pulse code modulation, B) pulse stretcher, C) query processing, D) queue management");
	answers.add("A) pulse code modulation");
	questions.add("What type of memory is not directly addressable by the CPU and requires special software called EMS (expanded memory specification)?");
	options.add("A) extended, B) expanded, C) base, D) conventional");
	answers.add("B) expanded");
	questions.add("The word length of a computer is measured in");
	options.add("A) bytes, B) millimeters, C) meters, D) bits");
	answers.add("D) bits");
	questions.add("A computer programmer");
	options.add("A) dies all the thinking for a computer, B) can enter input data quickly, C) can operate all types of computer equipment, D) can draw only flowchart");
	answers.add("A) dies all the thinking for a computer");
	questions.add("Offline device is");
	options.add("A) a device which is not connected to CPU, B) a device which is connected to CPU, C) a direct access storage device, D) an I/O device");
	answers.add("A) a device which is not connected to CPU");
	questions.add("The speed at which data is transferred from the main memory to another medium on which data are recorded is referred as");
	options.add("A) data transfer rate, B) byte, C) buds, D) none of them");
	answers.add("A) data transfer rate");
	questions.add("Communications device, combines transmissions from several devices into on line is?");
	options.add("A) concentrator, B) modifier, C) multiplexer, D) full-duplex line");
	answers.add("C) multiplexer");
	questions.add("Interface electronic circuit is used to interconnect I/O devices to a computer's CPU or");
	options.add("A) ALU, B) memory, C) buffer, D) register");
	answers.add("B) memory");
	questions.add("The personnel who deals with the computer and its management put together are called");
	options.add("A) software, B) human ware, C) firmware, D) hardware");
	answers.add("B) human ware");
	questions.add("Multi user systems provided cost savings for small business because they use a single processing unit to link several");
	options.add("A) personal computers, B) workstations, C) dumb terminals, D) mainframes");
	answers.add("C) dumb terminals");
	questions.add("CD-ROM");
	options.add("A) is a semiconductor memory, B) memory register, C) magnetic memory, D) none of them");
	answers.add("D) none of them");
	questions.add("Which of the following registers is loaded with the contents of the memory location pointed by the PC?");
	options.add("A) memory address registers, B) memory data register, C) instruction registers, D) program counter");
	answers.add("C) instruction registers");
	questions.add("The time period during which a computer is malfunctioning or not operating correctly due to machine failures is referred as");
	options.add("A) downtime, B) uptime, C) runtime, D) none of them");
	answers.add("A) downtime");
	questions.add("Data communications involving telegraph lines uses");
	options.add("A) simplex lines, B) wideband channels, C) narrowband channels, D) dialed service");
	answers.add("C) narrowband channels");
	questions.add("A group of magnetic tapes, videos or terminals usually under the control of one master is");
	options.add("A) cylinder, B) surface, C) track, D) cluster");
	answers.add("D) cluster");
	questions.add("One millisecond is");
	options.add("A) 1 second, B) 10th of a second, C) 1000th of a second, D) 10000th of a second");
	answers.add("C) 1000th of a second");
	questions.add("The brain of any computer system is");
	options.add("A) ALU, B) memory, C) CPU, D) control unit");
	answers.add("C) CPU");
	questions.add("Before a disk can be used to store datA. It must be");
	options.add("A) none of them, B) formatted, C) Reformatted, D) addressed");
	answers.add("B) formatted");
	questions.add("What are the three decisions making operations performed by the ALU of a computer?");
	options.add("A) greater than, B) less than, C) equal to, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is not a primary storage device?");
	options.add("A) magnetic tape, B) magnetic disk, C) optical disk, D) none of them");
	answers.add("D) none of them");
	questions.add("Which of the following registers is used to keep track of address of the memory location where the next instruction is located?");
	options.add("A) memory address registers, B) memory data register, C) instruction register, D) program counter");
	answers.add("D) program counter");
	questions.add("EBCDIC is");
	options.add("A) 6-bit coding system, B) 7-bit coding system, C) 8-bit coding system, D) 9-bit coding system");
	answers.add("C) 8-bit coding system");
	questions.add("A semiconductor memory which allows he eraser of the information stared in it so that new information can be stared in it is referred as");
	options.add("A) EPROM, B) ROM, C) RAM, D) none of them");
	answers.add("A) EPROM");
	questions.add("An online backing storage system capable of storing larger quantities of data of");
	options.add("A) CPU, B) memory, C) mass storage, D) secondary storage");
	answers.add("C) mass storage");
	questions.add("Each model of a computer has a unique");
	options.add("A) assembly of a computer, B) machine language, C) high level language, D) all of them");
	answers.add("B) machine language");
	questions.add("What type of device is computer keyboard?");
	options.add("A) memory, B) output, C) storage, D) input");
	answers.add("D) input");
	questions.add("Which part of the computer is used for calculating and comparing?");
	options.add("A) disk unit, B) control unit, C) ALU, D) modem");
	answers.add("C) ALU");
	questions.add("A name or number used to identify a storage location is called");
	options.add("A) a byte, B) a record, C) an address, D) all of them");
	answers.add("C) an address");
	questions.add("Microprocessors can be used to make");
	options.add("A) computer, B) digital systems, C) calculators, D) all of them");
	answers.add("D) all of them");
	questions.add("A data communication facility on which data can be transmitted in two directions is referred as");
	options.add("A) duplex, B) simplex, C) triplex, D) none of them");
	answers.add("A) duplex");
	questions.add("Extended ASCII uses");
	options.add("A) 8 bits for coding, B) 9 bits for coding, C) 10 bits for coding, D) 11 bits for coding");
	answers.add("A) 8 bits for coding");
	questions.add("One of a class of storage device that can access storage locations in any order is");
	options.add("A) DTE, B) DASD, C) DDE, D) none of them");
	answers.add("B) DASD");
	questions.add("Computer professionals working in a computer center are");
	options.add("A) software, B) firmware, C) hardware, D) human ware");
	answers.add("D) human ware");
	questions.add("The original ASCII code used ______ bits of each byte, reserving that last bit for error checking");
	options.add("A) 5, B) 6, C) 7, D) 8");
	answers.add("C) 7");
	questions.add("Can you tell what passes into and out from the computer via its ports?");
	options.add("A) data, B) bytes, C) graphics, D) pictures");
	answers.add("A) data");
	questions.add("Which of the following is a secondary memory device?");
	options.add("A) keyboard, B) disk, C) ALU, D) all of them");
	answers.add("B) disk");
	questions.add("How many address lines are needed to address each memory location in a 2048*4 memory chip?");
	options.add("A) 10, B) 11, C) 8, D) 12");
	answers.add("B) 11");
	questions.add("Electronic Mall/Message System (EMMS) is similar or best suits to");
	options.add("A) postal service, B) telephone service, C) telegraph service, D) none of them");
	answers.add("A) postal service");
	questions.add("A device used for transmission of images scanned at a transmitting point and duplicated at a receiving point is");
	options.add("A) Facsimile (FAX), B) telephone, C) photocopier, D) none of them");
	answers.add("A) Facsimile (FAX)");
	questions.add("Which is an item o storage medium in the form of circular plate?");
	options.add("A) disk, B) CPU, C) printer, D) ALU");
	answers.add("A) disk");
	questions.add("Which of the items below are considered removable storage media?");
	options.add("A) removable hard disk cartridges, B) (magneto-optical) disk, C) flexible disks cartridges, D) all of them");
	answers.add("D) all of them");
	questions.add("Which company is the biggest player in the microprocessor industry?");
	options.add("A) Motorola, B) IBM, C) Intel, D) AMD");
	answers.add("C) Intel");
	questions.add("Properly arranged data is called");
	options.add("A) field, B) words, C) information, D) file");
	answers.add("C) information");
	questions.add("UNIVAC is");
	options.add("A) Universal Automatic Computer, B) Universal Array Computer, C) Unique Automatic Computer, D) Unvalued Automatic Computer");
	answers.add("A) Universal Automatic Computer");
	questions.add("EBCDIC =");
	options.add("A) Extended Binary Coded Decimal Interchange Code, B) Extended Bit Code Decimal Interchange Code, C) Extended Bit Case Decimal Interchange Code, D) Extended Binary Case Decimal Interchange Code");
	answers.add("A) Extended Binary Coded Decimal Interchange Code");
	questions.add("Which operation is not performed by computer?");
	options.add("A) inputting, B) processing, C) controlling, D) understanding");
	answers.add("D) understanding");
	questions.add("Floppy disks are available in");
	options.add("A) single side single density, B) single side double density, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("A compiler is a translating program which");
	options.add("A) translates instruction of a high level language into machine language, B) translates entire source program into machine language program, C) it is not involved in program's execution, D) all of them");
	answers.add("D) all of them");
	questions.add("Offline device is");
	options.add("A) a device which is not connected to CPU, B) a device which is connected to CPU, C) a direct access storage device, D) an I/O device");
	answers.add("A) a device which is not connected to CPU");
	questions.add("Who is credited with the idea of using punch cards to control patterns of a weaving machine?");
	options.add("A) Pascal, B) Hollerith, C) Jacquard, D) Babbage");
	answers.add("C) Jacquard");
    }



    public static void main(String[] args) {
        new Computer_Quiz(name).setVisible(true); 
    }

}
