package secondListFrames;

import frame.Quiz;

public class Computer2_Quiz extends Quiz {
   
    public Computer2_Quiz(String name) {
        super(name);
        loadQuestions();
        System.out.println(questions.size());
        setupQuiz();
    }

    private void setupQuiz() {
        shuffleIndices();
        selectTotalQuestions();
        setCurrentQuestion();
        setQuestionTextAndOptions();
    }


    @Override
    public void setQuestionTextAndOptions() {
        qno.setText("Question #: " + currentQno);
        question.setText(questions.get(currentQuestionIndex));
        opt1.setText(options.get(currentQuestionIndex).split(", ")[0]);
        opt2.setText(options.get(currentQuestionIndex).split(", ")[1]);
        opt3.setText(options.get(currentQuestionIndex).split(", ")[2]);
        opt4.setText(options.get(currentQuestionIndex).split(", ")[3]);
    }

    // 400 questions
    @Override
    public final void loadQuestions() {
     
        questions.add("A modern electronic computer is a machine that is meant for");
	options.add("A) doing quick mathematical calculations, B) input, storage, manipulation and outputting of data, C) electronic data processing, D) performing repetitive tasks accurately");
	answers.add("B) input, storage, manipulation and outputting of data");
	questions.add("A characteristic of card systems is");
	options.add("A) slowness in processing data, B) using cards as records of transactions, C) needing a larger DP staff, D) all of them");
	answers.add("D) all of them");
	questions.add("CD-ROM stands for");
	options.add("A) Compactable Read Only Memory, B) Compact Data Read Only Memory, C) Compactable Disk Read Only Memory, D) Compact Disk Read Only Memory");
	answers.add("D) Compact Disk Read Only Memory");
	questions.add("Fifth generation computer is also known as");
	options.add("A) knowledge information processing system, B) very large scale integration (VLSI), C) both a and b, D) none of them");
	answers.add("A) knowledge information processing system");
	questions.add("Floppy disks typically in diameter");
	options.add("A) 3, B) 5.25, C) 8, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is machine independence program?");
	options.add("A) high level language, B) low level language, C) assembly language, D) machine language");
	answers.add("A) high level language");
	questions.add("The first computer introduced in Nepal was");
	options.add("A) IBM 1400, B) IBM 1401, C) IBM 1412, D) IBM 1402");
	answers.add("B) IBM 1401");
	questions.add("CPU is combination of");
	options.add("A) control and storage, B) control and output unit, C) arithmetic logic and input unit, D) arithmetic logic and control unit");
	answers.add("D) arithmetic logic and control unit");
	questions.add("Hard disk is coated in both side above");
	options.add("A) magnetic metallic oxide, B) optical metallic oxide, C) carbon layer, D) all of them");
	answers.add("A) magnetic metallic oxide");
	questions.add("Which statement is valid about interpreter?");
	options.add("A) it translates one instruction at a time, B) object code is saved for future use, C) repeated interpretation is not necessary, D) all of them");
	answers.add("A) it translates one instruction at a time");
	questions.add("Which of the following registers is loaded with the contents of the memory location pointed by the PC?");
	options.add("A) memory address registers, B) memory data registers, C) instruction register, D) program counter");
	answers.add("C) instruction register");
	questions.add("Which of the following is first generation of computer?");
	options.add("A) EDSAC, B) IBM-1401, C) CDC-1604, D) ICL-2900");
	answers.add("A) EDSAC");
	questions.add("The brain of any computer system is");
	options.add("A) control unit, B) arithmetic logic unit, C) central processing unit, D) storage unit");
	answers.add("C) central processing unit");
	questions.add("Binary circuit elements have");
	options.add("A) one stable state, B) two stable state, C) three stable state, D) none of them");
	answers.add("B) two stable state");
	questions.add("Which is the limitation of high level language?");
	options.add("A) lower efficiency, B) machine dependence, C) machine level coding, D) none of them");
	answers.add("A) lower efficiency");
	questions.add("Which of the following registers is used to keep track of address of the memory location where the next instruction is located?");
	options.add("A) memory address registers, B) memory data register, C) instruction register, D) program counter");
	answers.add("D) program counter");
	questions.add("Most of the inexpensive personal computer does not have any disk or diskette drive. What is the name of such computers/");
	options.add("A) home computers, B) diskless computers, C) dedicated computers, D) general purpose computers");
	answers.add("A) home computers");
	questions.add("IBM 1401 is");
	options.add("A) First Generation computer, B) Second Generation computer, C) Third Generation computer, D) Fourth Generation computer");
	answers.add("B) Second Generation computer");
	questions.add("Pick the one that is used for logical operations or comparisons such as less than equal to or greater than");
	options.add("A) arithmetic and logic unit, B) control unit, C) both a and b, D) none of them");
	answers.add("A) arithmetic and logic unit");
	questions.add("Which statement is valid?");
	options.add("A) 1 KB = 1024 bytes, B) 1 MB = 2048 bytes, C) 1 MB = 1000 kilobytes, D) 1 KB = 1000 bytes");
	answers.add("A) 1 KB = 1024 bytes");
	questions.add("High level language is also called");
	options.add("A) problem oriented language, B) business oriented language, C) mathematically oriented language, D) all of them");
	answers.add("D) all of them");
	questions.add("Chief component of first generation computer was");
	options.add("A) transistors, B) vacuum tubes and valves, C) integrated circuits, D) none of them");
	answers.add("B) vacuum tubes and valves");
	questions.add("WAN =");
	options.add("A) Wap Area Network, B) Wide Area Network, C) Wide Array Net, D) Wireless Area Network");
	answers.add("B) Wide Area Network");
	questions.add("Analog Computer working on the supply of");
	options.add("A) continues electrical pulses, B) electrical pulses but not continues, C) magnetic strength, D) none of them");
	answers.add("A) continues electrical pulses");
	questions.add("Which statement is valid about computer program?");
	options.add("A) it is understood by a computer, B) it is understood by programmer, C) it is understood user, D) both of above");
	answers.add("D) both of above");
	questions.add("A computer programmer");
	options.add("A) does all the thinking for a computer, B) can enter input data quickly, C) can operate all types of computer equipment, D) can draw only flowchart");
	answers.add("A) does all the thinking for a computer");
	questions.add("Microprocessors can be used to make");
	options.add("A) computers, B) digital systems, C) calculators, D) all of them");
	answers.add("D) all of them");
	questions.add("MICF =");
	options.add("A) Magnetic Ink Character Reader, B) Magnetic Ink Code Reader, C) Magnetic Ink Cases Reader, D) none of them");
	answers.add("A) Magnetic Ink Character Reader");
	questions.add("Digital devices are");
	options.add("A) digital clock, B) automobile speed meter, C) clock with a dial and two hands, D) all of them");
	answers.add("A) digital clock");
	questions.add("Software in computer");
	options.add("A) enhances the capabilities of hardware machine, B) increase the speed of central processing unit, C) both a and b, D) none of them");
	answers.add("A) enhances the capabilities of hardware machine");
	questions.add("CD-ROM is a");
	options.add("A) semiconductor memory, B) memory register, C) magnetic memory, D) none of them");
	answers.add("D) none of them");
	questions.add("FORTRAN =");
	options.add("A) file translation, B) Format Translation, C) Formula Translation, D) Floppy Translation");
	answers.add("C) Formula Translation");
	questions.add("The computer that process both analog and digital is called");
	options.add("A) analog computer, B) digital computer, C) hybrid computer, D) mainframe computer");
	answers.add("D) mainframe computer");
	questions.add("Which of the following is not computer language?");
	options.add("A) high level language, B) medium level language, C) low level language, D) all of them");
	answers.add("B) medium level language");
	questions.add("Which of the following is not primary storage device?");
	options.add("A) magnetic tape, B) magnetic disk, C) optical disk, D) none of them");
	answers.add("D) none of them");
	questions.add("How many address lines are needed to address each memory location in a 2048*4 memory chip?");
	options.add("A) 10, B) 11, C) 12, D) none of them");
	answers.add("B) 11");
	questions.add("Which of the following require large computers memory?");
	options.add("A) imaging, B) graphics, C) voice, D) all of them");
	answers.add("D) all of them");
	questions.add("BCD =");
	options.add("A) Binary Coded Decimal, B) Bit Code Decimal, C) Binary Coded Digit, D) Bit Coded Digit");
	answers.add("A) Binary Coded Decimal");
	questions.add("ASCII =");
	options.add("A) American Stable Code for International Interchange, B) American Standard Case for Institutional Interchange, C) American Standard Code for Information Interchange, D) American Standard Code for Interchange Information");
	answers.add("C) American Standard Code for Information Interchange");
	questions.add("Which statement is valid about magnetic tape?");
	options.add("A) it is plastic ribbon, B) it is coated on both sides with iron oxide, C) it can be erased and reused, D) all of them");
	answers.add("A) it is plastic ribbon");
	questions.add("Which language is directly understood by the computer without translation program?");
	options.add("A) machine language, B) assembly language, C) high level language, D) none of them");
	answers.add("A) machine language");
	questions.add("EEPROM =");
	options.add("A) Electrically Erasable Programmable Read Only Memory, B) Easily Erasable Programmable Real Only Memory, C) Electronic Erasable Programmable Read Only Memory, D) none of them");
	answers.add("A) Electrically Erasable Programmable Read Only Memory");
	questions.add("The data recoding format is most of the modern magnetic tape is");
	options.add("A) 7-bit ASCII, B) 7-bit EBCDIC, C) 8-bit ASCII, D) 8-bit EBCDIC");
	answers.add("D) 8-bit EBCDIC");
	questions.add("A name or number used to identify a storage location is called");
	options.add("A) a byte, B) a record, C) an address, D) all of them");
	answers.add("C) an address");
	questions.add("Which American computer company is called Big Blue?");
	options.add("A) Microsoft, B) Compa Corp, C) IBM, D) Tandy Svenson");
	answers.add("C) IBM");
	questions.add("A term associated with the comparison of processing speeds of different computer system is");
	options.add("A) EFTS, B) MPG, C) MIPS, D) CPS");
	answers.add("C) MIPS");
	questions.add("An integrated circuit is");
	options.add("A) a complicated circuit, B) an integrating device, C) much con, D) fabricated on a tiny silicon chip");
	answers.add("D) fabricated on a tiny silicon chip");
	questions.add("MSI Stands for");
	options.add("A) Medium Scale Integrated Circuits, B) Medium System Integrated Circuits, C) Medium Scale Intelligent Circuit, D) Medium System Intelligent Circuit");
	answers.add("A) Medium Scale Integrated Circuits");
	questions.add("Which of the following is associated with error detector?");
	options.add("A) odd parity bit, B) even parity bit, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Instruction in computer languages consists of");
	options.add("A) OPCODE, B) OPERAND, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is a secondary memory device?");
	options.add("A) keyboard, B) disk, C) ALU, D) all of them");
	answers.add("B) disk");
	questions.add("When did IBM introduce the 20286 based PC/AT?");
	options.add("A) 1982, B) 1984, C) 1985, D) 1989");
	answers.add("B) 1984");
	questions.add("Second Generations computers were developed during");
	options.add("A) 1949 to 1955, B) 1956 to 1965, C) 1965 to 1970, D) 1970 to 1975");
	answers.add("B) 1956 to 1965");
	questions.add("Tape speed is measured in");
	options.add("A) feet per second, B) inch per second, C) meter per second, D) centimeter per second");
	answers.add("B) inch per second");
	questions.add("Machine language is");
	options.add("A) machine dependent, B) difficult to program, C) error prone, D) all of them");
	answers.add("D) all of them");
	questions.add("The difference between memory and storage is that memory is _______ and storage is ______");
	options.add("A) temporary, permanent, B) permanent, temporary, C) slow, fast, D) all of them");
	answers.add("A) temporary, permanent");
	questions.add("The capacity of 3.5 inch floppy disk is");
	options.add("A) 1.40 MB, B) 1.44 MB, C) 1.40 GB, D) 1.44 GB");
	answers.add("B) 1.44 MB");
	questions.add("Magnetic disks are the most popular medium for");
	options.add("A) direct access, B) sequential access, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Mnemonic a memory trick is used in which of the following language?");
	options.add("A) machine language, B) assembly language, C) high level language, D) none of them");
	answers.add("B) assembly language");
	questions.add("A floppy disk contains");
	options.add("A) circular tracks only, B) sectors only, C) both circular tracks and sectors, D) all of them");
	answers.add("C) both circular tracks and sectors");
	questions.add("When was the X window system born?");
	options.add("A) 1984, B) 1989, C) 1985, D) 1990");
	answers.add("A) 1984");
	questions.add("The process of restarting a computer system by loading instructions from a secondary storage device into the computer memory is called");
	options.add("A) duping, B) booting, C) padding, D) CPS");
	answers.add("B) booting");
	questions.add("Most important advantage of an IC is its");
	options.add("A) easy replacement in case of circuit failure, B) extremely high reliability, C) reduced cost, D) lower power consumption");
	answers.add("B) extremely high reliability");
	questions.add("The computer size was very large in");
	options.add("A) first generation, B) second generation, C) third generation, D) fourth generation");
	answers.add("A) first generation");
	questions.add("Storage capacity of magnetic disk depends on");
	options.add("A) tracks per inch of surface, B) bits per inch of tracks, C) disk pack in disk surface, D) all of them");
	answers.add("D) all of them");
	questions.add("The translator program used in assembly language is called");
	options.add("A) compiler, B) interpreter, C) assembler, D) translator");
	answers.add("C) assembler");
	questions.add("The octal equivalence of 111010 is");
	options.add("A) 81, B) 72, C) 71, D) none of them");
	answers.add("B) 72");
	questions.add("Today's computer giant IBM was earlier known by different name which was changes in 1924. What was that name?");
	options.add("A) Tabulator Machine Co., B) Computer Tabulating Recording Co., C) The Tabulator Ltd., D) International Computer Ltd.");
	answers.add("A) Tabulator Machine Co.");
	questions.add("Who invented the microprocessor?");
	options.add("A) Marcian E. Huff, B) Herman H. Goldstein, C) Joseph Jacquard, D) all of them");
	answers.add("A) Marcian E. Huff");
	questions.add("In a punched card system, data is processed by a");
	options.add("A) Keypunch machine, sorter and posting machine, B) accounting machine, posting machine and billing machine, C) sorter, posting machine, and billing machine, D) accounting machine, keypunch machine and sorter");
	answers.add("D) accounting machine, keypunch machine and sorter");
	questions.add("Microprocessors as switching devices are for which generation computers");
	options.add("A) first generation, B) second generation, C) third generation, D) fourth generation");
	answers.add("A) first generation");
	questions.add("Reading data is performed in magnetic disk by");
	options.add("A) read/write leads, B) sectors, C) track, D) lower surface");
	answers.add("A) read/write leads");
	questions.add("Easily relocatable language is");
	options.add("A) machine language, B) assembly language, C) high level language, D) medium level language");
	answers.add("B) assembly language");
	questions.add("The first electronic computer in the world was");
	options.add("A) UNIVAC, B) EDVAC, C) ENIAC, D) all of them");
	answers.add("C) ENIAC");
	questions.add("The first electronic general purpose digital computer built by Mauchly and Eckert called ENIA did not work on the stored program principle. How many numbers could it store in its internal memory?");
	options.add("A) 100, B) 20, C) 40, D) 80");
	answers.add("B) 20");
	questions.add("One computer that is not considered a portable computer is");
	options.add("A) minicomputer, B) laptop computer, C) notebook computer, D) all of them");
	answers.add("A) minicomputer");
	questions.add("The first machine to successfully perform a long series of arithmetic and logical operations was");
	options.add("A) ENIAC, B) Mark-I, C) Analytic engine, D) UNIVAC-I");
	answers.add("B) Mark-I");
	questions.add("Which generation of computer is still underdevelopment?");
	options.add("A) fourth generation, B) fifth generation, C) sixth generation, D) seventh generation");
	answers.add("B) fifth generation");
	questions.add("Access time is");
	options.add("A) seek time + latency time, B) seek time, C) seek time - latency time, D) latency time");
	answers.add("A) seek time + latency time");
	questions.add("Which of the following is called low level languages?");
	options.add("A) machine language, B) assembly language, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("The most commonly used standard data code to represent alphabetical, numerical and punctuation characters used in electronic data processing system is called");
	options.add("A) ASCII, B) EBCDIC, C) BCD, D) all of them");
	answers.add("A) ASCII");
	questions.add("The digital computer was developed primarily in");
	options.add("A) USSR, B) Japan, C) USA, D) UK");
	answers.add("C) USA");
	questions.add("IBM 7000 digital computer");
	options.add("A) belongs to second generation, B) uses VLSI, C) employs semiconductor memory, D) has modular constructions");
	answers.add("C) employs semiconductor memory");
	questions.add("Artificial Intelligence is associated with which generation?");
	options.add("A) fourth generation, B) fifth generation, C) sixth generation, D) seventh generation");
	answers.add("B) fifth generation");
	questions.add("Seek time is");
	options.add("A) time to position the head over proper track, B) time to position the head over proper sector, C) time to position the head over proper cylinder, D) none of them");
	answers.add("A) time to position the head over proper track");
	questions.add("Which of the following is problem oriented language?");
	options.add("A) high level language, B) machine language, C) assembly language, D) low level language");
	answers.add("A) high level language");
	questions.add("Which was the computer conceived by Babbage?");
	options.add("A) analytical engine, B) arithmetic machine, C) Donald Kunth, D) all of them");
	answers.add("A) analytical engine");
	questions.add("The subject of cybernetics deals with the science of");
	options.add("A) genetics, B) control and communications, C) molecular biology, D) biochemistry");
	answers.add("B) control and communications");
	questions.add("The proper definition of a modern digital computer is");
	options.add("A) an electronic automated machine that can solve problems involving words and numbers, B) a more sopho, C) any machine that can perform mathematical operations, D) a machine that works on binary code");
	answers.add("D) a machine that works on binary code");
	questions.add("In the third Generation of computers");
	options.add("A) distributed data processing first became popular, B) an operating system was first developed, C) high-level procedural languages were first used, D) online real time systems first become popular");
	answers.add("D) online real time systems first become popular");
	questions.add("ALU is");
	options.add("A) Arithmetic Logic Unit, B) Array Logic Unit, C) Application Logic Unit, D) none of them");
	answers.add("A) Arithmetic Logic Unit");
	questions.add("Latency time is");
	options.add("A) time to spin the needed data under head, B) time to spin the needed data under track, C) time to spin data under sector, D) all of them");
	answers.add("A) time to spin the needed data under head");
	questions.add("VGA is");
	options.add("A) Video Graphics Array, B) Visual Graphics Array, C) Volatile Graphics Array, D) Video Graphics Adapter");
	answers.add("A) Video Graphics Array");
	questions.add("An IBM system/38 represents the computer class of");
	options.add("A) small-scale computer, B) medium-scale computer, C) large-scale computer, D) super cm");
	answers.add("A) small-scale computer");
	questions.add("The first firm to mass-market a microcomputer as a personal computer was");
	options.add("A) IBM, B) Sperry Univac, C) Data General Corporation, D) Radio Shack");
	answers.add("C) Data General Corporation");
	questions.add("A digital computer did not score over, an analog computer in terms of");
	options.add("A) speed, B) accuracy, C) cost, D) memory");
	answers.add("B) accuracy");
	questions.add("In 1830, Charles Babbage designed a machine called analytical engine, which he showed at the parts exhibition. In which year was it exhibited?");
	options.add("A) 1820, B) 1860, C) 1855, D) 1870");
	answers.add("C) 1855");
	questions.add("Which was the world's first minicomputer and when was it introduced?");
	options.add("A) PDP-I, 1958, B) IBM System/36, 1960, C) PDP-II, 1961, D) VAX 11/780, 1962");
	answers.add("A) PDP-I, 1958");
	questions.add("Different components on the motherboard of a PC processor unit are linked together by sets or parallel electrical conducting lines. What are these lines called?");
	options.add("A) conductors, B) buses, C) connectors, D) connectively");
	answers.add("B) buses");
	questions.add("In analog computer");
	options.add("A) input is first converted to digital form, B) output is delaying in digital form, C) all of them");
	questions.add("The system unit of a personal computer typically contains all of the following except");
	options.add("A) microprocessor, B) disk controller, C) serial interface, D) modem");
	answers.add("D) modem");
	questions.add("While inserting a diskette into the diskette drive of a PC, the diskette's label side should face");
	options.add("A) east, B) north, C) south, D) up");
	answers.add("D) up");
	questions.add("Which of the following magazines covers only the IBM PC and its compatibles?");
	options.add("A) byte, B) PC magazine, C) personal computing, D) interface age");
	answers.add("B) PC magazine");
	questions.add("In latest generation computers the instructions are executed");
	options.add("A) parallel only, B) sequentially only, C) both sequentially and parallel, D) all of them");
	answers.add("C) both sequentially and parallel");
	questions.add("A computer program that converts an entire program into machine language is called a/an");
	options.add("A) interpreter, B) simulator, C) compiler, D) commander");
	answers.add("C) compiler");
	questions.add("Where was India's first computer installed and when?");
	options.add("A) Indian Institute of Technology, Delhi, 1977, B) Indian Institute of Science, Bangalore, 1971, C) Indian Iron & Steel Co. Ltd., 1968, D) Indian Statistical Institute, Calcutta, 1955");
	answers.add("D) Indian Statistical Institute, Calcutta, 1955");
	questions.add("Which of the following professions has not been affected by personal computers?");
	options.add("A) medical, B) clerical and law, C) accounting, D) none of them");
	answers.add("D) none of them");
	questions.add("Who designed the first electronics computer - ENIAC?");
	options.add("A) Van-Neumann, B) Joseph M. Jacquard, C) J. Presper Eckert and John W Mauchly, D) all of them");
	answers.add("C) J. Presper Eckert and John W Mauchly");
	questions.add("Which of the following does not affect the resolution of a video display image?");
	options.add("A) bandwidth, B) register scan rage, C) vertical and horizontal lines of resolution, D) screen size");
	answers.add("D) screen size");
	questions.add("The arranging of data in a logical sequence is called");
	options.add("A) sorting, B) classifying, C) reproducing, D) summarizing");
	answers.add("A) sorting");
	questions.add("Who invented the high level language c?");
	options.add("A) Dennis M. Ritchie, B) Nicklaus Writh, C) Seymour Papert, D) Donald Kunth");
	answers.add("A) Dennis M. Ritchie");
	questions.add("A computer program that translates one program instructions at a time into machine language is called a/an");
	options.add("A) interpreter, B) CPU, C) compiler, D) simulator");
	answers.add("A) interpreter");
	questions.add("As compared to diskettes, the hard disks are");
	options.add("A) more expensive, B) more portable, C) less rigid, D) slowly accessed");
	answers.add("A) more expensive");
	questions.add("Which of the following are the two main components of the CPU?");
	options.add("A) control unit and registers, B) Registers and main memory, C) Control unit and ALU, D) ALU and bus");
	answers.add("C) Control unit and ALU");
	questions.add("When was Apple Macintosh II microcomputer introduced in the market?");
	options.add("A) 1964, B) 1970, C) 1983, D) 1986");
	answers.add("C) 1983");
	questions.add("Personnel who design, program, operate and maintain computer equipment refers to");
	options.add("A) console-operator, B) programmer, C) peopleware, D) system analyst");
	answers.add("C) peopleware");
	questions.add("A small or intelligent device is so called because it contains within it a");
	options.add("A) computer, B) microcomputer, C) programmable, D) sensor");
	answers.add("D) sensor");
	questions.add("Floppy disks which are made from feasible plastic material are also called");
	options.add("A) hard disks, B) high-density disks, C) diskettes, D) templates");
	answers.add("C) diskettes");
	questions.add("A kind of serial dot-matrix printer that forms characters with magnetically-charged ink sprayed dots is called");
	options.add("A) laser printer, B) ink-jet printer, C) drum printer, D) Chan printer");
	answers.add("B) ink-jet printer");
	questions.add("Which of the following is true?");
	options.add("A) fields are composed of bytes, B) records are composed of fields, C) fields are composed of characters, D) all of them");
	answers.add("D) all of them");
	questions.add("What is the name of the new color laptop computer which is powered by a 386 processor at 33 MHz and is built by Epson?");
	options.add("A) AX3/33, B) NEC-20, C) Magnum 2000, D) HCL - 3000");
	answers.add("A) AX3/33");
	questions.add("When did arch rivals IBM and Apple Computers In C. decide to join hands?");
	options.add("A) 1991, B) 1978, C) 1984, D) 1990, ");
	answers.add("A) 1991");
	questions.add("The ALU of a computer responds to the commands coming from");
	options.add("A) primary memory, B) control memory, C) external memory, D) cache memory");
	answers.add("B) control memory");
	questions.add("Regarding a VDU, which statement is more correct?");
	options.add("A) it is an output device, B) it is an input device, C) it is a peripheral device, D) it is hardware device");
	answers.add("C) it is a peripheral device");
	questions.add("Which printer is very commonly used for desktop publishing?");
	options.add("A) laser printer, B) ink-jet printer, C) daisywheel printer, D) dot matrix printer");
	answers.add("A) laser printer");
	questions.add("The latest PC keyboards use a circuit that senses the movement by the change in its capacitance");
	options.add("A) capacitance keyboard, B) mechanical keyboard, C) qwerty keyboard, D) dvorak keyboard");
	answers.add("A) capacitance keyboard");
	questions.add("What does the disk drive of a computer do?");
	options.add("A) rotate the disk, B) read the disk, C) load a program from the disk into the memory, D) both b and c");
	answers.add("D) both b and c");
	questions.add("Human beings are referred to as Homosapinens, which device is called Silicon Sapiens?");
	options.add("A) monitor, B) hardware, C) robot, D) computer");
	answers.add("D) computer");
	questions.add("The act of retrieving existing data from memory is called");
	options.add("A) read-out, B) read from, C) read, D) all of them");
	answers.add("D) all of them");
	questions.add("What is the name of the computer terminal which gives paper printout?");
	options.add("A) display screen, B) soft copy terminal, C) hard copy terminal, D) plotter");
	answers.add("C) hard copy terminal");
	questions.add("The primary advantage of key-to-tape data entry system is");
	options.add("A) a large percentage of editing can be performed at the time of data entry, B) key verification is easily performed, C) the tape is reusable, D) keying errors can be detected");
	answers.add("C) the tape is reusable");
	questions.add("The language that the computer can understand and execute is called");
	options.add("A) machine language, B) application software, C) system program, D) all of them");
	answers.add("A) machine language");
	questions.add("An error in software or hardware is called a bug. What is the alternative computer jargon for it?");
	options.add("A) leech, B) sued, C) slug, D) glitch");
	answers.add("D) glitch");
	questions.add("All modern computer operate on");
	options.add("A) information, B) floppies, C) data, D) word");
	answers.add("C) data");
	questions.add("Dot-matrix is a type of");
	options.add("A) tape, B) printer, C) disk, D) bus");
	answers.add("B) printer");
	questions.add("An output device that uses words or messages recorded on a magnetic medium to produce audio");
	options.add("A) magnetic tape, B) voice response unit, C) voice recognition device, D) voice band");
	answers.add("B) voice response unit");
	questions.add("The two basic types of record-access methods are");
	options.add("A) sequential and random, B) sequential and indexed, C) direct and immediate, D) on-line and real time");
	answers.add("A) sequential and random");
	questions.add("An application suitable for sequential processing is");
	options.add("A) processing of grades, B) payroll processing, C) both a and b, D) all of them");
	answers.add("C) both a and b");
	questions.add("Modern computer was very reliable but they are not");
	options.add("A) fast, B) powerful, C) infallible, D) cheap");
	answers.add("C) infallible");
	questions.add("Instructions and memory address are represented by");
	options.add("A) character code, B) binary codes, C) binary word, D) parity bit");
	answers.add("B) binary codes");
	questions.add("In which year was UK's premier computing event called 'The which computer started?");
	options.add("A) 1980, B) 1985, C) 1986, D) 1987");
	answers.add("A) 1980");
	questions.add("The word processing task associated with changing the appearance of a document is");
	options.add("A) editing, B) writing, C) formatting, D) all of them");
	answers.add("C) formatting");
	questions.add("What is the name of the display feature that highlights are of the screen. Which requires imperator attention?");
	options.add("A) pixel, B) reverse video, C) touch screen, D) cursor");
	answers.add("B) reverse video");
	questions.add("Which of the following code used in present day computing was developed by IBM Corporation?");
	options.add("A) ASCII, B) Hollerith Code, C) Baudot Code, D) EBCDIC Code");
	answers.add("D) EBCDIC Code");
	questions.add("The advantage of COM are its _______ and ______");
	options.add("A) compact size; speed readability, B) compact size; speed, C) readability; speed, D) low cost; readability");
	answers.add("B) compact size; speed");
	questions.add("Which of the following is used as a primary storage device?");
	options.add("A) magnetic drum, B) prom, C) floppy, D) all of them");
	answers.add("B) prom");
	questions.add("IBM launched its first personal computer called IBM-PC in 1981. It has chips from Intel, disk drives from Tendon, operating system from Microsoft, the printer from Epson and the application software from everywhere. Can you name the country which contributed the video display?");
	options.add("A) India, B) China, C) Germany, D) Taiwan");
	answers.add("D) Taiwan");
	questions.add("What is the latest write-once optical storage media?");
	options.add("A) digital paper, B) magnet-optical disk, C) WORM disk, D) CD-ROM disk");
	answers.add("D) CD-ROM disk");
	questions.add("Which of the following file organization is most efficient for a file with a high degree of file activity?");
	options.add("A) sequential, B) ISAM, C) VSAM, D) B-Tree Index");
	answers.add("A) sequential");
	questions.add("Which of the following memories needs refreshing?");
	options.add("A) SRAM, B) DRAM, C) ROM, D) all of them");
	answers.add("B) DRAM");
	questions.add("Personal computers use a number of chips mounted on a main circuit boarD. What is the common name for such boards?");
	options.add("A) breadboard, B) daughter board, C) motherboard, D) father board");
	answers.add("C) motherboard");
	questions.add("The most important advantage of a video disk is");
	options.add("A) compactness, B) potential capacity, C) durability, D) cost effectiveness");
	answers.add("B) potential capacity");
	questions.add("A disadvantage of the laser printer is");
	options.add("A) it is quieter than an impact printer, B) it is very slow, C) the output is of a lower quality, D) none of them");
	answers.add("D) none of them");
	questions.add("Which of the following devices can be used to directly image printed text?");
	options.add("A) OCR, B) OMR, C) MICR, D) all of them");
	answers.add("A) OCR");
	questions.add("In most IBM PCs, the CPU, the device drives, memory expansion slots and active components are mounted on a single boarD. What is the name of this board?");
	options.add("A) grandmother board, B) motherboard, C) breadboard, D) daughter board");
	answers.add("B) motherboard");
	questions.add("What is the number of read-write heads in the drive for a 9-trac magnetic tape?");
	options.add("A) 9, B) 16, C) 18, D) 27");
	answers.add("A) 9");
	questions.add("The two kinds of main memory are");
	options.add("A) primary and secondary, B) random and sequential, C) ROM and RAM, D) all of them");
	answers.add("C) ROM and RAM");
	questions.add("Which of the following will happen when data is entered into memory location?");
	options.add("A) it will add to the content of the location, B) it will change the address of the memory location, C) it will erase the previous content, D) it will not be fruitful if there is already some data at the location");
	answers.add("C) it will erase the previous content");
	questions.add("A storage area used to store data to compensate for the difference in speed at which the different units can handle data is");
	options.add("A) memory, B) buffer, C) accumulator, D) address");
	answers.add("B) buffer");
	questions.add("Which of the following is not true for a magnetic disk?");
	options.add("A) it is expensive relative to magnetic tape, B) it provides only sequential access to stored data, C) users can easily update records by writing over the old data, D) all of them");
	answers.add("B) it provides only sequential access to stored data");
	questions.add("The output quality of a printer is measured by");
	options.add("A) dot per inch, B) dots per s. inch, C) dots printed per unit time, D) all of them");
	answers.add("B) dots per s. inch");
	questions.add("What is meant by a dedicated computer?");
	options.add("A) which is used by one person only, B) which is assigned one and only task, C) which uses one kind of software, D) which is meant for application software");
	answers.add("B) which is assigned one and only task");
	questions.add("Before a disk drive can access any sector record, a computer program has to provide the record's disk address. What information does this address specify?");
	options.add("A) track number, B) sector number, C) surface number, D) all of them");
	answers.add("D) all of them");
	questions.add("The terminal device that functions as a cash register, computer terminal and OCR reader is the");
	options.add("A) Data collection terminal, B) OCR register terminal, C) Video Display terminal, D) POS terminal");
	answers.add("D) POS terminal");
	questions.add("Which of the following is not valid version of MS office?");
	options.add("A) Office XP, B) Office Vista, C) Office 2007, D) none of them");
	answers.add("B) Office Vista");
	questions.add("What is the default left margin in Word 2003 document?");
	options.add("A) 1, B) 1.25, C) 1.5, D) 2");
	answers.add("B) 1.25");
	questions.add("What is the maximum number of font size you can apply for any character?");
	options.add("A) 163, B) 1638, C) 16038, D) none of them");
	answers.add("B) 1638");
	questions.add("From which menu you can insert Header and Footer?");
	options.add("A) insert menu, B) view menu, C) format menu, D) tools menu");
	answers.add("B) view menu");
	questions.add("Which of the following is not one of the three 'Mail merge Helper' steps?");
	options.add("A) merge the two files, B) create the main document, C) set the mailing list parameters, D) create the data source");
	answers.add("C) set the mailing list parameters");
	questions.add("Which of the following line spacing is invalid?");
	options.add("A) single, B) double, C) triple, D) multiple");
	answers.add("C) triple");
	questions.add("Which of the following is used to create newspaper style columns?");
	options.add("A) format tabs, B) table insert table, C) insert textbook, D) format columns");
	answers.add("D) format columns");
	questions.add("You cannot close MS word application by");
	options.add("A) choosing File menu then Exit submenu, B) press Alt+F4, C) click X button on title bar, D) from File menu choose Close submenu");
	answers.add("D) from File menu choose Close submenu");
	questions.add("What is gutter margin?");
	options.add("A) margin that is added to the left margin when printing, B) margin that is added to right margin when printing, C) margin that is added to the binding side of hen printing, D) margin that is added to the outside of the hen printing");
	answers.add("C) margin that is added to the binding side of hen printing");
	questions.add("Which of the following is graphics solution for Word Processors?");
	options.add("A) clipart, B) word art, C) drop cap, D) all of them");
	answers.add("A) clipart");
	questions.add("After typing header text, how can you quickly enter footer text?");
	options.add("A) press own key and type the text for footer, B) click on Switch between Header & Footer then type the text, C) both a and b, D) none of them");
	answers.add("B) click on Switch between Header & Footer then type the text");
	questions.add("Which of the following button will allow you to add, delete, or change records in your Data Source?");
	options.add("A) Data Source button, B) Edit button, C) Edit Data Source button, D) Data editing button");
	answers.add("C) Edit Data Source button");
	questions.add("How can you apply exactly the same formatting you did to another text?");
	options.add("A) cope the text and paste in new location, then type the new text again, B) copy the text and click on Paste Special tool on new place, C) select the text then click on Format Painter and select the new text, D) all of them");
	answers.add("C) select the text then click on Format Painter and select the new text");
	questions.add("Columns dialog box can be opened from");
	options.add("A) format menu columns submenu, B) double click on column space in ruler, C) press Alt+O+C, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following are word processing software?");
	options.add("A) WordPerfect, B) Easy Word, C) MS Word, D) all of them");
	answers.add("D) all of them");
	questions.add("The key F12 opens a");
	options.add("A) Save as dialog box, B) Open dialog box, C) Save dialog box, D) Close dialog box");
	answers.add("A) Save as dialog box");
	questions.add("Portrait and Landscape are");
	options.add("A) rientation, B) paper size, C) ayout, D) all of them");
	answers.add("A) rientation");
	questions.add("The keystrokes Ctrl+I is used to");
	options.add("A) increase font size, B) inserts a line break, C) indicate the text should be bold, D) applies italic format to selected text");
	answers.add("D) applies italic format to selected text");
	questions.add("When inserting umber in footer it appeared 1 but you wish to show A. How can you do that?");
	options.add("A) all of them, B) from Format menu choose bullets and Numbering and configure necessary setting, C) from Insert menu choose umber and specify necessary setting, D) click on number Format tool and specify required setting");
	answers.add("D) click on umber Format tool and specify required setting");
	questions.add("It is possible to ______ a data source before performing a merge");
	options.add("A) create, B) modify, C) sort, D) all of them");
	answers.add("D) all of them");
	questions.add("What should you do if your require passing the same format in many places?");
	options.add("A) click the Format painter and go on pasting in many places holding Alt Key, B) double click the format painter then go on pasting in many places, C) click the format painter then go on pasting to many places holding Ctrl Key, D) all of them");
	answers.add("B) double click the format painter then go on pasting in many places");
	questions.add("You can jump to the next column by");
	options.add("A) clicking with your mouse on the next column, B) press Alt+Down-Arrow, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("MS Office provides help in many ways, which of these is one of them?");
	options.add("A) what is this?, B) office assistant, C) help menu, D) all of them");
	answers.add("D) all of them");
	questions.add("What is the short cut key to open the Open dialog box?");
	options.add("A) F12, B) Shift F12, C) Alt+F12, D) Ctrl+F12");
	answers.add("D) Ctrl+F12");
	questions.add("If you need to change the typeface of a document, which menu will you choose?");
	options.add("A) edit, B) view, C) format, D) tools");
	answers.add("C) format");
	questions.add("A character that is raised and smaller above the baseline is known as");
	options.add("A) outlined, B) raised, C) superscript, D) subscript");
	answers.add("C) superscript");
	questions.add("Which of the following statement is false?");
	options.add("A) you can set different header footer for even and odd, B) you can set different umber formats for different sections, C) you can set different header footer for first f a section, D) you can set different header and footer for last f a section");
	answers.add("D) you can set different header and footer for last f a section");
	questions.add("What is the default font size of a new Word document based on Normal Template?");
	options.add("A) 10 pt, B) 12 pt, C) 14 pt, D) none of them");
	answers.add("B) 12 pt");
	questions.add("On which toolbar can you find Format Painter tool?");
	options.add("A) standard toolbar, B) formatting toolbar, C) drawing toolbar, D) picture toolbar");
	answers.add("A) standard toolbar");
	questions.add("How can you break the current column and start a new column immediately?");
	options.add("A) press Ctrl+Shift+Enter, B) press Alt+Enter, C) press Ctrl+Enter, D) press Alt+Shift+Enter");
	answers.add("A) press Ctrl+Shift+Enter");
	questions.add("A feature of MS Word that saves the document automatically after certain interval is available on");
	options.add("A) Save tab on Options dialog box, B) Save as dialog box, C) both a and b, D) none of them");
	answers.add("A) Save tab on Options dialog box");
	questions.add("Which of the following is not a font style?");
	options.add("A) bold, B) italics, C) regular, D) superscript");
	answers.add("D) superscript");
	questions.add("What is the purpose of inserting header and footer in document?");
	options.add("A) to enhance the overall appearance of the document, B) to mark the starting and ending of, C) to make large document more readable, D) to allow eaders and footers appear on document when printed");
	answers.add("D) to allow eaders and footers appear on document when printed");
	questions.add("Where can you change the vertical alignment?");
	options.add("A) formatting toolbar, B) paragraph dialog box, C) etup dialog box, D) standard toolbar");
	answers.add("C) etup dialog box");
	questions.add("What is the default font used in MS Word document?");
	options.add("A) Times New Roman, B) Arial, C) Algerian, D) Preeti");
	answers.add("A) Times New Roman");
	questions.add("Which indent marker controls all the lines except first line?");
	options.add("A) First Line Indent Market, B) Left Indent Marker, C) Hanging Indent Marker, D) Right Indent Marker");
	answers.add("B) Left Indent Marker");
	questions.add("What is the smallest width of a column?");
	options.add("A) 0, B) 0.5, C) 1, D) 1.5");
	answers.add("B) 0.5");
	questions.add("Where can you fine the horizontal split bar on MS Word screen?");
	options.add("A) on the left of horizontal scroll bar, B) on the right of horizontal scroll bar, C) on the top of vertical scroll bar, D) on the bottom of vertical scroll bar");
	answers.add("C) on the top of vertical scroll bar");
	questions.add("Pressing F8 key for three times select");
	options.add("A) a word, B) a sentence, C) a paragraph, D) entire document");
	answers.add("B) a sentence");
	questions.add("Which of the following function key activates the speller?");
	options.add("A) F5, B) F7, C) F9, D) Shift+F7");
	answers.add("B) F7");
	questions.add("To get to the 'Symbol' dialog box, click on the _______ menu and choose 'Symbol'.");
	options.add("A) insert, B) format, C) tools, D) table");
	answers.add("A) insert");
	questions.add("Which tap in Font dialog box contains options to apply font effects?");
	options.add("A) font tab, B) character spacing, C) text effects, D) standard toolbar");
	answers.add("A) font tab");
	questions.add("How can you remove tab stop markets from ruler?");
	options.add("A) double click the tab market and choose Clear All, B) drag the tab stop market out of the ruler, C) right click the tab stop market and choose remove, D) all of them");
	answers.add("B) drag the tab stop market out of the ruler");
	questions.add("If the number of columns is selected 1 and the line between check box is marked, where is the line drawn?");
	options.add("A) in the left margin, B) in the right margin, C) both a and b, D) none of them");
	answers.add("D) none of them");
	questions.add("Which of the following is not available on the Ruler of MS Word screen?");
	options.add("A) Tab stop box, B) left indent, C) right indent, D) center indent");
	answers.add("B) left indent");
	questions.add("What happens if your press Ctrl+Shift+F8?");
	options.add("A) it activates extended selection, B) it activates the rectangular selection, C) it selects the paragraph on which the insertion line is, D) none of them");
	answers.add("B) it activates the rectangular selection");
	questions.add("The minimum number of rows and columns in MS Word document is");
	options.add("A) 1 and 1, B) 2 and 1, C) 2 and 2, D) none of them");
	answers.add("A) 1 and 1");
	questions.add("Which of the following symbol sets would be most likely to contain a mathematical symbol such as a degree sign, greater than or equal to or a Greek letter?");
	options.add("A) wingdings, B) wingdings, C) webdings, D) symbol");
	answers.add("D) symbol");
	questions.add("If you need to double underline a word, how will you do that?");
	options.add("A) go to Format menu and then Font option, open Underline Style and choose Double Underline, B) from Format menu choose Font option and then from Font tab open underline Style and select Double Underline, C) select the text then choose Format >> Font and on font tab open Underline Style and choose Double Underline, D) click double underline too on formatting toolbar");
	answers.add("C) select the text then choose Format >> Font and on font tab open Underline Style and choose Double Underline");
	questions.add("Which operation you will perform if you need to move a block of text?");
	options.add("A) copy and paste, B) cut and paste, C) paste and delete, D) paste and cut");
	answers.add("B) cut and paste");
	questions.add("The other Col# are inactive when you have selected 3 columns. How will you activate those boxes?");
	options.add("A) double click on spacing box, B) double click on inactive Col#, C) remove mark from Line between checkbox, D) remove mark from Equal Column Width check box");
	answers.add("D) remove mark from Equal Column Width check box");
	questions.add("What is place to the left of horizontal scroll bar?");
	options.add("A) Tab stop buttons, B) view buttons, C) split buttons, D) indicators");
	answers.add("D) indicators");
	questions.add("How can you disable extended selection mode?");
	options.add("A) press F8 again to disable, B) press Del to disable, C) press Esc to disable, D) press Enter to disable");
	answers.add("C) press Esc to disable");
	questions.add("Thesaurus tool in MS Word is used for");
	options.add("A) scrolling suggestions, B) grammar options, C) synonyms and antonyms words, D) all of them");
	answers.add("C) synonyms and antonyms words");
	questions.add("When assigning a shortcut key to a symbol, you should always try select a key or key combination that is");
	options.add("A) unassigned, B) located on the ten-key pad section of your keyboard, C) assigned to another task, D) from the same font family as the symbol");
	answers.add("A) unassigned");
	questions.add("Drop cap means");
	options.add("A) all caps, B) small caps, C) title case, D) none of them");
	answers.add("D) none of them");
	questions.add("What is the extension of World files?");
	options.add("A) FIL, B) DOT, C) DOC, D) TXT");
	answers.add("C) DOC");
	questions.add("How much space in minimum must be provided between columns?");
	options.add("A) 0, B) 0.5, C) 1, D) 1.5");
	answers.add("A) 0");
	questions.add("Which file starts MS Word?");
	options.add("A) winword.exe, B) word.exe, C) msword.exe, D) word2003.exe");
	answers.add("A) winword.exe");
	questions.add("What does EXT indicator on status bar of MS word indicate?");
	options.add("A) it indicates whether the external text is pasted on document or not, B) it indicates whether extended add-ons are installed on MS Word or not, C) it indicates whether extended selection mode is turned on or off, D) none of them");
	answers.add("C) it indicates whether extended selection mode is turned on or off");
	questions.add("Why Drop Caps are used in document?");
	options.add("A) to drop all the capital letters, B) to automatically begin each paragraph with capital letter, C) to begin a paragraph with a large dropped initial capital letter, D) none of them");
	answers.add("C) to begin a paragraph with a large dropped initial capital letter");
	questions.add("Suppose you wanted to create an AutoCorrect entry that would type the words 'We regret to inform you that your submission has been declined'. Of the following choices which would be the best name you could assign to this entry?");
	options.add("A) regret, B) subdual, C) we regret to inform you that your submission has been declined, D) 11");
	answers.add("B) subdual");
	questions.add("What is the short cut key to open the Open dialog box?");
	options.add("A) Ctrl+F, B) Alt+Ctrl+F, C) Ctrl+D, D) Ctrl+Shift+D");
	answers.add("C) Ctrl+D");
	questions.add("Which of the following option is not available in insert>>Picture?");
	options.add("A) chart, B) Word Art, C) Clip Art, D) Graph");
	answers.add("D) Graph");
	questions.add("To open Columns dialog box quickly");
	options.add("A) double click on the left margin area of ruler, B) double click the space between area on ruler, C) double click the right margin in ruler, D) all of them");
	answers.add("B) double click the space between area on ruler");
	questions.add("How many ways you can save a document?");
	options.add("A) 3, B) 4, C) 5, D) 6");
	answers.add("A) 3");
	questions.add("What is the maximum number of lines you can set for a drop cap?");
	options.add("A) 3, B) 10, C) 15, D) 20");
	answers.add("B) 10");
	questions.add("A bookmark is an item or location in document that you identify as a name for future reference. Which of the following task is accomplished by using bookmarks?");
	options.add("A) to add anchors in web, B) to mark the ending of a paragraph of document, C) to quickly jump to specific location in document, D) to add hyperlinks in webORRECT ANSWER IS: to quickly jump to specific location in document");
	questions.add("If you want to convert a symbol or several lines of text into an AutoCorrect entry, you should");
	options.add("A) insert the symbol or type the text, then select the text or symbol and go to the AutoCorrect dialog box, B) click the Tools menu and choose AutoCorrect Options, then click the insert menu and choose Symbol to add the symbol or paragraph to AutoCorrect, C) AutoCorrect can only accommodate one line of text. It is not possible to convert a symbol or multiple lines of text into an AutoCorrect entry, D) insert the symbol or type the text, then select the text or symbol and click the Edit menu followed by Paste Special. Select New AutoCorrect Entry and then click OK");
	answers.add("A) insert the symbol or type the text, then select the text or symbol and go to the AutoCorrect dialog box");
	questions.add("How can you access the font size tool on formatting toolbar?");
	options.add("A) Ctrl+S, B) Ctrl+Shift+S, C) Ctrl+P, D) Ctrl+Shift+P");
	answers.add("D) Ctrl+Shift+P");
	questions.add("To insert a drop cap in one of the paragraph you should access");
	options.add("A) Insert Menu, B) Format, C) Tools, D) none of them");
	answers.add("B) Format");
	questions.add("Which of the following command is not available in Tools menu?");
	options.add("A) auto text, B) AutoCorrect, C) auto summarize, D) macro");
	answers.add("A) auto text");
	questions.add("You wished to justify text over the height of paper, which option will you choose?");
	options.add("A) etup from File menu, B) paragraph from Format menu, C) from formatting toolbar, D) font from Format menu");
	answers.add("A) etup from File menu");
	questions.add("If you want to keep track of different editions of a document which features will you use?");
	options.add("A) editions, B) versions, C) track change, D) all of them");
	answers.add("B) versions");
	questions.add("What is the default number of lines to drop for drop cap?");
	options.add("A) 3, B) 10, C) 15, D) 20");
	answers.add("A) 3");
	questions.add("A word processor would most likely to be used to do");
	options.add("A) keep an account of money spent, B) do a computer search in media center, C) maintain an inventory, D) type a biography");
	answers.add("D) type a biography");
	questions.add("Autocorrect was originally designed to replace ______ words as you type");
	options.add("A) short, repetitive, B) grammatically incorrect, C) misspelled, D) none of them");
	answers.add("C) misspelled");
	questions.add("How can you make the selected character superscripted?");
	options.add("A) Ctrl+=, B) Ctrl+shift+=, C) Alt+Ctrl+Shift+=, D) none of them");
	answers.add("B) Ctrl+shift+=");
	questions.add("How many different positions can you set for drop cap?");
	options.add("A) 1, B) 2, C) 4, D) 6");
	answers.add("B) 2");
	questions.add("To remove the cursor o f document");
	options.add("A) Ctrl+PgDn, B) Ctrl+PgUp, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is not of the merge process?");
	options.add("A) sort the data source records, B) format a main document, C) edit a data source, D) merge the two files to print or create a new document");
	answers.add("A) sort the data source records");
	questions.add("Background color or effects applied on a document is not visible in");
	options.add("A) web layout view, B) print layout view, C) reading view, D) print view");
	answers.add("D) print view");
	questions.add("What is the shortcut key you can press to create a copyright symbol?");
	options.add("A) Alt+Ctrl+C, B) Alt+C, C) Ctrl+C, D) Ctrl+Shift+C");
	answers.add("A) Alt+Ctrl+C");
	questions.add("What happens when you click on Insert>>Picture>>Clip Art");
	options.add("A) it inserts a clipart picture into document, B) it lets you choose clipart to insert into document, C) it opens Clip Art taskbar, D) none of them");
	answers.add("C) it opens Clip Art taskbar");
	questions.add("Which of the following is the second step in creating a macro?");
	options.add("A) start recording, B) using your mouse or keyboard perform the task you want to automate, C) assign a keyboard shortcut to the macro, D) give the macro a name");
	answers.add("C) assign a keyboard shortcut to the macro");
	questions.add("What does Ctrl+= key effect?");
	options.add("A) superscript, B) subscript, C) all caps, D) shadow");
	answers.add("B) subscript");
	questions.add("What is the maximum number of lines you can set for lines to drop box?");
	options.add("A) 3, B) 5, C) 10, D) 15");
	answers.add("C) 10");
	questions.add("Text boundary can be displayed or hidden from");
	options.add("A) auto text option from Insert menu, B) options from Tools menu, C) customize from Tools menu, D) all of them");
	answers.add("B) options from Tools menu");
	questions.add("What is a portion of a document in which you set certain ormatting options?");
	options.add("A) document, B) paragraph, C) section, D) setup");
	answers.add("C) section");
	questions.add("How many columns can you insert in a word document in maximum?");
	options.add("A) 35, B) 45, C) 55, D) 65");
	answers.add("B) 45");
	questions.add("Which option is not available in Insert Table Autofit behavior?");
	options.add("A) Fixed Column Width, B) Autofit to Contents, C) Autofit to Window, D) Autofit to Column");
	answers.add("D) Autofit to Column");
	questions.add("If you will be displaying or printing your document on another computer, you'll want to make sure and select the ______ option under the 'Save' tab");
	options.add("A) Embed Fonts, B) Embed True Type Fonts, C) Save True Type Fonts, D) Save Fonts");
	answers.add("B) Embed True Type Fonts");
	questions.add("What happens if you mark on Hidden check box of Font dialog box after you select some text?");
	options.add("A) the text is deleted from document and you need to bring from Recycle Bin if require again, B) the text is hidden and you need to bring it by removing the check box if needed again, C) the text is deleted and cannot be returned back, D) the text is hidden and cannot be returned back");
	answers.add("B) the text is hidden and you need to bring it by removing the check box if needed again");
	questions.add("Which of the following can not be used to create parallel style column?");
	options.add("A) format tabs, B) table insert table, C) insert textbook, D) format columns");
	answers.add("D) format columns");
	questions.add("Borders can be applied to");
	options.add("A) cells, B) paragraph, C) text, D) all of them");
	answers.add("D) all of them");
	questions.add("What is the smallest and largest font size available in Font Size toll on formatting toolbar?");
	options.add("A) 8 and 72, B) 8 and 64, C) 12 and 72, D) none of them");
	answers.add("A) 8 and 72");
	questions.add("To Autofit the width of column");
	options.add("A) double click the right border of column, B) double click the left border of column, C) double click the column header, D) all of them");
	answers.add("A) double click the right border of column");
	questions.add("In Word, the mailing list is known as the");
	options.add("A) data sheet, B) source, C) data source, D) sheet");
	answers.add("C) data source");
	questions.add("How can you increase the font size of selected text by one point every time?");
	options.add("A) by pressing Ctrl+], B) by pressing Ctrl+[, C) by pressing Ctrl+}, D) by pressing Ctrl+{");
	answers.add("A) by pressing Ctrl+]");
	questions.add("Which of the following is not a type of argin?");
	options.add("A) left, B) right, C) center, D) top");
	answers.add("C) center");
	questions.add("Which of the following is not a valid Zoom percentage in Excel?");
	options.add("A) 10, B) 100, C) 300, D) 500");
	answers.add("D) 500");
	questions.add("You can set order in Excel from");
	options.add("A) from border tab in formal cells dialog box, B) from boarder tool in formatting toolbar, C) from line style tool in drawing toolbar, D) you can not set order in excel");
	answers.add("D) you can not set order in excel");
	questions.add("You can use the formula palette to");
	options.add("A) format cells containing numbers, B) create and edit formulas containing functions, C) entered assumption data, D) copy a range of cells");
	answers.add("B) create and edit formulas containing functions");
	questions.add("Macros are (run) or executed from the ______ menu");
	options.add("A) insert, B) format, C) tools, D) data");
	answers.add("C) tools");
	questions.add("Which of the following methods can not be used to enter data in a cell?");
	options.add("A) pressing an arrow key, B) pressing the tab key, C) pressing the Esc key, D) clicking the enter button to the formula bar");
	answers.add("C) pressing the Esc key");
	questions.add("When integrating MS Word and Excel. Word is usually the");
	options.add("A) server, B) source, C) client, D) none of them");
	answers.add("C) client");
	questions.add("When you print preview a worksheet");
	options.add("A) the entire worksheet is displayed, B) the selected range is displayed, C) the active portion of the worksheet is displayed, D) all of them");
	answers.add("D) all of them");
	questions.add("The spelling tool is placed on ______ toolbar");
	options.add("A) standard, B) formatting, C) drawing, D) reviewing");
	answers.add("A) standard");
	questions.add("When all the numbers between 0 and 100 in a range should be displayed in Red color, apply");
	options.add("A) use =if() function to format the required numbers red, B) apply conditional formatting command on format menu, C) select the cells that contain number between 0 and 100 then click red color on text color tool, D) all of them");
	answers.add("B) apply conditional formatting command on format menu");
	questions.add("What Pivot Table toolbar button updates the data in a Pivot Table or Pivot Chart report if the source data has changed");
	options.add("A) format report, B) pivot table, C) refresh data, D) show detail");
	answers.add("C) refresh data");
	questions.add("You can open the consolidate dialog box by choosing consolidate from the _____ menu");
	options.add("A) insert, B) format, C) tools, D) data");
	answers.add("D) data");
	questions.add("Which of the following will not set text in selected cells to italics?");
	options.add("A) pressing Ctrl+I on the keyboard, B) using the Tools-Wizards-Web from menu item, C) using the Format-Cells-Font menu item, D) none of them");
	answers.add("B) using the Tools-Wizards-Web from menu item");
	questions.add("Charts tips can");
	options.add("A) show the formatting of a data label, B) show the name of a data series, C) show the value of data point, D) both b and c");
	answers.add("D) both b and c");
	questions.add("You can group noncontiguous worksheets with");
	options.add("A) the group button on the standard toolbar, B) the shift key and the mouse, C) the Ctrl key and mouse, D) the Alt+Enter key");
	answers.add("C) the Ctrl key and mouse");
	questions.add("A data map is helpful");
	options.add("A) when you have too much data to chart, B) to show a geographic distribution of data, C) to compare data points, D) to show changes in data over time");
	answers.add("B) to show a geographic distribution of data");
	questions.add("If you need to text to show vertically in a cell. How will you achieve this?");
	options.add("A) choose vertical on text alignment in format cells dialog box, B) choose 90 degrees in orientation of format cells dialog box, C) choose distributed from the vertical drop down list of format cells dialog box, D) choose center across selection from horizontal combo box in format cells dialog box");
	answers.add("B) choose 90 degrees in orientation of format cells dialog box");
	questions.add("You can check the conditions against _____ when applying conditional formatting");
	options.add("A) cell value, B) formula, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("What is an expression that tells how the numbers in a determined set of cells are to be calculated?");
	options.add("A) formula, B) field, C) data, D) query");
	answers.add("A) formula");
	questions.add("Each excel file is called a workbook because");
	options.add("A) it can contain text and data, B) it can be modified, C) it can contain many sheets including worksheets and chart sheets, D) you have to work hard to create it");
	answers.add("C) it can contain many sheets including worksheets and chart sheets");
	questions.add("Which of the following methods cannot be used to edit the content of cell?");
	options.add("A) pressing the Alt key, B) clicking the formula bar, C) pressing F2, D) double clicking the cell");
	answers.add("A) pressing the Alt key");
	questions.add("The Name box");
	options.add("A) shows the location of the previously active cell, B) appears to the left of the formula bar, C) appears below the status bar, D) appears below the menu bar");
	answers.add("B) appears to the left of the formula bar");
	questions.add("Weight refers to");
	options.add("A) the print density of character, B) the height of the printed character, C) upright and slanted shape, D) the design and appearance of characters");
	answers.add("A) the print density of character");
	questions.add("Can you set 0.5 inch left indentation for a cell in Excel?");
	options.add("A) excel does not have indentation feature, B) you can specify indentation only if you turn the rulers on, C) indentation can be set from format cells dialog box, D) the indentation can be specified only when printing");
	answers.add("C) indentation can be set from format cells dialog box");
	questions.add("Which of the following is not true regarding Conditional Formatting?");
	options.add("A) you can add more than one condition to check, B) you can set condition to look for bold and apply italics on them, C) you can apply font, border and pattern formats that meets the specified conditions, D) you can delete any condition from conditional formatting dialog box if it is not required");
	answers.add("B) you can set condition to look for bold and apply italics on them");
	questions.add("tr 1 ,tr 2, tr 3 is an example of a");
	options.add("A) formula, B) function, C) series, D) syntax");
	answers.add("C) series");
	questions.add("Which types of charts can excel produce?");
	options.add("A) line graphs and pie charts only, B) only line graphs, C) bar charts, line graphs and pie charts, D) bar charts and line graphs only");
	answers.add("C) bar charts, line graphs and pie charts");
	questions.add("You can activate a cell by");
	options.add("A) pressing the Tab key, B) clicking the cell, C) pressing an arrow key, D) all of them");
	answers.add("D) all of them");
	questions.add("How do you change column width to fit the contents?");
	options.add("A) single-click the boundary to the left to the column heading, B) double click the boundary to the right of the column heading, C) press Alt and single click anywhere in the column, D) all of them");
	answers.add("B) double click the boundary to the right of the column heading");
	questions.add("When you link data maintained in Excel workbook to a Word document");
	options.add("A) the word document cannot be edited, B) the word document contains a reference to the original source application, C) the word document must contain a hyperlink, D) the word document contains a copy of actual data");
	answers.add("B) the word document contains a reference to the original source application");
	questions.add("You can automatically adjust the size of text in a cell if they do not fit in width by");
	options.add("A) double clicking on the right border of column header, B) from format choose columns and then Autofit selection, C) from format cells dialog box mark shrink to fit check box, D) all of them");
	answers.add("C) from format cells dialog box mark shrink to fit check box");
	questions.add("Which of the following is invalid statement?");
	options.add("A) sheet tabs can be colored, B) some picture can be applied as a background of a sheet, C) you can set the column width automatically fit the amount of text, D) the width of a row and be specified manually or fit automatically");
	answers.add("D) the width of a row and be specified manually or fit automatically");
	questions.add("You can edit existing Excel data by pressing the");
	options.add("A) F1 key, B) F2 key, C) F3 key, D) F4 key");
	answers.add("B) F2 key");
	questions.add("How are data organized in a spreadsheet?");
	options.add("A) lines and spaces, B) layers and planes, C) rows and columns, D) height and width");
	answers.add("C) rows and columns");
	questions.add("Which of the following set up options can not be set in the etup dialog box?");
	options.add("A) printer selection, B) vertical or horizontal placement, C) orientation, D) row and column titles");
	answers.add("A) printer selection");
	questions.add("When you work with large worksheets, you may need to");
	options.add("A) size the worksheet to fit on the specific number of, B) add and remove reaks, C) specify only certain print areas, D) all of them");
	answers.add("D) all of them");
	questions.add("When you see a cell with a red triangle in the top right corner, what does this signify?");
	options.add("A) there is an error in the cell, B) there is a comment associated with the cell, C) the font color for text in the cell is red, D) a formula cannot be entered into the cell");
	answers.add("B) there is a comment associated with the cell");
	questions.add("Formatting a cell in Currency, you can specify");
	options.add("A) decimal places, B) currency symbol, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is not an option in the spelling dialog box?");
	options.add("A) edit, B) ignore, C) ignore all, D) change");
	answers.add("A) edit");
	questions.add("The cell reference for a range of cells that starts in cell B1 and goes over to column G and down to row 10 is");
	options.add("A) G1-G10, B) B1.G10, C) B1;G10, D) B1:G10");
	answers.add("D) B1:G10");
	questions.add("What does the VLOOKUP function do?");
	options.add("A) looks up text that contain V, B) checks whether text is the same in one cell as in the next, C) finds related records, D) all of them");
	answers.add("C) finds related records");
	questions.add("What terms refers to a specific set of values saved with the workbook?");
	options.add("A) range, B) scenario, C) trend line, D) what-if analysis");
	answers.add("B) scenario");
	questions.add("Hyperlink cannot be");
	options.add("A) special shapes like stars and banners, B) drawing objects like rectangles ovals, C) pictures, D) all can be hyperlinks");
	answers.add("D) all can be hyperlinks");
	questions.add("To hold row and column titles in places so that they do not scroll when you scroll a worksheet, click the");
	options.add("A) unfreeze panes command on the window menu, B) freeze panes command on the window menu, C) hold titles command on the edit menu, D) split command on the window menu");
	answers.add("B) freeze panes command on the window menu");
	questions.add("Formatting a cell in Number format you can't set");
	options.add("A) decimal places, B) use 1000 separator, C) negative numbers, D) currency symbol");
	answers.add("D) currency symbol");
	questions.add("You can quickly change the appearance of your work by choosing Auto Format from the ______ menu");
	options.add("A) edit, B) view, C) format, D) tools");
	answers.add("C) format");
	questions.add("A user wishes to remove a spreadsheet from a workbook. Which is the correct sequence of events that will do this?");
	options.add("A) go to file - save as - save as type - excel worksheet, B) right click on the spreadsheet tab and select Delete, C) right click on the spreadsheet and select insert - entire column, D) none of them");
	answers.add("B) right click on the spreadsheet tab and select Delete");
	questions.add("Gridlines");
	options.add("A) may be turned off for display but turned on for printing, B) may be turned on or off for printing, C) may be tuned off for displaying and printing, D) all of them");
	answers.add("D) all of them");
	questions.add("Got function? No? You need the insert function dialog box. How do you get it?");
	options.add("A) right click a cell and then click insert, B) click the insert menu and then click function, C) type = in a cell, D) all of them");
	answers.add("B) click the insert menu and then click function");
	questions.add("You can use the horizontal and vertical scroll bars to");
	options.add("A) split a worksheet into two panes, B) view different rows and columns, C) edit the contents of a cell, D) view different worksheets");
	answers.add("B) view different rows and columns");
	questions.add("Which of these is a quick way to copy formatting from a selected cell to two other cells on the same worksheet?");
	options.add("A) use Ctrl to select all three cells, then click the paste button on the standard toolbar, B) copy the selected cell then select the other two cells, click style on the format menu, then click modify, C) click format painter on the formatting toolbar twice then click in each cell you want to copy the formatting to, D) all of them");
	answers.add("C) click format painter on the formatting toolbar twice then click in each cell you want to copy the formatting to");
	questions.add("What is entered by the function =today()");
	options.add("A) the date value for the day according to system clock, B) he time value according to system clock, C) today's date as Text format, D) all of them");
	answers.add("A) the date value for the day according to system clock");
	questions.add("To protect a worksheet, you can choose protection and the protect sheet from the _______ menu");
	options.add("A) edit, B) format, C) tools, D) data");
	answers.add("C) tools");
	questions.add("What feature enables you to adjust or back solve the value in a cell to reach a desired outcome in a formula?");
	options.add("A) goal seek, B) scenario summary report, C) forecasting, D) trend line");
	answers.add("D) trend line");
	questions.add("You can print only an embedded chart by");
	options.add("A) moving the chart to a chart sheet before you print, B) formatting the chart before you print, C) selecting the chart before you print, D) both a and c");
	answers.add("D) both a and c");
	questions.add("Which of the following describes how to select all the cells in a single column?");
	options.add("A) right click on column and select pick from list, B) use data - text to columns menu item, C) left click on the gray column title button, D) pressing Ctrl+A on the keyboard");
	answers.add("C) left click on the gray column title button");
	questions.add("What do we call a computer program that organizes data in rows and columns of cells? You might use this type of program to keep a record of the money you earned moving lawns over the summer?");
	options.add("A) spreadsheet program, B) database program, C) word processor program, D) desktop publisher program");
	answers.add("A) spreadsheet program");
	questions.add("To edit data in an embedded Excel worksheet object in a Word document");
	options.add("A) use the excel menu bar and toolbars inside the word application, B) edit the hyperlink, C) edit the data in a excel source application, D) use the word menu bar and toolbars");
	answers.add("A) use the excel menu bar and toolbars inside the word application");
	questions.add("Which function will you use to enter current time in a worksheet cell?");
	options.add("A) =today(), B) =now(), C) =time(), D) =currentTime()");
	answers.add("B) =now()");
	questions.add("You can open the highlight changes dialog box by choosing track changes from the _____ menu");
	options.add("A) edit, B) insert, C) format, D) tools");
	answers.add("D) tools");
	questions.add("What term describes a background that appears as a grainy, non smooth surface");
	options.add("A) gradient, B) pattern, C) solid, D) texture");
	answers.add("A) gradient");
	questions.add("Which of the following is correct order of precedence in a formula calculation?");
	options.add("A) multiplication and division, exponential positive and negative value, B) multiplication and division, positive and negative values, addition and subtraction, C) addition and subtraction, positive and negative values, exponentiation, D) none of them");
	answers.add("D) none of them");
	questions.add("When you use the fill effects in the format data series dialog box, you cannot");
	options.add("A) rotate text on the chart, B) select a fore ground color, C) select a pattern, D) select a background color");
	answers.add("A) rotate text on the chart");
	questions.add("You can add an image to a template by clicking the insert picture from file button on the toolbar");
	options.add("A) standard, B) formatting, C) drawing, D) picture");
	answers.add("D) picture");
	questions.add("Status indicators are located on the");
	options.add("A) vertical scroll bar, B) horizontal scroll bar, C) formula bar, D) formatting toolbar");
	answers.add("C) formula bar");
	questions.add("Rounding errors can occur");
	options.add("A) when you use multiplication, division or exponentiation in a formula, B) when you use addition and subtraction in a formula, C) because excel uses hidden decimal places in computation, D) when you show the results of formulas with different decimal places than the calculated results");
	answers.add("A) when you use multiplication, division or exponentiation in a formula");
	questions.add("Special category of Number tab in format cells dialog box can be used to apply formats like");
	options.add("A) Zip code, B) phone number, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following is not a worksheet design criterion?");
	options.add("A) efficiency, B) auditability, C) description, D) clarity");
	answers.add("C) description");
	questions.add("Excel is a");
	options.add("A) graphic program, B) word processor, C) a spreadsheet, D) none of them");
	answers.add("C) a spreadsheet");
	questions.add("A function inside another function is called _________ function");
	options.add("A) nested, B) round, C) sum, D) text");
	answers.add("A) nested");
	questions.add("Paper spreadsheets can have all the same advantages as an electronic spreadsheet except which of the following?");
	options.add("A) rows and columns, B) headings, C) speed, D) none of them");
	answers.add("C) speed");
	questions.add("To drag a selected range of data to another worksheet in the same workbook, use the");
	options.add("A) tab key, B) Alt key, C) shift key, D) Ctrl key");
	answers.add("D) Ctrl key");
	questions.add("You can open the scenario manager dialog box by choosing scenarios from the ______ menu");
	options.add("A) view, B) insert, C) format, D) tools");
	answers.add("D) tools");
	questions.add("Merge cells option can be applied from");
	options.add("A) format cells dialog box alignment tab, B) formatting toolbar, C) both a and b, D) none of them");
	answers.add("A) format cells dialog box alignment tab");
	questions.add("To copy cell contents using drag and drop, press the");
	options.add("A) end key, B) shift key, C) Esc key, D) none of them");
	answers.add("D) none of them");
	questions.add("To create an inactive Pivot Table for the web, you use a Microsoft office web component called");
	options.add("A) HTML, B) Pivot Table Field List, C) Pivot Table List, D) Pivot Table Report");
	answers.add("D) Pivot Table Report");
	questions.add("How should you print a selected area of a worksheet, if you'll want to print a different area next time?");
	options.add("A) on the file menu, point to print area and then click set print area, B) on the file menu, click print, and then click selection under print what, C) on the view menu, click custom views, then click add, D) all of them");
	answers.add("B) on the file menu, click print, and then click selection under print what");
	questions.add("Which of the following is not a basic step in creating a worksheet?");
	options.add("A) save the workbook, B) modify the worksheet, C) enter text and data, D) copy the worksheet");
	answers.add("D) copy the worksheet");
	questions.add("When creating a vertical reak");
	options.add("A) the active cell must be A1, B) the active cell can be anywhere in the worksheet, C) the active cell must be in row 1, D) the active cell must be in column A");
	answers.add("C) the active cell must be in row 1");
	questions.add("You can open the Sort dialog box by choosing Sort from the _____ menu");
	options.add("A) view, B) format, C) tools, D) data");
	answers.add("D) data");
	questions.add("You can copy data or formulas");
	options.add("A) with the copy, paste and cut commands on the edit menu, B) with commands on a shortcut menu, C) with buttons on the standard toolbar, D) all of them");
	answers.add("D) all of them");
	questions.add("Pre-made sheet formats like simple, classic, accounting, colorful etC. can be applied from");
	options.add("A) all of them, B) from format >> cells, C) from format >> auto format, D) from table >> auto format");
	answers.add("C) from format >> auto format");
	questions.add("If you press _______ the cell accepts your typing as its contents");
	options.add("A) Enter, B) Ctrl+Enter, C) TAB, D) Insert");
	answers.add("A) Enter");
	questions.add("What function displays row data in column or column data in a row?");
	options.add("A) hyperlink, B) index, C) transpose, D) rows");
	answers.add("C) transpose");
	questions.add("Your German supplier still invoices for parts in deutsche marks. How can you have Excel convert those sums to Euros?");
	options.add("A) on the insert menu, click symbol and from the currency symbols subset, select the Euro sign, B) on the tools menu, click add-ins and select the Euro currency tools check box, C) apply a selected background color, D) all of them");
	answers.add("B) on the tools menu, click add-ins and select the Euro currency tools check box");
	questions.add("What's quick way to extend these numbers to a longer sequence, for instance 1 through 20?");
	options.add("A) select both cells and then drag the fill handle over the range you want for instance 18 more rows, B) select the range you want, include both cells, point to fill on the Edit menu, and then click down, C) both a and b, D) none of them");
	answers.add("A) select both cells and then drag the fill handle over the range you want for instance 18 more rows");
	questions.add("To activate the previous cell in a pre-selected range, press");
	options.add("A) the Alt key, B) the Tab key, C) the Enter key, D) none of them");
	answers.add("D) none of them");
	questions.add("When working in the reak preview, you can");
	options.add("A) view exactly where each reak occurs, B) add or remove reaks, C) change the print area, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following format you can decide to apply or not in auto format dialog box?");
	options.add("A) number format, B) border format, C) font format, D) all of them");
	answers.add("D) all of them");
	questions.add("The autofill feature");
	options.add("A) extends a sequential series of data, B) automatically adds a range of cell values, C) applies a boarder around selected cells, D) none of them");
	answers.add("A) extends a sequential series of data");
	questions.add("When you insert an Excel file into a Word document, the data are");
	options.add("A) hyperlinked, B) placed in a word table, C) linked, D) embedded");
	answers.add("B) placed in a word table");
	questions.add("Which function calculates your monthly mortgage payment?");
	options.add("A) PMT (payments), B) NPER (number of periods), C) PV (present value), D) all of them");
	answers.add("A) PMT (payments)");
	questions.add("To insert three columns between columns D and E you would");
	options.add("A) select column D, B) select column E, C) both a and b, D) none of them");
	answers.add("B) select column E");
	questions.add("When the formula bar is activated, you can see");
	options.add("A) the edit formula button, B) the cancel button, C) the enter button, D) all of them");
	answers.add("D) all of them");
	questions.add("How can you remove borders applied in cells?");
	options.add("A) choose none on border tab of format cells, B) open the list on border tool in formatting toolbar then choose first tool, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("What is the keyboard shortcut for creating a chart from the selected cells?");
	options.add("A) F3, B) F5, C) F7, D) F11");
	answers.add("D) F11");
	questions.add("Except for the _____ function, a formula with a logical function shows the word (TRUE) or (FALSE) as a result");
	options.add("A) IF, B) AND, C) OR, D) NOT");
	answers.add("A) IF");
	questions.add("If you are working in English(US), Chinese or Japanese, Excel 2002 can speak data as you enter it, to help you verify accuracy. How do you activate this feature?");
	options.add("A) point to speech on the tools menu, and then click show text to speech toolbar, B) click validation on the data menu, C) point to speech on the tools menu and then click speech recognition, D) all of them");
	answers.add("A) point to speech on the tools menu, and then click show text to speech toolbar");
	questions.add("To center worksheet titles across a range of cell ,you must");
	options.add("A) select the cells containing the title text and use the fill handle to center the text across a range of cells, B) widen the columns, C) both a and b, D) none of them");
	answers.add("A) select the cells containing the title text and use the fill handle to center the text across a range of cells");
	questions.add("In a worksheet you can select");
	options.add("A) the entire worksheet, B) rows, C) columns, D) all of them");
	answers.add("D) all of them");
	questions.add("Where can you set the shedding color for a range of cells in excel?");
	options.add("A) choose required color from patterns tab of format cells dialog box, B) choose required color on fill color tool in formatting toolbar, C) choose required color on fill color tool in drawing toolbar, D) all of them");
	answers.add("D) all of them");
	questions.add("Which file format can be added to a PowerPoint show?");
	options.add("A) .jpg, B) .give, C) .wav, D) all of them");
	answers.add("D) all of them");
	questions.add("You can edit an embedded organization chart object by");
	options.add("A) clicking edit object, B) double clicking the organization chart object, C) right clicking the chart object, then clicking edit MS-Organization Chart object, D) both b and c");
	answers.add("D) both b and c");
	questions.add("Which option can be used to set custom timings for slides in a presentation?");
	options.add("A) slider timings, B) slider timer, C) rehearsal, D) slide show setup");
	answers.add("C) rehearsal");
	questions.add("_______ controls all the main slide control tasks for your presentation");
	options.add("A) task pane, B) task bar, C) control panel, D) none of them");
	answers.add("A) task pane");
	questions.add("Which menu provides you options like animation scheme, custom animation, slide transition?");
	options.add("A) insert menu, B) format menu, C) tools menu, D) slide show menu");
	answers.add("D) slide show menu");
	questions.add("Which of the following statements is true?");
	options.add("A) you can insert text boxes from drawing toolbar in PowerPoint, B) you cannot insert text boxes from drawing toolbar in PowerPoint, C) text boxes are provided when you choose a layout and can't be inserted afterwards, D) none of them");
	answers.add("A) you can insert text boxes from drawing toolbar in PowerPoint");
	questions.add("Which of the following is the default etup orientation of slide in PowerPoint?");
	options.add("A) vertical, B) landscape, C) portrait, D) none of them");
	answers.add("B) landscape");
	questions.add("In Microsoft PowerPoint two kinds of sound affects files that can be added to the presentation are");
	options.add("A) .wav files and .mid files, B) .wav files and .gif files, C) .wav files and .jpg files, D) .jpg files and .gif files");
	answers.add("A) .wav files and .mid files");
	questions.add("What is the term used when you press and hold the left mouse key and more the mouse around the slide?");
	options.add("A) highlighting, B) dragging, C) selecting, D) moving");
	answers.add("B) dragging");
	questions.add("Which of the following will not advance the slides in a slide show view?");
	options.add("A) the Esc key, B) the space bar, C) the Enter key, D) the mouse button");
	answers.add("A) the Esc key");
	questions.add("Which of the following cannot be toggled from View >> Toolbars?");
	options.add("A) control toolbox, B) slides, C) revisions, D) reviewing");
	answers.add("B) slides");
	questions.add("How many steps are there between start and finish in AutoContent wizard?");
	options.add("A) 3, B) 4, C) 5, D) 6");
	answers.add("A) 3");
	questions.add("When you delete a text box object from a slide in PowerPoint presentation");
	options.add("A) the object is deleted but text box and the text inside is left on the slide, B) the text box is deleted and the text is pasted on the slide, C) the text box and text both are deleted, D) none of them");
	answers.add("C) the text box and text both are deleted");
	questions.add("Want a PowerPoint photo album slide show to play continuously?");
	options.add("A) use random slide transitions, B) launch an online broadcast, C) loop continuously, D) all of them");
	answers.add("A) use random slide transitions");
	questions.add("Material consisting of text and numbers is best presented as");
	options.add("A) a table slide, B) a bullet slide, C) a title slide, D) all of them");
	answers.add("A) a table slide");
	questions.add("Which of the following toolbars provide different options in various master views?");
	options.add("A) common tasks toolbar, B) drawing toolbar, C) formatting toolbar, D) standard toolbar");
	answers.add("A) common tasks toolbar");
	questions.add("To import text from a word document that uses headings into a PowerPoint presentation:");
	options.add("A) this can not be done in PowerPoint, B) click insert, slides from outline, C) click import, word document headings, D) click file. New, presentation from word headings");
	answers.add("B) click insert, slides from outline");
	questions.add("Which of the following pane is not available in Task Pane?");
	options.add("A) getting started, B) clip art, C) word art, D) search result");
	answers.add("C) word art");
	questions.add("Which short cut key inserts a new slide in current presentation?");
	options.add("A) Ctrl+N, B) Ctrl+M, C) Ctrl+S, D) all of them");
	answers.add("B) Ctrl+M");
	questions.add("Which of the following font effect is not available in PowerPoint Font dialog box?");
	options.add("A) underline, B) shadow, C) emboss, D) strikethrough");
	answers.add("D) strikethrough");
	questions.add("What is defined by the handout master?");
	options.add("A) slide formatting, B) layout of audience handout notes, C) handout content formatting for Microsoft word export, D) all of them");
	answers.add("B) layout of audience handout notes");
	questions.add("What is motion path?");
	options.add("A) a type of animation entrance effect, B) a method of advancing slides, C) a method of moving items on a slide, D) all of them");
	answers.add("C) a method of moving items on a slide");
	questions.add("How can you create a uniform appearance by adding a background image to all slides?");
	options.add("A) create a template, B) edit the slide master, C) use the autocorrect wizard, D) all of them");
	answers.add("B) edit the slide master");
	questions.add("Format painter");
	options.add("A) to paint pretty pictures on your slides, B) to copy formatting from one object or piece of text and then apply it elsewhere, C) to change the background color of you slides, D) to paint pretty pictures on background slides");
	answers.add("B) to copy formatting from one object or piece of text and then apply it elsewhere");
	questions.add("Which of the following pane is not available in Task Pane?");
	options.add("A) slide design, B) master slide, C) slide layout, D) slide transition");
	answers.add("B) master slide");
	questions.add("What happens if you select first and second slide and then click on new slide button on toolbar?");
	options.add("A) a new slide is inserted as first slide in presentation, B) a new slide is inserted as second slide in presentation, C) a new slide is inserted as third slide in presentation, D) none of them");
	answers.add("C) a new slide is inserted as third slide in presentation");
	questions.add("What happens if you edited an image inserted in PowerPoint?");
	options.add("A) the original file that was inserted is not changed, B) the original file that was inserted is changed, C) the original file is changed when you save presentation, D) none of them");
	answers.add("A) the original file that was inserted is not changed");
	questions.add("Which of the following tool enables you to add text to a slide without using the standard placeholders?");
	options.add("A) text tool box, B) line tool, C) drawing tool, D) auto shapes tool");
	answers.add("A) text tool box");
	questions.add("To select all of the boxes of an organization chart");
	options.add("A) clicking and edit and select all, B) right click the chart background and then click select all, C) press and hold the Shift key and click each box, D) all of them");
	answers.add("D) all of them");
	questions.add("What is a slide-title master pair?");
	options.add("A) the title area and text area of a specific slide, B) a slide master and title master merged into a single slide, C) a slide master and title master for a specific design template, D) all of them");
	answers.add("C) a slide master and title master for a specific design template");
	questions.add("How do you create speaker note that show the slides, related notes and your company logo on each");
	options.add("A) edit the notes master and add your company logo, B) edit the slide master and insert your company logo and notes pane, C) edit the handout master to include your company logo and one slider per ith additional note space, D) all of them");
	answers.add("A) edit the notes master and add your company logo");
	questions.add("Slide show options available to the presenter includes all of the following except");
	options.add("A) transitions command, B) speaker notes command, C) meeting minder command, D) navigation commands");
	answers.add("A) transitions command");
	questions.add("A new presentation can be created from");
	options.add("A) blank presentation, B) from existing presentation, C) from design template, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following method can insert a new slide in current presentation?");
	options.add("A) right click on the slide panel and choose new slide, B) from insert menu choose new slide, C) click on new slide button on toolbar, D) all of them");
	answers.add("D) all of them");
	questions.add("If you select insert >> picture >> from file");
	options.add("A) you can insert pictures and clip arts, B) you can insert clipart only, C) you can insert pictures only, D) none of them");
	answers.add("C) you can insert pictures only");
	questions.add("In notes master view, how do you modify the font size of text for all the notes of a presentation?");
	options.add("A) modify the slide design, B) modify the notes master layout, C) modify the text within the body placeholder, D) all of them");
	answers.add("C) modify the text within the body placeholder");
	
    }



    public static void main(String[] args) {
        new Computer2_Quiz(name).setVisible(true); 
    }

}
