package secondListFrames;

import frame.Quiz;

public class Computer3_Quiz extends Quiz {
   
    public Computer3_Quiz(String name) {
        super(name);
        loadQuestions();
        System.out.println(questions.size());
        System.out.println(answers.size());
        System.out.println(options.size());
        setupQuiz();
        
    }

    private void setupQuiz() {
        shuffleIndices();
        selectTotalQuestions();
        setCurrentQuestion();
        setQuestionTextAndOptions();
    }

    @Override
    public void setQuestionTextAndOptions() {
        qno.setText("Question #: " + currentQno);
        question.setText(questions.get(currentQuestionIndex));
        opt1.setText(options.get(currentQuestionIndex).split(", ")[0]);
        opt2.setText(options.get(currentQuestionIndex).split(", ")[1]);
        opt3.setText(options.get(currentQuestionIndex).split(", ")[2]);
        opt4.setText(options.get(currentQuestionIndex).split(", ")[3]);
    }

    // 401 questions
    @Override
    public final void loadQuestions() {
     
        questions.add("Which of the following should you use if you want all the slide in the presentation to have the same (look)?");
	options.add("A) the slide layout option, B) add a slide option, C) outline view, D) a presentation design template");
	answers.add("D) a presentation design template");
	questions.add("One way to make a PowerPoint slide display animations is to");
	options.add("A) select the slide in normal view and click format animation, B) click the PowerPoint window and move it around vigorously with the mouse for a manual animation effect, C) select the slide in slide sorter view right click and choose preset animations from the shortcut menu, D) PowerPoint does not have an animation feature");
	answers.add("C) select the slide in slide sorter view, right click and choose preset animations from the shortcut menu");
	questions.add("Which of the following is an example for automatic text formatting");
	options.add("A) underlining hyperlink, B) adjusting extra space, C) replacing two -'s with an em hyphens, D) all of them");
	answers.add("D) all of them");
	questions.add("In slide layout panel how many layouts are available for text layout by default?");
	options.add("A) 4, B) 7, C) 12, D) none of them");
	answers.add("A) 4");
	questions.add("Which of the following is not a part of slide design?");
	options.add("A) design template, B) color scheme, C) animation scheme, D) slide layout");
	answers.add("D) slide layout");
	questions.add("The effect applied to display when slides changes in slide show view is");
	options.add("A) slide animation, B) custom animations, C) custom transition, D) slide transition");
	answers.add("D) slide transition");
	questions.add("Want your logo in the same position on every slide, automatically? Insert it on the");
	options.add("A) handout master, B) notes master, C) slide master, D) all of them");
	answers.add("C) slide master");
	questions.add("In the context of animations, what is a trigger?");
	options.add("A) an action button that advances to the next slide, B) an item on the slide that performs an action when clicked, C) the name of a motion path, D) all of them");
	answers.add("B) an item on the slide that performs an action when clicked");
	questions.add("Which of the following is not a way to cut ext?");
	options.add("A) select the text and press the delete button, B) select the text and select Edit, cut from the menu, C) select the text and click the cut button on the toolbar, D) select the text and press ctrl+X");
	answers.add("A) select the text and press the delete button");
	questions.add("Which of the following is not a way to create a new presentation?");
	options.add("A) using the scan-in slides feature, B) from scratch (create a blank presentation), C) using a template, D) using the auto content wizard");
	answers.add("A) using the scan-in slides feature");
	questions.add("which of the following statements is false?");
	options.add("A) if you choose to select from one of the pre-made slide layouts, you can change the positioning, B) if you choose to select from the pre-made slide layouts, you cannot delete the objects in the layout, C) blank slide is at the top of the 'Content Layouts' area in the Slide Layout Panel, D) all of them");
	answers.add("B) if you choose to select from the pre-made slide layouts, you cannot delete the objects in the layout");
	questions.add("What is the best way to create another copy of a slide?");
	options.add("A) click the slide then press Ctrl+A and paste in new slide, B) from insert menu choose duplicate slide, C) redo everything on a new slide that you had done on previous slide, D) none of them");
	answers.add("B) from insert menu choose duplicate slide");
	questions.add("To start slide show of a presentation");
	options.add("A) hit F5 key, B) from slide show menu choose view show option, C) from slide show menu choose rehearse timing, D) both a and b");
	answers.add("D) both a and b");
	questions.add("Which of the following views is the best view to use when setting transition effects for all slides in a");
	options.add("A) slide sorter view, B) notes iew, C) slide view, D) outline view");
	answers.add("A) slide sorter view");
	questions.add("If you have a PowerPoint show you related and want to send using email to another teacher you can add the show to your email message as a(an)");
	options.add("A) inclusion, B) attachment, C) reply, D) forward");
	answers.add("B) attachment");
	questions.add("Which types of fonts are best suitable for titles and headlines");
	options.add("A) serif fonts, B) sans serif fonts, C) text fonts, D) picture fonts");
	answers.add("B) sans serif fonts");
	questions.add("The quickest way to create a PowerPoint presentation is to use the");
	options.add("A) word for windows templates, B) auto creation wizard, C) auto content wizard, D) presentation wizard");
	answers.add("C) auto content wizard");
	questions.add("What lets you to create new presentation by selecting ready-made font color and graphics effects?");
	options.add("A) presentation template, B) master slide, C) design template, D) animation scheme");
	answers.add("C) design template");
	questions.add("From which menu you can access picture, test box, chart etc.?");
	options.add("A) file, B) edit, C) insert, D) view");
	answers.add("C) insert");
	questions.add("What is the term used when a clip art image changes the direction of faces?");
	options.add("A) group, B) flip, C) rotate, D) all of them");
	answers.add("C) rotate");
	questions.add("Objects on the slide that hold text are called");
	options.add("A) placeholders, B) object holders, C) auto layouts, D) text holders");
	answers.add("A) placeholders");
	questions.add("In order to edit a chart, you can");
	options.add("A) triple click the chart object, B) click and drag the chart object, C) double click the chart object, D) click the chart object");
	answers.add("C) double click the chart object");
	questions.add("Which type of font is best suitable for large amount of text?");
	options.add("A) serif fonts, B) sans serif fonts, C) text fonts, D) picture fonts");
	answers.add("A) serif fonts");
	questions.add("Which of the following can you format using buttons on the formatting toolbar?");
	options.add("A) your hand drive, B) format painting, C) font color, D) underlining");
	answers.add("D) underlining");
	questions.add("Which command will you use in PowerPoint if you need to change the color of different objects without changing content?");
	options.add("A) design template, B) color scheme, C) font color, D) object color");
	answers.add("B) color scheme");
	questions.add("If you want to insert some slides from other presentation into current one choose");
	options.add("A) from insert menu choose slides from files, B) from insert menu choose slides from presentation, C) from insert menu choose slides, D) none of them");
	answers.add("A) from insert menu choose slides from files");
	questions.add("The slide that is used to introduce a topic and set the tone for the presentation is called the");
	options.add("A) table slide, B) graph slide, C) bullet slide, D) title slide");
	answers.add("D) title slide");
	questions.add("Which of the following provides a means of printing out feature notes with a miniature slide on a printed");
	options.add("A) slide with animation, B) outline view, C) notes 204, D) audience handout");
	answers.add("D) audience handout");
	questions.add("To exit the PowerPoint");
	options.add("A) click the application minimize button, B) click the document close button, C) double click the applications control menu icon, D) double click the document control menu icon");
	answers.add("C) double click the applications control menu icon");
	questions.add("To give a PowerPoint presentation to a large audience, you");
	options.add("A) set up your computer in a large auditorium and click large auditorium Ok, B) click the slide you wish the audience to see in normal view then click the next slide and so on, C) choose either view slide show or slide show view show, D) click slide show Ok");
	answers.add("C) choose either view, slide show or slide show, view show");
	questions.add("Which tab is not available on left panel when you open a presentation?");
	options.add("A) outline, B) slides, C) notes, D) all of them");
	answers.add("C) notes");
	questions.add("What PowerPoint feature will you use to play motion effect to different objects if a slide?");
	options.add("A) slide transition, B) slide design, C) animation objects, D) animation scheme");
	answers.add("D) animation scheme");
	questions.add("What are the three options available in insert >> picture menu?");
	options.add("A) clipart, pictures, shapes, B) clipart, from file, shapes, C) clipart, from files, auto shapes, D) clipart, pictures, auto shapes");
	answers.add("C) clipart, from files, auto shapes");
	questions.add("Which of the following features should you use when typing in the notes text box?");
	options.add("A) slide show, B) insert, C) slide maser, D) zoom");
	answers.add("D) zoom");
	questions.add("Which command brings you to the first slide in your presentation?");
	options.add("A) next slide button, B) p, C) Ctrl + Home, D) Ctrl + End");
	answers.add("C) Ctrl + Home");
	questions.add("To preview a motion path effect using the custom animation task pane, you should");
	options.add("A) click the play button, B) click the show effect button, C) double click the motion path, D) all of them");
	answers.add("A) click the play button");
	questions.add("Which of the following can you use to add times to the slides in a presentation?");
	options.add("A) slide show menu, B) rehearse timing button, C) slide transition button, D) all of them");
	answers.add("B) rehearse timing button");
	questions.add("Which of the following statements is not true?");
	options.add("A) you can type text directly into PowerPoint slide but typing in text box is more convenient, B) from insert menu choose picture and then from file to insert your images into slides, C) you can display a PowerPoint presentation in normal, slide sorter or slide show view, D) you can show or hide task pane from view >> toolbars");
	answers.add("A) you can type text directly into PowerPoint slide but typing in text box is more convenient");
	questions.add("What feature will you use to apply motion effects in between a slide exits and another enters?");
	options.add("A) slide transition, B) slide design, C) animation objects, D) animation scheme");
	answers.add("A) slide transition");
	questions.add("To insert slide numbers");
	options.add("A) insert a text box and select insert >> umber, B) insert a textbox and select insert >> number >> umber, C) choose insert >> slide number, D) insert a new text box and select insert >> slide number");
	answers.add("D) insert a new text box and select insert >> slide number");
	questions.add("Which option allows you to select line, curve, freeform or scribble tools?");
	options.add("A) create effect, B) insert motion path, C) draw custom path, D) all of them");
	answers.add("C) draw custom path");
	questions.add("In normal view, how can you quickly change to handout master view?");
	options.add("A) click the outline tab and select handout master view, B) press the shift key and lick the handout master view button, C) on the view menu, click slide sorter, and click handouts, D) all of them");
	answers.add("B) press the shift key and lick the handout master view button");
	questions.add("You can show the shortcut menu during the slideshow by");
	options.add("A) clicking the shortcut button on the formatting toolbar, B) right clicking the current slide, C) clicking an icon on the current slide, D) both a and b");
	answers.add("B) right clicking the current slide");
	questions.add("You can create a new presentation by completing all of the following except");
	options.add("A) clicking the new button on the standard toolbar, B) clicking file, new, C) clicking file open, D) pressing Ctrl+N");
	answers.add("C) clicking file open");
	questions.add("Which of the following is not one of PowerPoint's views?");
	options.add("A) slide show view, B) slide view, C) presentation view, D) outline view");
	answers.add("C) presentation view");
	questions.add("To start Microsoft PowerPoint application");
	options.add("A) click on start >> programs >> all programs >> Microsoft PowerPoint, B) hit Ctrl + R then type ppoint.exe and Enter, C) click start >> run then type PowerPoint then press Enter, D) all of them");
	answers.add("C) click start >> run then type PowerPoint then press Enter");
	questions.add("The selected design template can be applied");
	options.add("A) to current slide only, B) to all the slides, C) to all the new presentation you create, D) all of them");
	answers.add("D) all of them");
	questions.add("In a PowerPoint presentation");
	options.add("A) sound clips can be inserted but not movie clips, B) movie clips can be inserted but not sound clips, C) both cannot be inserted, D) both can be inserted");
	answers.add("D) both can be inserted");
	questions.add("Which of the following should be used when you want to add a slide to an existing presentation?");
	options.add("A) file, add a new slide, B) insert, new slide, C) file open, D) file, new");
	answers.add("B) insert, new slide");
	questions.add("How can you quickly reinstate a deleted footer placeholder in master view?");
	options.add("A) create a new slide master, B) re-apply the footer placeholder, C) re-apply the slide layout, D) all of them");
	answers.add("B) re-apply the footer placeholder");
	questions.add("Auto clipart is a feature that");
	options.add("A) automatically places clipart in your presentation, B) scans you presentation for incorrect spelling in your words on each slide, C) scans your presentation for incorrect spelling in word arts objects, D) all of them");
	answers.add("D) all of them");
	questions.add("You can embed a MS-Organization Chart in a slide by");
	options.add("A) clicking the subject command on the edit menu, B) clicking the object command on the edit menu, C) clicking the insert new slide button the standard toolbar, then double click the organisation chart button on the formatting toolbar, D) clicking the MS-Organization Chart button on the standard toolbar");
	answers.add("B) clicking the object command on the edit menu");
	questions.add("Which PowerPoint view works best for adding slide transition?");
	options.add("A) slide show view, B) slide sorter view, C) slide view, D) notes view");
	answers.add("B) slide sorter view");
	questions.add("Which of the following section does not exist in a slide layout?");
	options.add("A) titles, B) lists, C) charts, D) animations");
	answers.add("D) animations");
	questions.add("The difference between Slide Design and Auto Content Wizard is");
	options.add("A) both are same, B) AutoContent wizard is just the wizard version of Slide Design, C) Slide Design does not provide sample content but Auto Content wizard provides sample content too, D) Slide Design asks your choice in steps but Auto Content wizard does not let you make choices");
	answers.add("C) Slide Design does not provide sample content but Auto Content wizard provides sample content too");
	questions.add("To insert a hyperlink in a slide");
	options.add("A) choose insert >> hyperlink, B) press Ctrl + K, C) hyperlinks can't be inserted in slides, D) both a and b");
	answers.add("D) both a and b");
	questions.add("The size of the organization chart object");
	options.add("A) is determined by the presentation design and can not be changed, B) is determined by the presentation design but can be changed in PowerPoint, C) is dependent on the amount of text within the organization chart, D) both b and c");
	answers.add("D) both b and c");
	questions.add("Which of the following can you use to add times to the slides in a presentation?");
	options.add("A) slide show menu, B) rehearse timing button, C) slide transition button, D) all of them");
	answers.add("B) rehearse timing button");
	questions.add("To select one hyperlink after another during a slide presentation, what do you press?");
	options.add("A) Tab, B) Ctrl+K, C) Ctrl+h, D) all of them");
	answers.add("A) Tab");
	questions.add("Which of the following views is the best view to use when setting transition effects for all slides in a presentation");
	options.add("A) slide sorter view, B) notes iew, C) slide view, D) outline view");
	answers.add("A) slide sorter view");
	questions.add("PowerPoint presentations are widely used as");
	options.add("A) not outlines for teachers, B) project presentations by students, C) communication of planning, D) all of them");
	answers.add("D) all of them");
	questions.add("In which menu can you find features like slide design, slide layout etc.?");
	options.add("A) insert menu, B) format menu, C) tools menu, D) slide show menu");
	answers.add("B) format menu");
	questions.add("List box and text box");
	options.add("A) are some other than that in a list box the bullets are enabled, B) are different list boxes are used to present lists and can't be created with text boxes, C) both a and b, D) none of them");
	answers.add("A) are some other than that in a list box the bullets are enabled");
	questions.add("Special effects used to introduce slides in a presentation are called");
	options.add("A) effects, B) custom animations, C) transitions, D) present animations");
	answers.add("C) transitions");
	questions.add("What are the different views to display a table");
	options.add("A) datasheet view, B) design view, C) pivot table & pivot chart view, D) all of them");
	answers.add("D) all of them");
	questions.add("The database language that allows you to access or maintain data in a database");
	options.add("A) DCL, B) DML, C) DDL, D) none of them");
	answers.add("A) DCL");
	questions.add("In table design view, which key can be used to switch between the field names and properties panels?");
	options.add("A) F3, B) F4, C) F5, D) F6");
	answers.add("D) F6");
	questions.add("Queries in Access can be used as");
	options.add("A) view change and analyze data in different ways, B) source of records for forms and reports, C) only a and b, D) none of them");
	answers.add("C) only a and b");
	questions.add("Referential integrity means");
	options.add("A) do not enter a value in the foreign key of a child table if that value does not exist in the primary key of the parent table, B) do not enter a value in the primary key of a child table if that value does not exist in the primary key of the parent table, C) do not enter a value in the foreign key of a parent table if that value does not exist in the primary key of the child table, D) all of them");
	answers.add("A) do not enter a value in the foreign key of a child table if that value does not exist in the primary key of the parent table");
	questions.add("To duplicate a controls formatting you can use");
	options.add("A) manager, B) wizard, C) painter, D) control");
	answers.add("C) painter");
	questions.add("It is a sign or symbol that specifies, operator, and values that produce a result");
	options.add("A) operator, B) query, C) expression, D) none of them");
	answers.add("A) operator");
	questions.add("Which of the following creates a drop down list of values to choose from?");
	options.add("A) ole object, B) hyperlink, C) memo, D) lookup wizard");
	answers.add("D) lookup wizard");
	questions.add("What is the maximum length a text field can be?");
	options.add("A) 120, B) 255, C) 265, D) 75");
	answers.add("B) 255");
	questions.add("In table design view what are the first columns of buttons used for");
	options.add("A) indicate primary key, B) indicate current row, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("To create queries in Access");
	options.add("A) you can drag and drop fields on query builders, B) you can type the SL command in SL view, C) you can use query wizard or design view, D) all of them");
	answers.add("D) all of them");
	questions.add("Cascade delete option");
	options.add("A) is used to delete all the records of all tables in a database, B) will repeat the recent delete operation to all the records of current table, C) is available in edit relationship dialog box which makes sure that all the related records will be deleted automatically when the record from parent table is deleted, D) none of them");
	answers.add("C) is available in edit relationship dialog box which makes sure that all the related records will be deleted automatically when the record from parent table is deleted");
	questions.add("The ______ button on the tool box display data from a related table");
	options.add("A) sub from sub report, B) relationships, C) select objects, D) more controls");
	answers.add("A) sub from sub report");
	questions.add("Which of the following database object is created first before any other created?");
	options.add("A) table, B) form, C) report, D) query");
	answers.add("A) table");
	questions.add("The command center of access file that appears when you crate or open the MS Access database file");
	options.add("A) database window, B) user window, C) design view window, D) switchboard");
	answers.add("A) database window");
	questions.add("Which of the following is not a database object?");
	options.add("A) tables, B) queries, C) relationships, D) reports");
	answers.add("C) relationships");
	questions.add("The default and maximum size of text field in access");
	options.add("A) 50 and 255 characters, B) 8 and 1 GB, C) 266 characters & 64000 characters");
	answers.add("A) 50 and 255 characters");
	questions.add("Query design window has two parts. The upper part shows");
	options.add("A) name of fields, field type and size, B) tables with fields and relationships between tables, C) criteria, D) sorting check boxes");
	answers.add("B) tables with fields and relationships between tables");
	questions.add("Cascade update option");
	options.add("A) means do not change the value in the primary key field if that record has related records in another table, B) means change all the related records in child tables if the record in parent table is changed, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("You can set a controls border type to make the border invisible");
	options.add("A) transparent, B) invisible, C) do not display, D) no border");
	answers.add("C) do not display");
	questions.add("This type of database contains multiple tables that are connected to produce combined output from all tables");
	options.add("A) bound, B) linked, C) relational, D) joined");
	answers.add("C) relational");
	questions.add("When creating an input mask this character does not require an entry, but if an entry is made it must be");
	options.add("A) ?, B) !, C) #, D) '\'");
	answers.add("A) ?");
	questions.add("The third stage in designing a database is when we analyze out tables more closely and create a _______ between tables");
	options.add("A) relationship, B) join, C) query, D) none of them");
	answers.add("A) relationship");
	questions.add("A ______ enables you to view data from a table based on a specific criterion");
	options.add("A) form, B) query, C) macro, D) report");
	answers.add("B) query");
	questions.add("The size of yes no field is always");
	options.add("A) 1 bit, B) 1 byte, C) 1 character, D) 1 GB");
	answers.add("A) 1 bit");
	questions.add("What does the show check box in query design window indicate");
	options.add("A) it indicated whether the field is to be used or not, B) it indicated whether the field is to be displayed in query result or not, C) it indicates whether the field names to be displayed in query result or not, D) none of them");
	answers.add("B) it indicated whether the field is to be displayed in query result or not");
	questions.add("We can remove a relationship defined between two tables by");
	options.add("A) from edit menu choose delete relationship, B) select the relationship line and press delete, C) choose delete option from relationship menu, D) all of them");
	answers.add("B) select the relationship line and press delete");
	questions.add("A _____ name must be unique within a database");
	options.add("A) table, B) field, C) record, D) character");
	answers.add("A) table");
	questions.add("The 'Filter by Selection' allows you to filter those records");
	options.add("A) that match the selected field, B) that match the criteria specified, C) that meet any of several criteria specified, D) all of them");
	answers.add("A) that match the selected field");
	questions.add("In a database table, the category of information is called");
	options.add("A) tuple, B) field, C) record, D) all of them");
	answers.add("B) field");
	questions.add("What are the columns in a Microsoft access table called?");
	options.add("A) rows, B) records, C) fields, D) columns");
	answers.add("C) fields");
	questions.add("Which of the following is not a field type in access");
	options.add("A) memo, B) hyperlink, C) ole object, D) lookup wizard");
	answers.add("D) lookup wizard");
	questions.add("What is a form in MS Access");
	options.add("A) it is a printed here users will write their data to fill it up, B) it is an input screen designed to make the viewing and entering data easier, C) this is an important part of database used by analysts to draw conclusions, D) all of them");
	answers.add("B) it is an input screen designed to make the viewing and entering data easier");
	questions.add("If you need to edit a relationship");
	options.add("A) right click the relationship line and choose edit relationship, B) double click the relationship line, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("The expression builder is an access tool that controls an expression ______ for entering an expression");
	options.add("A) table, B) box, C) cell, D) palette");
	answers.add("B) box");
	questions.add("The operation of checking input data against specified criteria is known as");
	options.add("A) data verification, B) data validation, C) cross check, D) data control");
	answers.add("B) data validation");
	questions.add("In Access, this displays the results of a calculation in a query");
	options.add("A) lookup field, B) calculated field, C) source field, D) child field");
	answers.add("B) calculated field");
	questions.add("This key uniquely identifies each record");
	options.add("A) primary key, B) key record, C) unique key, D) field name");
	answers.add("A) primary key");
	questions.add("Which of the following is not a type of Microsoft access database object?");
	options.add("A) table, B) form, C) worksheets, D) modules");
	answers.add("C) worksheets");
	questions.add("The size of a field with number data type can not be");
	options.add("A) 2, B) 4, C) 8, D) 16");
	answers.add("D) 16");
	questions.add("Which of the following statements is true?");
	options.add("A) reports can be used to retrieve data from tables and calculate, B) queries can be printed in well formatted manner and presented as the information, C) queries can include calculated fields that do not exist in table, D) reports and forms are similar but forms are used to print but reports to display on screen only");
	answers.add("C) queries can include calculated fields that do not exist in table");
	questions.add("If you write criteria values vertically (one in a row) it will mean");
	options.add("A) OR conditions, B) AND conditions, C) NOT conditions, D) none of them");
	answers.add("A) OR conditions");
	questions.add("This option allows you to build a new table by entering data directly into the datasheet");
	options.add("A) datasheet view, B) design view, C) link table, D) none of them");
	answers.add("A) datasheet view");
	questions.add("Some rules are set in databases to check and permit only correct values. What is this feature called?");
	options.add("A) data verification, B) auditing, C) data filtering, D) data validation");
	answers.add("D) data validation");
	questions.add("In Access, this operation copies a backup file from the storage medium back onto the computer");
	options.add("A) recreate, B) restore, C) copy, D) structure");
	answers.add("B) restore");
	questions.add("It is an association established between common");
	options.add("A) line, B) relationship, C) primary key, D) records");
	answers.add("B) relationship");
	questions.add("Which of the following database object hold data?");
	options.add("A) forms, B) reports, C) queries, D) tables");
	answers.add("D) tables");
	questions.add("Which field type will you select when creating a new table if you require to enter long text in that field?");
	options.add("A) text, B) memo, C) currency, D) hyperlink");
	answers.add("B) memo");
	questions.add("Two tables can be linked with relationship so that the data integrity can be enforceD. Where can you find relationship command?");
	options.add("A) tools menu, B) file menu, C) view menu, D) database menu");
	answers.add("A) tools menu");
	questions.add("To achieve AND effect when you are entering criteria in a query design window");
	options.add("A) write criteria values vertically one in a row, B) write criteria values horizontally, C) write criteria values in same field separated with AND, D) write criteria values in same field separated with &");
	answers.add("B) write criteria values horizontally");
	questions.add("The key uniquely identifies each record in a table");
	options.add("A) primary key, B) key record, C) field name, D) all of them");
	answers.add("A) primary key");
	questions.add("Database access levels are specified so as to define who can access what in a database. It is identified");
	options.add("A) user ID, B) password, C) status, D) none of them");
	answers.add("A) user ID");
	questions.add("If you make an invalid entry in the input mask wizard dialog box, this will display to advise you that the entry is not correct");
	options.add("A) text error, B) validation error, C) literal error, D) entry error");
	answers.add("B) validation error");
	questions.add("This is the stage in database design where one gathers and list all the necessary fields for the database project");
	options.add("A) data definition, B) data refinement, C) establishing relationship, D) none of them");
	answers.add("A) data definition");
	questions.add("Which of the following store command to retrieve data from database?");
	options.add("A) forms, B) reports, C) queries, D) tables");
	answers.add("C) queries");
	questions.add("Which field type can store photos?");
	options.add("A) hyperlink, B) ole, C) both a and b, D) none of them");
	answers.add("B) ole");
	questions.add("Which of the following is not a type of relationship that can be applied in Access database?");
	options.add("A) one to one, B) one to many, C) many to many, D) all of them");
	answers.add("D) all of them");
	questions.add("A search value can be exact value it can be");
	options.add("A) logical operator, B) relationship, C) wild card character, D) comparison operation");
	answers.add("C) wild card character");
	questions.add("This data type allows alphanumeric characters and special symbols");
	options.add("A) text, B) memo, C) auto number, D) none of them");
	answers.add("A) text");
	questions.add("What it is called to present information in a particular order based on numeric or alphabetical value?");
	options.add("A) sorting, B) searching, C) arranging, D) cropping");
	answers.add("A) sorting");
	questions.add("A database language concerned with the definition o the whole database structure and schema is");
	options.add("A) DCL, B) DML, C) DDL, D) all of them");
	answers.add("C) DDL");
	questions.add("Which of the following database object produces the final result to present?");
	options.add("A) forms, B) reports, C) queries, D) tables");
	answers.add("B) reports");
	questions.add("When entering field name, how many characters you can type in maximum?");
	options.add("A) 60, B) 64, C) 68, D) any number of character");
	answers.add("B) 64");
	questions.add("To create relationship between two tables");
	options.add("A) drag the primary key of a table into foreign key of another table, B) drag the foreign key of a table into primary key of another table, C) frag any field from parent table and drop on child table, D) none of them");
	answers.add("A) drag the primary key of a table into foreign key of another table");
	questions.add("Both conditions display on the same row in the design grid when _____ operator is in use");
	options.add("A) OR, B) IN, C) AND, D) LIKE");
	answers.add("C) AND");
	questions.add("Unlike text data type, this can store up to maximum of 65, 535 characters");
	options.add("A) memo, B) data/time, C) number, D) all of them");
	answers.add("A) memo");
	questions.add("A collection of related records in database is known as a");
	options.add("A) table, B) database, C) file, D) none of them");
	answers.add("A) table");
	questions.add("In the form wizard dialog box, the fields from the selected table are displayed in this list box");
	options.add("A) all fields, B) all records, C) available records, D) available fields");
	answers.add("D) available fields");
	questions.add("Which of the field has width 8 bytes?");
	options.add("A) memo, B) number, C) date/time, D) hyperlink");
	answers.add("C) date/time");
	questions.add("What is the different between 'open' and 'open exclusively'?");
	options.add("A) open statement opens access database files and open exclusively opens database files of other program like oracle, B) open exclusive locks whole database so that no one can access it whereas open locks only the record that is being accessed, C) both open and open exclusively are same, D) open exclusive command does not exist is MS Access");
	answers.add("B) open exclusive locks whole database so that no one can access it whereas open locks only the record that is being accessed");
	questions.add("After entering all fields required for a table, if you realize that the third field is not needed, how will you remove?");
	options.add("A) you need to delete the whole table, there is no method to remove a particular field only, B) delete all the fields from third downwards and reenter the required fields again, C) select the third column in datasheet view then delete, D) select the third row in table design view then delete");
	answers.add("D) select the third row in table design view then delete");
	questions.add("While creating relationship when you drag a field to drop into another table the mouse pointer changes into");
	options.add("A) a doctor's sign, B) thin + sign, C) outline rectangle, D) none of them");
	answers.add("C) outline rectangle");
	questions.add("The two form layout types will display multiple records at one time are tabular and _____");
	options.add("A) columnar, B) justified, C) date sheet, D) pivot table");
	answers.add("B) justified");
	questions.add("It is a database object to view, change and analyze data in different ways");
	options.add("A) query, B) form, C) report, D) none of them");
	answers.add("A) query");
	questions.add("A part of database that stores complete information about an entity such as employees, sales, orders, etc.");
	options.add("A) file, B) record, C) field, D) query");
	answers.add("B) record");
	questions.add("The form displays the field name labels down the left side of the column, with the data for each fields just to the right of its corresponding label");
	options.add("A) tabular, B) justified, C) columnar, D) datasheet");
	answers.add("C) columnar");
	questions.add("Which of the following statement is true?");
	options.add("A) foreign key fields don?t allow duplicate values, B) in primary key filed you can enter duplicate value, C) in an indexed field you may or may not enter duplicate value depending upon setting, D) all of them");
	answers.add("C) in an indexed field you may or may not enter duplicate value depending upon setting");
	questions.add("Which of the following is a method to create a new table in MS Access?");
	options.add("A) create a table in design view, B) create table using wizard, C) create table by entering data, D) all of them");
	answers.add("D) all of them");
	questions.add("How can you define a field so that when entering data for that field it will display instead of actual typed text");
	options.add("A) input mask, B) validation rule, C) indexed, D) IME mode");
	answers.add("A) input mask");
	questions.add("What happens when you release mouse pointer after you drop the primary key of a table into foreign key of another table?");
	options.add("A) a relationship is created, B) edit relationship dialog box appears, C) error occurs, D) nothing happens");
	answers.add("B) edit relationship dialog box appears");
	questions.add("You can automatically include all of the field in a table in a query by _______ a strike that appear list box in query design view");
	options.add("A) clicking, B) right clicking, C) double clicking, D) none of them");
	answers.add("C) double clicking");
	questions.add("It is most common type of query. It retrieves records from one or more tables and then displays the");
	options.add("A) parameter, B) select, C) crosstab, D) all of them");
	answers.add("B) select");
	questions.add("To create this, you enter an expression in the design grid that instructs Access to perform a calculation using the current field values");
	options.add("A) formulated field, B) numeric field, C) formula field, D) calculated field");
	answers.add("D) calculated field");
	questions.add("This form displays data in a table layout with field name labels across the top of the nd the corresponding data in rows and columns under each heading");
	options.add("A) columnar, B) justified, C) datasheet, D) tabular");
	answers.add("D) tabular");
	questions.add("Following is not a database model");
	options.add("A) network database model, B) relational database model, C) object oriented database model, D) none of them");
	answers.add("D) none of them");
	questions.add("To create a new table, in which method you don?t need to specify the field type and size?");
	options.add("A) create table in design view, B) create table using wizard, C) create table by entering data, D) all of them");
	answers.add("C) create table by entering data");
	questions.add("A small button with three dots usually displayed at the right of field properties box");
	options.add("A) make button, B) expression button, C) build button, D) none of them");
	answers.add("C) build button");
	questions.add("What do you mean by one to many relationship between student and class table?");
	options.add("A) one student can have many classes, B) one class may have many students, C) many classes may have many students, D) many students may have many classes");
	answers.add("A) one student can have many classes");
	questions.add("The ______ operator will cause a record to be selected only if two or more conditions are satisfied");
	options.add("A) or, B) if or, C) range, D) and");
	answers.add("D) and");
	questions.add("It is a query that when run displays its own dialog box prompting you for information, such as");
	options.add("A) select, B) crosstab, C) parameter, D) append");
	answers.add("C) parameter");
	questions.add("The ascending order of data hierarchy is");
	options.add("A) bit - byte - field - record - file - database, B) bit - byte - record - field - file - database, C) byte - bit - field - record - file - database, D) bit - byte - field - record - database - file");
	answers.add("A) bit - byte - field - record - file - database");
	questions.add("This form displays multiple records, one per row, in the form window");
	options.add("A) datasheet, B) tabular, C) columnar, D) justified");
	answers.add("A) datasheet");
	questions.add("Microsoft Access is a");
	options.add("A) RDBMS, B) OODBMS, C) ORDBMS, D) none of them");
	answers.add("A) RDBMS");
	questions.add("When writing a new table which method can be used to choose fields from standard database and tables");
	options.add("A) create table in design view, B) create table using wizard, C) create table by entering data, D) all of them");
	answers.add("B) create table using wizard");
	questions.add("To sort records in a table");
	options.add("A) open table, click on the field on which the sorting is to be done, then click sort button database toolbar, B) open table, click sort button on database toolbar, choose field based on which to sort, click Ok, C) click the field heading to sort it ascending or descending, D) all of them");
	answers.add("A) open table, click on the field on which the sorting is to be done, then click sort button database toolbar");
	questions.add("In one-to-many relationship the table in 'one' side is called _______ and on 'many' side is called _______");
	options.add("A) child, parent, B) parent, child, C) brother, sister, D) father, son");
	answers.add("B) parent, child");
	questions.add("When a picture or other graphic image is placed in the report header section it will appear");
	options.add("A) once in the bugging of the report, B) at the top of every . every after record break, C) on the 1st and last of the report");
	answers.add("A) once in the bugging of the report");
	questions.add("It is used to calculate and restructure data for easier analysis of your datA. It calculates the sum.");
	options.add("A) crosstab, B) parameter, C) select, D) crosstab");
	answers.add("D) crosstab");
	questions.add("Which of the following database object can be used if you need to mail the invoice to customers?");
	options.add("A) a form, B) a query, C) a report, D) a table");
	answers.add("C) a report");
	questions.add("DCL provides commands to perform actions like");
	options.add("A) change the structure of tables, B) insert, update or delete records and data values, C) authorizing access and other control over database, D) none of them");
	answers.add("C) authorizing access and other control over database");
	questions.add("The graphics can be");
	options.add("A) drawing, B) photograph, movies, C) simulation, D) all of them");
	answers.add("D) all of them");
	questions.add("The brightness of each pixel is");
	options.add("A) compatible, B) incompatible, C) both a and b, D) none of them");
	answers.add("B) incompatible");
	questions.add("The additive color models use concept of");
	options.add("A) printing ink, B) light to display color, C) printing line, D) none of them");
	answers.add("B) light to display color");
	questions.add("Grey scale images have a maximum color depth of");
	options.add("A) 8bit, B) 16bit, C) 24bit, D) 32bit");
	answers.add("A) 8bit");
	questions.add("A major disadvantage of DUST in interactive computer graphics is");
	options.add("A) ability to selectively erase part of an image, B) inability to selectively erase part of image from screen, C) inability to produce bright picture, D) none of them");
	answers.add("B) inability to selectively erase part of image from screen");
	questions.add("Two basic technique for producing color display with a CRT are");
	options.add("A) shadow mask and random scan, B) beam penetrating method and shadow mask method, C) random scan and raster scan, D) none of them");
	answers.add("B) beam penetrating method and shadow mask method");
	questions.add("To generate the characters, which are required");
	options.add("A) hardware, B) software, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Plasma device converts");
	options.add("A) electrical energy into light, B) light into electrical energy, C) light into graphical energy, D) none of them");
	answers.add("A) electrical energy into light");
	questions.add("Computer graphics was first used by");
	options.add("A) William fetter in 1960, B) James fetter in 1969, C) James gosling in 1991, D) John Taylor in 1980");
	answers.add("A) William fetter in 1960");
	questions.add("Each pixel has ______ basic color components");
	options.add("A) two or three, B) one or two, C) three or four, D) none of them");
	answers.add("C) three or four");
	questions.add("The subtractive color model use the concept of");
	options.add("A) printing ink, B) light to display color, C) printing line, D) none of them");
        answers.add("A) printing ink");
	questions.add("Graphics with limited features is known as");
	options.add("A) active graphics, B) passive graphics, C) grayscale images, D) none of them");
	answers.add("B) passive graphics");
	questions.add("Interactive graphics is useful in");
	options.add("A) training pilots, B) computer aided design, C) process control, D) all of them");
	answers.add("D) all of them");
	questions.add("In beam penetrating method of color CRT, two layer of phosphor coated are");
	options.add("A) red and blue, B) red and green, C) blue and green, D) none of them");
	answers.add("B) red and green");
	questions.add("The method which uses array of dots for generating a character is called");
	options.add("A) stoke method, B) bitmap method, C) star bust method, D) none of them");
	answers.add("B) bitmap method");
	questions.add("The component of interactive computer graphics are");
	options.add("A) a light pen, B) display unit, C) bank of switches, D) all of them");
	answers.add("D) all of them");
	questions.add("The quantity of an image depend on");
	options.add("A) no. of pixel used by image, B) no. of lines used by image, C) no. of resolution used by image, D) none of them");
	answers.add("A) no. of pixel used by image");
	questions.add("Color apparent in additive model are the result of");
	options.add("A) reflected light, B) transmission of light, C) flow of light, D) none of them");
	answers.add("B) transmission of light");
	questions.add("Computer of present time have much higher memory and _______ storage capacity");
	options.add("A) much smaller, B) much bigger, C) much slower, D) none of them");
	answers.add("B) much bigger");
	questions.add("The origin of computer graphics was developed in");
	options.add("A) 1950, B) 1960, C) 1970, D) 1990");
	answers.add("A) 1950");
	questions.add("In beam penetrating method of color CRT, which layer is red and which is green");
	options.add("A) outer is red and inner is green, B) inner is red and outer is green, C) inner is red and inner is green, D) none of them");
	answers.add("A) outer is red and inner is green");
	questions.add("The hardware devices contain");
	options.add("A) color printer/black white printer, B) plotters, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Plasma panel have _______ resolution");
	options.add("A) high, B) good, C) both a and b, D) low");
	answers.add("C) both a and b");
	questions.add("Personal computer become powerful during the late");
	options.add("A) 1960, B) 1970, C) 1980, D) 1950");
	answers.add("B) 1970");
	questions.add("Higher the number of pixels, ______ the image quality");
	options.add("A) bad, B) better, C) smaller, D) none of them");
	answers.add("B) better");
	questions.add("Two dimensional color model are");
	options.add("A) RGB and CMKY, B) RGB and CYMK, C) RGB and CMYK, D) none of them");
	answers.add("C) RGB and CMYK");
	questions.add("CRT means");
	options.add("A) common ray tube, B) cathode ray tube, C) common ray tube, D) none of them");
	answers.add("B) cathode ray tube");
	questions.add("The term business graphics came into use in late");
	options.add("A) 1950, B) 1960, C) 1970, D) 1990");
	answers.add("C) 1970");
	questions.add("A shadow mask CRT has _______ phosphor color dots at each pixel position");
	options.add("A) 1, B) 2, C) 3, D) 4");
	answers.add("C) 3");
	questions.add("An example of black and white laser printer is");
	options.add("A) HP 4000, B) MS, C) both a and b, D) none of them");
	answers.add("A) HP 4000");
	questions.add("Plasma panel are also called");
	options.add("A) liquid crystal displays, B) gas discharge display, C) non emissive display, D) none of them");
	answers.add("B) gas discharge display");
	questions.add("Three dimensional computer graphics become effective in the late");
	options.add("A) 1960, B) 1980, C) 1970, D) 1950");
	answers.add("B) 1980");
	questions.add("A pallet can be defined as a finite set of colors for managing the");
	options.add("A) analog images, B) digital images, C) both a and b, D) none of them");
	answers.add("B) digital images");
	questions.add("RGB model are used for");
	options.add("A) computer display, B) printing, C) painting, D) none of them");
	answers.add("A) computer display");
	questions.add("Refresh CRT consist of");
	options.add("A) glass wrapper, B) the phosphor viewing surface, C) the election gun assembly, D) all of them");
	answers.add("D) all of them");
	questions.add("Computer graphics is used in many DPT software as");
	options.add("A) Photoshop, B) paint brush, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which color is produced with the green and red dots only");
	options.add("A) blue, B) yellow, C) magenta, D) white");
	answers.add("B) yellow");
	questions.add("An example of color printer is");
	options.add("A) HP 4000, B) MS, C) both a and b, D) none of them");
	answers.add("B) MS");
	questions.add("The basic graphical interactions are");
	options.add("A) pointing, B) positioning, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which environment has been one of the most accepted tool for computer graphics in business and graphics design studios");
	options.add("A) graphics, B) Macintosh, C) quake, D) multimedia");
	answers.add("B) Macintosh");
	questions.add("Display card are");
	options.add("A) VGA, B) EGA, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("CMYK model are used for");
	options.add("A) computer display, B) printing, C) painting, D) none of them");
	answers.add("B) printing");
	questions.add("The amount of time the phosphor produce light or shine is controlled by chemical composition of the phosphor. This is known as");
	options.add("A) persistence, B) resistance, C) generators, D) none of them");
	answers.add("A) persistence");
	questions.add("Any CRT based display must be refreshing at least _____ times a second");
	options.add("A) 20, B) 30, C) 40, D) 10");
	answers.add("B) 30");
	questions.add("Which color is produced with the blue and red dots");
	options.add("A) blue, B) yellow, C) magenta, D) white");
	answers.add("C) magenta");
	questions.add("Non impact use various techniques to combine three color pigment _____ to produce a range of color patterns");
	options.add("A) cyan, magenta and yellow, B) cyan, white and black, C) cyan, white and yellow, D) black, magenta and yellow");
	answers.add("A) cyan, magenta and yellow");
	questions.add("GUI means");
	options.add("A) graphical user interface, B) graphical user interaction, C) graphics uniform interaction, D) none of them");
	answers.add("A) graphical user interface");
	questions.add("Graphics is one of the ________ major key element in design of multimedia application");
	options.add("A) five, B) three, C) four, D) eight");
	answers.add("A) five");
	questions.add("Display card is used for the purpose of");
	options.add("A) sending graphics data to input unit, B) sending graphics data to output unit, C) receiving graphics data from output unit, D) none of them");
	answers.add("B) sending graphics data to output unit");
	questions.add("The intersection of three primary RGB color produces");
	options.add("A) white color, B) black color, C) magenta color, D) blue color");
	answers.add("A) white color");
	questions.add("The election beam in a color picture tube is refreshed ______ times in a second to make video realistic");
	options.add("A) 15 times, B) 25 times, C) 35 times, D) 45 times");
	answers.add("B) 25 times");
	questions.add("The standardization is needed");
	options.add("A) to make application programs more portable, B) to increase their utility, C) to allow them to use in different application environment, D) all of them");
	answers.add("D) all of them");
	questions.add("Cyan color is produced when the blue and green are activated");
	options.add("A) equally, B) unequally, C) both a and b, D) none of them");
	answers.add("A) equally");
	questions.add("Printers produce output by either");
	options.add("A) impact method, B) non impact method, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Three dimensional graphics become popular in games designing, multimedia and animation during the late");
	options.add("A) 1960, B) 1970, C) 1980, D) 1990");
	answers.add("D) 1990");
	questions.add("Several graphics image file formats that are used by most of graphics system are");
	options.add("A) GIF, B) JPEG, C) TIFF, D) all of them");
	answers.add("D) all of them");
	questions.add("The intersection of primary CMYK color produces");
	options.add("A) white color, B) black color, C) magenta color, D) blue color");
	answers.add("B) black color");
	questions.add("DUST means");
	options.add("A) direct view storage tube, B) domain view storage tube, C) direct view store tube, D) none of them");
	answers.add("A) direct view storage tube");
	questions.add("GKS stands for");
	options.add("A) graphics kernel system, B) graphics kernel stands, C) generic kernel stands, D) none of them");
	answers.add("A) graphics kernel system");
	questions.add("Which technique of color CRT is used for production of realistic image");
	options.add("A) shadow mask method, B) beam penetration method, C) both a and b, D) none of them");
	answers.add("A) shadow mask method");
	questions.add("What is the name of temporary memory where the graphics data is stored to be displayed on screen");
	options.add("A) RAM, B) ROM, C) frame buffer, D) none of them");
	answers.add("C) frame buffer");
	questions.add("The quake, one of the first fully 3D games was released in year");
	options.add("A) 1996, B) 1976, C) 1986, D) 1999");
	answers.add("A) 1996");
	questions.add("The GIF format is much ______ to be downloaded or uploaded over the www");
	options.add("A) slower, B) faster, C) medium, D) none of them");
	answers.add("B) faster");
	questions.add("The RGB model display a much _______ % of the visible band as compared to CMYK");
	options.add("A) lesser, B) larger, C) medium, D) none of them");
	answers.add("B) larger");
	questions.add("DUST is rarely used today as part of");
	options.add("A) input device, B) output device, C) display system, D) none of them");
	answers.add("C) display system");
	questions.add("GKS was developed by the");
	options.add("A) international standards organization, B) national standard organization, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("In which method of CRT, convergence problem occur");
	options.add("A) beam penetration method, B) shadow mask method, C) both a and b, D) none of them");
	answers.add("B) shadow mask method");
	questions.add("The division of the computer screen into rows and columns that define the no. of pixels to display a picture is called");
	options.add("A) persistence, B) resolution, C) encapsulated post script, D) none of them");
	answers.add("B) resolution");
	questions.add("Which one is the basic input device in GUI");
	options.add("A) mouse, B) graphics tablet, C) voice system, D) touch panel");
	answers.add("A) mouse");
	questions.add("Types of computer graphics are");
	options.add("A) vector and raster, B) scalar and raster, C) vector and scalar, D) none of them");
	answers.add("A) vector and raster");
	questions.add("Once a file is saved in JPEG format, some data is lost");
	options.add("A) temporarily, B) permanently, C) both a and b, D) none of them");
	answers.add("B) permanently");
	questions.add("Color depth can be defined by _______ which can be displayed on a display unit");
	options.add("A) bits per pixel, B) bytes per pixel, C) megabyte per pixel, D) none of them");
	answers.add("A) bits per pixel");
	questions.add("In DUST, is there refresh buffer");
	options.add("A) yes, B) no, C) both a and b, D) none of them");
	answers.add("B) no");
	questions.add("The resolution of raster scan display is");
	options.add("A) low, B) high, C) medium, D) none of them");
	answers.add("A) low");
	questions.add("Beam penetration method is used in");
	options.add("A) random scan system, B) raster scan system, C) both a and b, D) none of them");
	answers.add("A) random scan system");
	questions.add("LCD means");
	options.add("A) liquid crystal displays, B) liquid crystal data, C) liquid chrome data, D) none of them");
	answers.add("A) liquid crystal displays");
	questions.add("Vector graphics is composed of");
	options.add("A) pixels, B) paths, C) palette, D) none of them");
	answers.add("B) paths");
	questions.add("EPS image file format is used for");
	options.add("A) vector graphics, B) bitmap, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Each bit represent");
	options.add("A) one color, B) two color, C) three color, D) none of them");
	answers.add("B) two color");
	questions.add("The electron beam in DUST is designed to draw directly to");
	options.add("A) phosphor, B) storage mesh, C) glass, D) none of them");
	answers.add("B) storage mesh");
	questions.add("Random scan systems are designed for");
	options.add("A) line drawing application, B) pixel drawing application, C) color drawing application, D) none of them");
	answers.add("A) line drawing application");
	questions.add("Shadow mask method is used in");
	options.add("A) random scan system, B) raster scan system, C) both a and b, D) none of them");
	answers.add("B) raster scan system");
	questions.add("LCD are commonly used in");
	options.add("A) calculators, B) portable, C) laptop computers, D) all of them");
	answers.add("D) all of them");
	questions.add("Pen or inkjet plotters use the following devices");
	options.add("A) drum, B) flat bed, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Raster graphics are composed of");
	options.add("A) pixels, B) paths, C) palette, D) none of them");
	answers.add("A) pixels");
	questions.add("TIFF (tagged image file format) are used for");
	options.add("A) vector graphics, B) bitmap, C) both a and b, D) none of them");
	answers.add("B) bitmap");
	questions.add("RGB true color model has _______ color depth");
	options.add("A) 24bit, B) 32bit, C) 64bit, D) none of them");
	answers.add("A) 24bit");
	questions.add("The second grid in DUST is called");
	options.add("A) phosphor, B) storage mesh, C) collector, D) none of them");
	answers.add("C) collector");
	questions.add("Solid pattern in random scan display is _______ to fill");
	options.add("A) difficult, B) easy, C) not fill, D) none of them");
	answers.add("A) difficult");
	questions.add("Graphics data is computed by processor in form of");
	options.add("A) electrical signals, B) analog signals, C) digital signals, D) none of them");
	answers.add("A) electrical signals");
	questions.add("LCD is an ______ device");
	options.add("A) emissive, B) non emissive, C) gas discharge, D) none of them");
	answers.add("B) non emissive");
	questions.add("Raster image are more commonly called");
	options.add("A) pix map, B) bitmap, C) both a and b, D) none of them");
	answers.add("B) bitmap");
	questions.add("EPS means");
	options.add("A) entire post script, B) entire post scale, C) encapsulated post script, D) none of them");
	answers.add("C) encapsulated post script");
	questions.add("CMYK true color model has _______ color depth");
	options.add("A) 24bit, B) 32bit, C) 64bit, D) none of them");
	answers.add("B) 32bit");
	questions.add("To increase the energy of these slow moving electron and create a bright picture in DUST, the screen is maintained at a");
	options.add("A) low positive potential, B) high negative potential, C) high positive potential, D) none of them");
	answers.add("C) high positive potential");
	questions.add("Raster scan is ______ expensive than random scan");
	options.add("A) more, B) less, C) both a and b, D) none of them");
	answers.add("B) less");
	questions.add("An example of impact device is");
	options.add("A) electrostatic printer, B) inkjet printer, C) line printer, D) laser printer");
	answers.add("C) line printer");
	questions.add("Plasma panel is an _______ device");
	options.add("A) emissive, B) non emissive, C) expensive, D) none of them");
	answers.add("A) emissive");
	questions.add("The brightness of each pixel is");
	options.add("A) compactible, B) incompatible, C) both a and b, D) none of them");
	answers.add("B) incompatible");
	questions.add("Pixel can be arranged in areolar");
	options.add("A) one dimensional grid, B) two dimensional grid, C) three dimensional grid, D) none of them");
	answers.add("B) two dimensional grid");
	questions.add("A three dimensional graphics has");
	options.add("A) two axes, B) three axes, C) both a and b, D) none of them");
	answers.add("B) three axes");
	questions.add("The transformation in which an object can be shifted to any coordinate position in three dimensional");
	options.add("A) translation, B) scaling, C) rotation, D) all of them");
	answers.add("A) translation");
	questions.add("How many types of projection are");
	options.add("A) 1, B) 2, C) 3, D) 4");
	answers.add("B) 2");
	questions.add("_____ refer to a model that represent all the dimensions of an object external as well as internal");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) composite transformation, D) none of them");
	answers.add("A) wire frame model");
	questions.add("Parallel projection shows the");
	options.add("A) true image of an object, B) true size of an object, C) true shape of an object, D) all of them");
	answers.add("C) true shape of an object");
	questions.add("The perspective projection is more practical because the distant objects appear");
	options.add("A) smaller, B) larger, C) neither smaller nor larger, D) none of them");
	answers.add("A) smaller");
	questions.add("The distance of a line from the projection plane determines");
	options.add("A) its size on projection plane, B) its length on projection plane, C) its width on projection plane, D) its height on projection plane");
	answers.add("A) its size on projection plane");
	questions.add("More the control points of a Bezier curve, _____ the quality of the curve");
	options.add("A) higher, B) lower, C) bad, D) none of them");
	answers.add("A) higher");
	questions.add("______ as the most commonly used boundary presentation for a 3-D graphics object");
	options.add("A) data polygon, B) surface polygon, C) system polygon, D) none of them");
	answers.add("B) surface polygon");
	questions.add("The transformation in which an object can be rotated about origin as well as any arbitrary pivot point");
	options.add("A) translation, B) scaling, C) rotation, D) all of them");
	answers.add("C) rotation");
	questions.add("The types of projection are");
	options.add("A) parallel projection and quadric projection, B) orthographic projection and oblique projection, C) oblique projection and quadric projection, D) none of them");
	answers.add("B) orthographic projection and oblique projection");
	questions.add("______ refers to the result obtained by multiplying the matrix of the individual transformation");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) composite transformation, D) none of them");
	answers.add("C) composite transformation");
	questions.add("Projection rays (projectors) emanate from a");
	options.add("A) COP (center of projection), B) intersects projection plane, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Sp line curve can be either");
	options.add("A) Bezier sp line, B) B sp line, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("The further the line from the projection plane, ______ its image on the projection plane");
	options.add("A) smaller, B) larger, C) neither smaller nor larger, D) none of them");
	answers.add("A) smaller");
	questions.add("______ is one of the function that is used to specify a single plane surface");
	options.add("A) meta-ball model, B) fill area, C) reflection, D) none of them");
	answers.add("B) fill area");
	questions.add("The sweep representation of an object refers to the");
	options.add("A) 2D representation, B) 3D representation, C) both a and b, D) none of them");
	answers.add("B) 3D representation");
	questions.add("Raster images are known as");
	options.add("A) pix map, B) bitmap, C) both a and b, D) none of them");
	answers.add("B) bitmap");
	questions.add("A three dimensional object can also be represented using");
	options.add("A) method, B) equation, C) point, D) none of them");
	answers.add("B) equation");
	questions.add("The transformation in which the size of an object can be modified in x-direction, y-direction and z-direction");
	options.add("A) translation, B) scaling, C) rotation, D) all of them");
	answers.add("B) scaling");
	questions.add("________ are the three dimensional analogs of quad trees");
	options.add("A) quadric, B) octrees, C) geometry, D) none of them");
	answers.add("B) octrees");
	questions.add("The projection in which the projection plane is allowed to intersect the x,y and z-axes at equal distances");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) isometric projection, D) back face removal");
	answers.add("C) isometric projection");
	questions.add("The sender of projection for parallel projection is at");
	options.add("A) zero, B) infinity, C) one, D) none of them");
	answers.add("B) infinity");
	questions.add("Bezier sp line always passes through");
	options.add("A) first and second control point, B) does not pass from first and second control point, C) both a and b, D) none of them");
	answers.add("A) first and second control point");
	questions.add("The Bezier curve obtained from the four control points is called a");
	options.add("A) square Bezier curve, B) cubic Bezier curve, C) hectare Bezier curve, D) rectangle Bezier curve");
	answers.add("B) cubic Bezier curve");
	questions.add("Meta-ball is used to descried");
	options.add("A) simplest object, B) complex object, C) composite object, D) none of them");
	answers.add("C) composite object");
	questions.add("Vector graphics is composed of");
	options.add("A) pixels, B) paths, C) palette, D) none of them");
	answers.add("B) paths");
	questions.add("An ____ can be considered as an extension of spherical surface");
	options.add("A) Bezier, B) ellipsoid, C) shearing, D) none of them");
	answers.add("B) ellipsoid");
	questions.add("Apart form the basic transformation ______ are also used");
	options.add("A) shearing, B) reflection, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("By which more complex objects can be constructed");
	options.add("A) quadric surfaces, B) wire frame model, C) composite transformation, D) none of them");
	answers.add("A) quadric surfaces");
	questions.add("In which projection the plane normal to the projection has equal angles with these three axes");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) isometric projection, D) back face removal");
	answers.add("C) isometric projection");
	questions.add("In orthographic projection, engineering use");
	options.add("A) top view of an object, B) front view of an object, C) side view of an object, D) all of them");
	answers.add("D) all of them");
	questions.add("The equation for describing surface of 3D plane are");
	options.add("A) Ax+By+Cz+D=0, B) Ax+By+Cz=0, C) both a and b, D) none of them");
	answers.add("A) Ax+By+Cz+D=0");
	questions.add("The shape of a Bezier curve primarily depends upon the");
	options.add("A) position of control points, B) distance of control points, C) position of control panel, D) none of them");
	answers.add("A) position of control points");
	questions.add("Super quadrics is a class of object that contain");
	options.add("A) data, B) codes, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("CRT means");
	options.add("A) common ray tube, B) cathode ray tube, C) common ray tube, D) none of them");
	answers.add("B) cathode ray tube");
	questions.add("RGB true color model has _______ color depth");
	options.add("A) 24bit, B) 32bit, C) 64bit, D) none of them");
	answers.add("A) 24bit");
	questions.add("_______ curve is one of the sp line approximation methods");
	options.add("A) Bezier, B) ellipsoid, C) shearing, D) none of them");
	answers.add("A) Bezier");
	questions.add("In which transformation the shape of an object can be modified in any direction depending upon the value assigned to them");
	options.add("A) reflection, B) shearing, C) scaling, D) none of them");
	answers.add("B) shearing");
	questions.add("______ refers to the common elements of graphics scenes, often used in graphics packages as primitive components");
	options.add("A) quadric surfaces, B) wire frame model, C) composite transformation, D) none of them");
	answers.add("A) quadric surfaces");
	questions.add("______ is a simple object space algorithm that removes about half of the total polygon in an image as");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) isometric projection, D) back face removal");
	answers.add("D) back face removal");
	questions.add("The orthographic projection that show more than one side of an object are called");
	options.add("A) axonometric projection, B) isometric projection, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("the object refers to the 3D representation through linear, circular or some other representation are called");
	options.add("A) quadric surfaces, B) sweep representation, C) torus, D) none of them");
	answers.add("B) sweep representation");
	questions.add("The no. of control points in a Bezier curve ensures the");
	options.add("A) jaggies of curve, B) smoothness of curve, C) straightness of curve, D) none of them");
	answers.add("B) smoothness of curve");
	questions.add("When two molecules move apart, which effect on molecular shapes");
	options.add("A) stretching, B) snapping, C) contracting, D) all of them");
	answers.add("D) all of them");
	questions.add("A Bezier curve is a polynomial of degree _____ the no. of control points used");
	options.add("A) one more than, B) one less than, C) two less than, D) none of them");
	answers.add("B) one less than");
	questions.add("In which transformation, the mirror image of an object can be seen with respect to x-axis, y-axis, z-axis as well as with respect to an arbitrary line");
	options.add("A) reflection, B) shearing, C) translation, D) none of them");
	answers.add("A) reflection");
	questions.add("_______ refer to the shapes created by union, intersection and difference of given shapes");
	options.add("A) wire frame model, B) constructive solid geometry methods, C) composite transformation, D) none of them");
	answers.add("B) constructive solid geometry methods");
	questions.add("By which we can take a view of an object from different directions and different distances");
	options.add("A) projection, B) rotation, C) translation, D) scaling");
	answers.add("A) projection");
	questions.add("The projection that can be viewed as the projection that has a center of projection at a finite distance from the plane of projection are called");
	options.add("A) parallel projection, B) perspective projection, C) isometric projection, D) none of them");
	answers.add("B) perspective projection");
	questions.add("The most basic transformation that are applied in three-dimensional planes are");
	options.add("A) translation, B) scaling, C) rotation, D) all of them");
	answers.add("D) all of them");
	questions.add("In OSI network architecture, the dialogue control and token management are responsibility of");
	options.add("A) session layer, B) network layer, C) transport layer, D) data link layer");
	answers.add("A) session layer");
	questions.add("Which of the following statement is incorrect?");
	options.add("A) the difference between synchronous and asynchronous transmission is the clocking derived from the data in synchronous transmission, B) half duplex line is a communication line in which data can move in two direction, but not at the same time, C) teleprocessing combines telecommunications and DP techniques in online activities, D) batch processing is the preferred processing mode for telecommunication operation");
	answers.add("D) batch processing is the preferred processing mode for telecommunication operation");
	questions.add("The loss in signal power as light travels down the fiber is called");
	options.add("A) attenuation, B) prorogation, C) scattering, D) interruption");
	answers.add("A) attenuation");
	questions.add("A band is always equivalent to");
	options.add("A) a byte, B) a bit, C) 100 bits, D) none of them");
	answers.add("D) none of them");
	questions.add("In OSI network architecture, the routing is performed by");
	options.add("A) network layer, B) data link layer, C) transport layer, D) session layer");
	answers.add("A) network layer");
	questions.add("Which of the following is considered a broad band communication channel?");
	options.add("A) coaxial cable, B) fiber optic cable, C) microwave circuits, D) all of them");
	answers.add("D) all of them");
	questions.add("Avalanche photodiode receivers can detect bits of transmitted data by receiving");
	options.add("A) 100 photons, B) 200 photons, C) 2000 photons, D) 300 photons");
	answers.add("B) 200 photons");
	questions.add("A remote batch-processing operation in which data is solely input to a central computer would require");
	options.add("A) telephone lines, B) simplex lines, C) mixed bad channel, D) all of them");
	answers.add("B) simplex lines");
	questions.add("Which of the following performs modulation and demodulation?");
	options.add("A) fiber optics, B) satellite, C) coxical cable, D) modem");
	answers.add("D) modem");
	questions.add("Which of the following is not a transmission medium?");
	options.add("A) telephone lines, B) coaxial cables, C) modem, D) microwave systems");
	answers.add("C) modem");
	questions.add("Communication circuits that transmit data in both directions but not at the same time are operating in");
	options.add("A) a simplex mode, B) a half duplex mode, C) a full duplex mode, D) an asynchronous mode");
	answers.add("B) a half duplex mode");
	questions.add("An example of a medium speed, switched communications service is");
	options.add("A) series 1000, B) data phone 50, C) DDD, D) all of them");
	answers.add("C) DDD");
	questions.add("The transmission signal coding method of TI carrier is called");
	options.add("A) bipolar, B) NRZ, C) Manchester, D) binary");
	answers.add("A) bipolar");
	questions.add("The process of converting analog signals into digital signals so they can be processed by a receiving computer is referred to as");
	options.add("A) modulation, B) demodulation, C) synchronizing, D) digitizing");
	answers.add("D) digitizing");
	questions.add("Which of the following does not allow multiple uses or devices to share one communication line?");
	options.add("A) doublplexer, B) multiplexer, C) concentrator, D) controller");
	answers.add("A) doublplexer");
	questions.add("Which of the following is considered a broad band communication channel?");
	options.add("A) coaxial cable, B) fiber optic cable, C) microwave circuits, D) all of them");
	answers.add("D) all of them");
	questions.add("In communicating satellite, multiple repeaters are known as");
	options.add("A) detectors, B) modulator, C) stations, D) transponders");
	answers.add("D) transponders");
	questions.add("While transmitting odd-parity coded symbols, the number of zeros in each symbol is");
	options.add("A) odd, B) even, C) both a and b, D) unknown");
	answers.add("D) unknown");
	questions.add("Which of the following is required to communicate between two computers?");
	options.add("A) communications software, B) protocol, C) communication hardware, D) all of them");
	answers.add("D) all of them");
	questions.add("How many OSI layers are covered in the X.25 standard?");
	options.add("A) 2, B) 3, C) 7, D) 6");
	answers.add("B) 3");
	questions.add("Which of the following signal is not standard RS-232-C signal?");
	options.add("A) VDR, B) RTS, C) CTS, D) DSR");
	answers.add("A) VDR");
	questions.add("Data communications monitors available on the software marked include");
	options.add("A) ENVIRON/1, B) TOTAL, C) BPL, D) Telnet");
	answers.add("A) ENVIRON/1");
	questions.add("An example of an analog communication method is");
	options.add("A) laser beam, B) microwave, C) voice grade telephone line, D) all of them");
	answers.add("D) all of them");
	questions.add("Which of the following is an advantage to using fiber optics data transmission?");
	options.add("A) resistance to data theft, B) fast data transmission rate, C) low noise level, D) all of them");
	answers.add("D) all of them");
	questions.add("Layer one of the OSI model is");
	options.add("A) physical layer, B) link layer, C) transport layer, D) network layer");
	answers.add("A) physical layer");
	questions.add("Which of the following statement is incorrect?");
	options.add("A) multiplexers are designed to accept data from several I/O devices and transmit a unified stream of data on one communication line, B) HDLC is a standard synchronous communication protocol, C) RTS/CTS is the ay the DTE indicates that it is ready to transmit data and the way the DCW indicates that it is ready to accept data, D) RTS/CTS is the way the terminal indicates ringing");
	answers.add("D) RTS/CTS is the way the terminal indicates ringing");
	questions.add("Which of the following statement is incorrect?");
	options.add("A) the difference between synchronous and asynchronous transmission is the clocking derived from the data in synchronous transmission, B) half duplex line is a communication line in which data can move in two direction, but not at the same time, C) teleprocessing combines telecommunications and DP techniques in online activities, D) batch processing is the preferred processing mode for telecommunication operation");
	answers.add("D) batch processing is the preferred processing mode for telecommunication operation");
	questions.add("Number of bits per symbol used in Baudot code is");
	options.add("A) 7, B) 5, C) 8, D) 8");
	answers.add("B) 5");
	questions.add("What is the main difference between DDCMP and SDLC?");
	options.add("A) DDCMP does not need special hardware to final the beginning of a message, B) DDCMP has a message header, C) SDLC has an IP address, D) SDLC does not use CRC");
	answers.add("A) DDCMP does not need special hardware to final the beginning of a message");
	questions.add("The x.25 standard specifies a");
	options.add("A) technique for start-stop data, B) technique for dial access, C) DTE/DCE interface, D) data bit rate");
	answers.add("C) DTE/DCE interface");
	questions.add("Which of the following is an advantage to using fiber optics data transmission?");
	options.add("A) resistance to data theft, B) fast data transmission rate, C) low noise level, D) all of them");
	answers.add("D) all of them");
	questions.add("An example of digital, rather than analog, communication is");
	options.add("A) DDD, B) DDS, C) WATS, D) DDT");
	answers.add("B) DDS");
	questions.add("Terminals are required for");
	options.add("A) real time batch processing & time-sharing, B) real time, time sharing & distributed message processing, C) real time, distributed processing & manager inquiry, D) real time, time sharing & message switching");
	answers.add("D) real time, time sharing & message switching");
	questions.add("Which of the following statement is incorrect?");
	options.add("A) multiplexers are designed to accept data from several I/O devices and transmit a unified stream of data on one communication line, B) HDLC is a standard synchronous communication protocol, C) RTS/CTS is the ay the DTE indicates that it is ready to transmit data and the way the DCW indicates that it is ready to accept data, D) RTS/CTS is the way the terminal indicates ringing");
	answers.add("D) RTS/CTS is the way the terminal indicates ringing");
	questions.add("Which of the following communication modes support wo-way traffic but in only one direction at a time?");
	options.add("A) simplex, B) half duplex, C) three-quarters duplex, D) all of them");
	answers.add("B) half duplex");
	questions.add("Which of the following is required to communicate between two computers?");
	options.add("A) communications software, B) protocol, C) communication hardware, D) all of them");
	answers.add("D) all of them");
	questions.add("The receive equalizer reduces delay distortions using a");
	options.add("A) tapped delay lines, B) gearshifts, C) descrambler, D) difference engine");
	answers.add("A) tapped delay lines");
	questions.add("In a synchronous modem, the receive equalizer is known as");
	options.add("A) adaptive equalizer, B) impairment equalizer, C) statistical equalizer, D) compromise equalizer");
	answers.add("A) adaptive equalizer");
	questions.add("Which of the following signal is not standard RS-232-C signal?");
	options.add("A) VDR, B) RTS, C) CTS, D) DSR");
	answers.add("A) VDR");
	questions.add("Which of the following unit might be used by a company to satisfy its growing communication needs?");
	options.add("A) front end processor, B) multiplexer, C) controller, D) all of them");
	answers.add("D) all of them");
	questions.add("The transmission signal coding method of TI carrier is called");
	options.add("A) bipolar, B) NRZ, C) Manchester, D) binary");
	answers.add("A) bipolar");
	questions.add("The channel in the data communication model can be");
	options.add("A) postal mail services, B) telephone lines, C) radio lines, D) any of the above");
	answers.add("D) any of the above");
	questions.add("A data terminal serves as an");
	options.add("A) effector, B) sensor, C) both a and b, D) none of them");
	answers.add("C) both a and b");
	questions.add("Which of the following does not allow multiple uses or devices to share one communication line?");
	options.add("A) doublplexer, B) multiplexer, C) concentrator, D) controller");
	answers.add("A) doublplexer");
	questions.add("What is number of separate protocol layers at the serial interface gateway specified by the x.25 standard?");
	options.add("A) 4, B) 2, C) 6, D) 3");
	answers.add("D) 3");
	questions.add("The interactive transmission of data within a time sharing system may be best suited to");
	options.add("A) simplex lines, B) half-duplex lines, C) full duplex lines, D) biflex lines");
	answers.add("B) half-duplex lines");
	questions.add("Which of the following transmission systems provide the highest rate to individual device?");
	options.add("A) computer bus, B) telephone lines, C) voice and mode, D) lease lines");
	answers.add("A) computer bus");
	questions.add("A protocol is a set of rules governing a time sequence of events that must take place");
	options.add("A) between peers, B) between an interface, C) between modems, D) across an interface");
	answers.add("A) between peers");
	questions.add("Which of the following is not a transmission medium?");
	options.add("A) telephone lines, B) coaxial cables, C) modem, D) microwave systems");
	answers.add("C) modem");
	questions.add("The iterative transmission of data within a time sharing system may be best suited to");
	options.add("A) simplex lines, B) half-duplex lines, C) full duplex lines, D) biflex lines");
	answers.add("B) half-duplex lines");
	questions.add("If a computer on the network shares resources for others to use, it is called");
	options.add("A) server, B) client, C) mainframe, D) none of them");
	answers.add("A) server");
	questions.add("ISO stands for");
	options.add("A) international standards organization, B) international student organization, C) integrated services organization, D) none of them");
	answers.add("A) international standards organization");
	questions.add("ISDN is an example of ________ network");
	options.add("A) circuit switched, B) packet switched, C) both a and b, D) none of them");
	answers.add("A) circuit switched");
	questions.add("Print server uses _____ which is a buffer that holds data before it is send to the printer");
	options.add("A) queue, B) spool, C) both a and b, D) node");
	answers.add("B) spool");
	questions.add("What is the max cable length of STP?");
	options.add("A) 100 ft., B) 200 ft., C) 100 m, D) 200 m");
	answers.add("D) 200 m");
	questions.add("What is the central device in star technology?");
	options.add("A) STP server, B) hub/switch, C) PDC, D) router");
	answers.add("B) hub/switch");
	questions.add("Terminators are used in ______ topology");
	options.add("A) bus, B) star, C) ring, D) none of them");
	answers.add("A) bus");
	questions.add("ISO OSI model is used in");
	options.add("A) stand alone PC, B) network environment, C) both a and b, D) none of them");
	answers.add("B) network environment");
	questions.add("X.25 is an example of ______ network");
	options.add("A) circuit switched, B) packet switched, C) both a and b, D) none of them");
	answers.add("B) packet switched");
	questions.add("A standalone program that has been modified to work on a LAN by including currency controls such as");
	options.add("A) LAN intrinsic software, B) LAN aware software, C) groupware, D) LAN ignorant software");
	answers.add("A) LAN intrinsic software");
	questions.add("What is the max data capacity of STP?");
	options.add("A) 100 mbps, B) 10 mbps, C) 1000 mbps, D) 10000 mbps");
	answers.add("A) 100 mbps");
	questions.add("What is max data capacity for optical fiber cable?");
	options.add("A) 10 mbps, B) 100 mbps, C) 1000 mbps, D) 10000 mbps");
	answers.add("C) 1000 mbps");
	questions.add("In _______ topology, if a computer's network cable is broken, whole network goes down");
	options.add("A) bus, B) star, C) ring, D) none of them");
	answers.add("A) bus");
	questions.add("Network cable lies on _______ layer");
	options.add("A) application, B) network, C) physical, D) none of them");
	answers.add("B) network");
	questions.add("______ allows LAN users to share computer programs and data");
	options.add("A) communication server, B) print server, C) file server, D) none of them");
	answers.add("C) file server");
	questions.add("The _____ portion of LAN management software restricts access, records user activities and audit");
	options.add("A) configuration management, B) security management, C) performance management, D) none of them");
	answers.add("B) security management");
	questions.add("Which connector STP uses?");
	options.add("A) BNC, B) RJ-11, C) RJ-45, D) RJ-69");
	answers.add("C) RJ-45");
	questions.add("Which of the following architecture uses CSMA/CD access method?");
	options.add("A) ARC net, B) Ethernet, C) both a and b, D) none of them");
	answers.add("B) Ethernet");
	questions.add("For large networks, ________ topology is used");
	options.add("A) bus, B) star, C) ring, D) none of them");
	answers.add("B) star");
	questions.add("______ layer decides which physical pathway the data should take");
	options.add("A) application, B) network, C) physical, D) none of them");
	answers.add("C) physical");
	questions.add("TCP/IP is a");
	options.add("A) network hardware, B) network software, C) protocol, D) none of them");
	answers.add("C) protocol");
	questions.add("Which is the lowest layer of TCP/IP model:");
	options.add("A) host to host layer, B) network access layers, C) internet layer, D) application layer");
	answers.add("B) network access layers");
	questions.add("Default port for HTTP");
	options.add("A) 23, B) 80, C) 21, D) 25");
	answers.add("D) 25");
	questions.add("Which is the IP source routing method");
	options.add("A) SSR, B) LSR, C) LLR, D) both a and b");
	answers.add("D) both a and b");
	questions.add("Which agency assign Ips");
	options.add("A) IEEE, B) ANSI, C) ICANN, D) BSNL");
	answers.add("C) ICANN");
	questions.add("In which method we can connect to internet");
	options.add("A) dial-up, B) SLIP, C) PPP, D) all of them");
	answers.add("D) all of them");
	questions.add("OSI stands for");
	options.add("A) open system interface, B) out system interface, C) open system interconnection, D) out system interconnection");
	answers.add("C) open system interconnection");
	questions.add("______ is an access channel for computers to exchange information");
	options.add("A) socket, B) port, C) gateways, D) protocol");
	answers.add("B) port");
	questions.add("Which is not the part of the UDP datagram");
	options.add("A) source port, B) destination port, C) checksum, D) none of them");
	answers.add("D) none of them");
	questions.add("In a TCP header source and destination header contains");
	options.add("A) 8 bits, B) 16 bits, C) 32 bits, D) 128 bits");
	answers.add("C) 32 bits");
	questions.add("Which is the component of IP");
	options.add("A) client identifier, B) network identifier, C) host identifier, D) both b and c");
	answers.add("B) network identifier");
	questions.add("URL stands for");
	options.add("A) universal resource locator, B) uniform resource locator, C) uniform radio locator, D) none of them");
	answers.add("B) uniform resource locator");
	questions.add("Which is not the browser");
	options.add("A) Internet Explorer, B) Opera, C) Mozilla, D) Google");
	answers.add("B) Opera");
	questions.add("TCP/IP mainly used for");
	options.add("A) file transfer, B) email, C) remote login service, D) all of them");
	answers.add("D) all of them");
	questions.add("How many ports a computer may have");
	options.add("A) 256, B) 128, C) 65535, D) 1024");
	answers.add("C) 65535");
	questions.add("Which is the type of socket?");
	options.add("A) datagram, B) stream, C) raw, D) all of them");
	answers.add("D) all of them");
	
    }



    public static void main(String[] args) {
        new Computer3_Quiz(name).setVisible(true); 
    }

}
